#!/bin/sh

app_dir=/usr/lib/rikkahub

exec /usr/bin/java \
  -Dcompose.application.resources.dir="$app_dir/resources" \
  -Dcompose.application.configure.swing.globals=true \
  -Dskiko.library.path="$app_dir" \
  -cp "$app_dir/*" \
  me.rerere.rikkahub.desktop.MainKt "$@"
