package me.rerere.rikkahub.desktop

internal val GermanDesktopTranslations = mapOf(
    "settings.language" to "Sprache",
    "settings.language_description" to "Sprache der Desktop-App auswählen",
    "settings.title" to "Einstellungen",
    "settings.subtitle" to "Darstellung, Interaktion und Modelle",
    "settings.back" to "Zurück",
    "settings.color_mode" to "Farbmodus",
    "settings.color_mode_description" to "Dem System folgen oder ein festes helles/dunkles Thema verwenden",
    "settings.system" to "System",
    "settings.light" to "Hell",
    "settings.dark" to "Dunkel",
    "settings.theme_color" to "Themenfarbe",
    "settings.theme_color_description" to "Wählen Sie eine Akzentfarbe und passende Töne für die Oberfläche",
    "settings.font" to "Oberflächenschrift",
    "settings.font_description" to "%s; Codeblöcke bleiben monospaced",
    "settings.chat_font_size" to "Chat-Schriftgröße",
    "sidebar.welcome" to "Willkommen zurück",
    "sidebar.new_chat" to "Neuer Chat",
    "sidebar.search_chats" to "Chats suchen",
    "sidebar.back_to_chats" to "Zurück zu Chats",
    "sidebar.favorite_messages" to "Favorisierte Nachrichten",
    "sidebar.search" to "Suchen",
    "sidebar.all_assistants" to "Alle Assistenten",
    "sidebar.all_tags" to "Alle Tags",
    "sidebar.chats" to "Chats",
    "chat.open_conversations" to "Konversationen öffnen",
    "chat.options" to "Konversationsoptionen",
    "chat.rename" to "Umbenennen",
    "chat.export_markdown" to "Markdown exportieren",
    "chat.generate_title" to "Titel generieren",
    "chat.statistics" to "Gesprächsstatistik",
    "chat.generate_suggestions" to "Antwortvorschläge generieren",
    "chat.compress_history" to "Verlauf komprimieren",
    "chat.set_system_prompt" to "Systemprompt festlegen",
    "chat.edit_system_prompt" to "Systemprompt bearbeiten",
    "chat.enable_lorebooks" to "Lorebooks für dieses Gespräch aktivieren",
    "chat.disable_lorebooks" to "Lorebooks für dieses Gespräch deaktivieren",
    "chat.move_to_folder" to "In Ordner verschieben",
    "chat.uncategorized" to "Nicht kategorisiert",
    "chat.new_folder" to "Neuer Ordner",
    "chat.close" to "Schließen",
    "message.sources" to "Quellen",
    "message.source_number" to "Quelle %d",
    "message.input_tokens" to "Eingabe-Token",
    "message.output_tokens" to "Ausgabe-Token",
    "message.cached_tokens" to "Gecachte Token",
    "message.previous_version" to "Vorherige Version",
    "message.next_version" to "Nächste Version",
    "message.copy" to "Kopieren",
    "message.fork" to "Von hier abzweigen",
    "message.regenerate" to "Neu generieren",
    "message.translate" to "Übersetzen",
    "message.favorite" to "Favorisieren",
    "message.unfavorite" to "Aus Favoriten entfernen",
    "message.edit" to "Bearbeiten",
    "message.delete" to "Löschen",
    "empty_chat.greeting" to "Wie kann ich helfen?",
    "composer.collapse" to "Editor einklappen",
    "composer.expand" to "Editor ausklappen",
    "composer.add_attachment" to "Anhang hinzufügen",
    "composer.enable_web_search" to "Websuche aktivieren",
    "composer.disable_web_search" to "Websuche deaktivieren",
    "composer.quick_messages" to "Schnellnachrichten",
    "composer.manage_assistants" to "Assistenten und Tags verwalten",
    "composer.stop_generation" to "Generierung stoppen",
    "composer.send" to "Senden; gedrückt halten, um ohne Antwort hinzuzufügen",
    "settings.show_user_avatar" to "Benutzeravatar anzeigen",
    "settings.show_user_avatar_description" to "Zeigt einen Avatar neben Benutzernachrichten an",
    "settings.user_nickname" to "Benutzername",
    "settings.user_nickname_description" to "Wird neben Benutzernachrichten angezeigt; Standard „Du“ wenn leer",
    "settings.user_nickname_placeholder" to "Du",
    "settings.show_model_icon" to "Modellsymbol anzeigen",
    "settings.show_model_icon_description" to "Zeigt das Modellsymbol neben Assistentennachrichten an",
    "settings.show_model_name" to "Modellnamen anzeigen",
    "settings.show_model_name_description" to "Zeigt den Modellnamen über Assistentennachrichten an",
    "settings.assistant_bubble" to "Assistentensprechblase",
    "settings.assistant_bubble_description" to "Zeigt Assistententext in einer gefüllten Blase an",
    "settings.message_timestamp" to "Nachrichtenzeit",
    "settings.message_timestamp_description" to "Zeigt die Erstellungszeit im Kopf jeder Nachricht an",
    "settings.reasoning" to "Denkinhalt",
    "settings.reasoning_description" to "Zeigt die von kompatiblen Modellen zurückgegebenen Denkprozesse an",
    "settings.collapse_reasoning" to "Denkinhalt nach Abschluss einklappen",
    "settings.collapse_reasoning_description" to "Denkinhalt nur während der Antwortgenerierung ausklappen",
    "settings.code_wrap" to "Codeblöcke umbrechen",
    "settings.code_wrap_description" to "Lange Codezeilen umbrechen statt horizontal zu scrollen",
    "settings.chinese_typography" to "Chinesische Typografie",
    "settings.chinese_typography_description" to "Abstände zwischen chinesischem und lateinischem Text, Zahlen oder Symbolen einfügen",
    "settings.mermaid_rendering" to "Mermaid-Diagramme rendern",
    "settings.mermaid_rendering_description" to "Mermaid-Codeblöcke als interaktive Diagramme rendern",
    "settings.mermaid_cli" to "Mermaid CLI erlauben",
    "settings.mermaid_cli_description" to "Die lokale Ausführung von Mermaid CLI zum Rendern von Diagrammen erlauben",
    "settings.mermaid_cli_path" to "Mermaid-CLI-Pfad",
    "settings.mermaid_cli_path_description" to "Leer lassen, um PATH, globales npm und lokale Benutzerpfade automatisch zu erkennen",
    "settings.mermaid_system_browser" to "Systembrowser verwenden",
    "settings.mermaid_system_browser_description" to "Mermaid CLI die Verwendung eines installierten Chromium-basierten Browsers erlauben",
    "settings.send_on_enter" to "Mit Enter senden",
    "settings.send_on_enter_description" to "Wenn aus: Strg+Enter sendet, Enter fügt eine neue Zeile ein",
    "settings.auto_scroll" to "Automatisch scrollen",
    "settings.auto_scroll_description" to "Neuem Denk- und Antwortinhalt während der Generierung folgen",
    "settings.smooth_scroll" to "Sanftes Scrollen",
    "settings.smooth_scroll_description" to "Mausrad-Scrollen in der Chatansicht animieren",
    "settings.message_navigation" to "Nachrichtennavigation",
    "settings.message_navigation_description" to "Zeigt nach dem Scrollen Schaltflächen für Anfang, Zurück, Weiter und Ende an",
    "settings.message_navigation_left" to "Nachrichtennavigation links",
    "settings.message_navigation_left_description" to "Standardmäßig auf der rechten Seite des Nachrichtenbereichs",
    "settings.export_backup" to "Sicherung exportieren",
    "settings.export_backup_description" to "Anbieter, Assistenten, Einstellungen und Chats als JSON speichern",
    "settings.export" to "Exportieren",
    "settings.import_backup" to "Sicherung importieren",
    "settings.import_backup_description" to "Aktuelle Desktop-Daten durch eine RikkaHub-Sicherung ersetzen",
    "settings.import" to "Importieren",
    "settings.reset_data" to "Alle Daten zurücksetzen",
    "settings.reset_data_description" to "Lokale Anbieter, Assistenten, Einstellungen und Chats löschen. Dies kann nicht rückgängig gemacht werden.",
    "settings.reset" to "Zurücksetzen",
    "settings.web_search" to "Websuchdienst",
    "settings.web_search_description" to "Wenn konfiguriert, externen Suchdienst verwenden; ansonsten native Suche des Modellanbieters",
    "settings.searxng_url" to "SearXNG-URL",
    "settings.api_key" to "API-Schlüssel",
    "settings.search_result_count" to "%d Ergebnisse pro Suche",
    "settings.test_search" to "Suche testen",
    "settings.search_test_success" to "Websuchverbindung funktioniert",
    "settings.search_test_failed" to "Suchtest fehlgeschlagen",
    "settings.add_assistant" to "Assistenten hinzufügen",
    "settings.assistant_name" to "Assistentenname",
    "settings.copy_assistant" to "Assistenten kopieren",
    "settings.delete_assistant" to "Assistenten löschen",
    "settings.tags" to "Tags (durch Kommas getrennt)",
    "settings.model_inherit" to "Modell (leer lassen für den Anbieterstandard)",
    "settings.select_model" to "Modell auswählen",
    "settings.system_prompt_inherit" to "Systemprompt (leer lassen für den Anbieterstandard)",
    "settings.apply_preset" to "Voreinstellung anwenden",
    "settings.add_provider" to "Anbieter hinzufügen",
    "settings.provider_name" to "Anbietername",
    "settings.delete_provider" to "Anbieter löschen",
    "settings.base_url" to "Basis-URL",
    "settings.hide_api_key" to "API-Schlüssel ausblenden",
    "settings.show_api_key" to "API-Schlüssel anzeigen",
    "settings.model" to "Modell",
    "settings.select_discovered_model" to "Entdecktes Modell auswählen",
    "settings.test_and_fetch_models" to "Testen und Modelle abrufen",
    "settings.provider_saved" to "Anbietereinstellungen gespeichert",
    "settings.save_provider" to "Anbieter speichern",
    "settings.back_to_chat" to "Zurück zum Chat",
    "settings.unsaved_changes_title" to "Änderungen speichern?",
    "settings.unsaved_changes_description" to "Die Einstellungen wurden geändert. Vor dem Verlassen speichern?",
    "settings.discard_changes" to "Nicht speichern",
    "settings.reset_confirmation_title" to "Alle Daten zurücksetzen?",
    "settings.reset_confirmation_description" to "Dies löscht dauerhaft die Desktop-Anbietergeheimnisse, Assistenten, Einstellungen und jede Konversation.",
    "settings.confirm_reset" to "Daten zurücksetzen",
    "common.cancel" to "Abbrechen",
    "common.save" to "Speichern",
    "common.submit" to "Senden",
    "common.expand" to "Ausklappen ",
    "common.collapse" to "Einklappen ",
    "message.thinking" to "Denkt...",
    "message.translation" to "Übersetzung",
    "attachment.audio" to "Audio",
    "timeline.execution" to "Ausführung",
    "timeline.expand_execution" to "Ausführung aufklappen",
    "timeline.collapse_execution" to "Ausführung einklappen",
    "timeline.expand_steps" to "%d Schritte aufklappen",
    "timeline.reasoning" to "Denken",
    "timeline.reasoning_duration" to "%s Sekunden nachgedacht",
    "timeline.today" to "Heute",
    "timeline.yesterday" to "Gestern",
    "timeline.day_before_yesterday" to "Vorgestern",
    "timeline.days_ago" to "Vor %d Tagen",
    "sidebar.recent" to "Kürzlich",
    "sidebar.most_active" to "Am häufigsten verwendet",
    "sidebar.sort_recent" to "Nach letzter Aktivität sortieren",
    "sidebar.sort_most_active" to "Nach Nutzungshäufigkeit sortieren",
    "sidebar.tool_call" to "Werkzeugaufruf",
    "sidebar.rename_folder" to "Ordner umbenennen",
    "common.new" to "Neu",
    "conversation.branch" to "Konversationszweig",
    "conversation.pinned" to "Angeheftet",
    "conversation.pin" to "Anheften",
    "conversation.unpin" to "Lösen",
    "conversation.move_to_chat" to "In Chats verschieben",
    "conversation.move_to_folder" to "Nach %s verschieben",
    "dialog.rename_conversation" to "Konversation umbenennen",
    "dialog.conversation_system_prompt" to "Systemprompt der Konversation",
    "dialog.compress_history" to "Gesprächsverlauf komprimieren",
    "dialog.compress_history_description" to "Frühere Nachrichten zusammenfassen und aktuelle behalten. Der gesamte Verlauf wird als wiederherstellbarer Snapshot gespeichert.",
    "dialog.target_tokens" to "Ziel-Token",
    "dialog.keep_recent_messages" to "Letzte Nachrichten behalten (von insgesamt %d)",
    "dialog.additional_instructions" to "Zusätzliche Anweisungen (optional)",
    "dialog.compress" to "Komprimieren",
    "dialog.translate_message" to "Nachricht übersetzen",
    "dialog.target_language" to "Zielsprache",
    "stats.messages" to "Nachrichten",
    "stats.attachments" to "Anhänge",
    "stats.characters" to "Text- und Denkzeichen",
    "stats.created_at" to "Erstellt",
    "stats.updated_at" to "Aktualisiert",
    "file.add_attachments" to "Anhänge hinzufügen",
    "file.parent_directory" to "Übergeordnetes Verzeichnis",
    "file.selected" to "Ausgewählt",
    "file.add_count" to "Hinzufügen (%d)",
    "file.file_name" to "Dateiname",
    "file.export_conversation_markdown" to "Konversation als Markdown exportieren",
    "file.export_backup" to "RikkaHub-Sicherung exportieren",
    "agent.approval_request" to "Der Agent fordert diesen Vorgang an. Zulassen?",
    "agent.docker_network_warning" to "Wird in einem eingeschränkten Docker-Container mit temporärem Host-Netzwerk ausgeführt und kehrt dann in einen isolierten Offline-Container zurück.",
    "agent.docker_warning" to "Wird in einem eingeschränkten Docker-Container ausgeführt, der nur den ausgewählten Arbeitsbereich einbindet.",
    "agent.local_shell_warning" to "Die lokale Shell läuft mit den Rechten Ihres aktuellen Benutzers. Bestätigen Sie den Befehl und seine Auswirkungen.",
    "agent.confirm_impact" to "Bestätigen Sie den Befehl und seine Auswirkungen.",
    "agent.image_pull_warning" to "Lädt Inhalte aus einer Image-Registry in den lokalen Docker-Cache herunter.",
    "agent.skill_warning" to "Skill-Anweisungen können das spätere Agentenverhalten beeinflussen.",
    "agent.write_warning" to "Dateiänderungen sind auf das ausgewählte Arbeitsverzeichnis beschränkt.",
    "agent.remember_docker_shell" to "Docker-Befehle für diesen Arbeitsbereich in diesem Gespräch automatisch genehmigen",
    "agent.remember_docker_network" to "Docker-Netzwerkbefehle für diesen Arbeitsbereich in diesem Gespräch automatisch genehmigen",
    "agent.remember_image_pull" to "Diesen Image-Download in diesem Gespräch automatisch genehmigen",
    "agent.remember_operation" to "Diese Art von Vorgang in diesem Gespräch automatisch genehmigen",
    "agent.allow" to "Zulassen",
    "agent.deny" to "Ablehnen",
    "settings.navigation" to "Einstellungskategorien",
    "settings.section.general" to "Allgemein",
    "settings.section.messages" to "Nachrichten",
    "settings.section.interaction" to "Interaktion",
    "settings.section.data" to "Daten, Sicherungen und Websuche",
    "settings.section.assistants" to "Assistenten",
    "settings.section.providers" to "Modelle und Dienste",
    "composer.placeholder" to "Nachricht an RikkaHub",
    "model_picker.title" to "Modell auswählen",
    "model_picker.filter" to "Modelle filtern",
    "model_picker.reasoning" to "Denkintensität",
    "model_picker.default" to "Standard",
    "model_picker.low" to "Niedrig",
    "model_picker.medium" to "Mittel",
    "model_picker.high" to "Hoch",
    "model_picker.manage_providers" to "Anbieter verwalten",
    "model_picker.checking_balance" to "Guthaben wird geprüft",
    "model_picker.balance" to "Guthaben: %s",
    "model_picker.balance_failed" to "Guthaben nicht verfügbar",
    "mcp.manage" to "MCP-Dienste verwalten",
    "mcp.check" to "Verfügbarkeit prüfen",
    "mcp.title" to "MCP-Dienste",
    "mcp.services_for_assistant" to "%d Dienste für diesen Assistenten",
    "mcp.check_all" to "Alle prüfen",
    "mcp.open_settings" to "MCP-Einstellungen öffnen",
    "mcp.no_servers" to "Keine MCP-Dienste konfiguriert",
    "mcp.not_checked" to "Nicht geprüft",
    "mcp.checking" to "Wird geprüft",
    "mcp.tools_synced" to "%d Werkzeuge synchronisiert",
    "mcp.available_tools" to "Verfügbar · %d Werkzeuge",
    "mcp.current_assistant" to "Dieser Assistent",
    "mcp.enabled" to "Aktiviert",
    "mcp.available" to "Verfügbar",
    "mcp.unavailable" to "Nicht verfügbar",
    "mcp_settings.title" to "MCP-Server",
    "mcp_settings.description" to "Synchronisieren Sie entfernte Werkzeuge und aktivieren Sie dann die Server, die dieser Assistent benötigt",
    "mcp_settings.add_server" to "MCP-Server hinzufügen",
    "mcp_settings.unnamed_server" to "Unbenannter MCP-Server",
    "mcp_settings.delete_server" to "MCP-Server löschen",
    "mcp_settings.server_name" to "Servername",
    "mcp_settings.server_name_help" to "Nur Buchstaben und Ziffern; dient zur Erzeugung stabiler Werkzeugnamen",
    "mcp_settings.command" to "Befehl",
    "mcp_settings.arguments" to "Befehlsargumente",
    "mcp_settings.arguments_help" to "Ein Argument pro Zeile",
    "mcp_settings.environment" to "Umgebungsvariablen",
    "mcp_settings.environment_help" to "Ein SCHLÜSSEL=WERT-Paar pro Zeile",
    "mcp_settings.server_url" to "Server-URL",
    "mcp_settings.enable_server" to "Server aktivieren",
    "mcp_settings.enable_server_help" to "Wenn deaktiviert, werden seine Werkzeuge dem Modell nicht zur Verfügung gestellt",
    "mcp_settings.sync_failed" to "Synchronisierung der MCP-Werkzeuge fehlgeschlagen",
    "mcp_settings.sync_tools" to "Werkzeuge synchronisieren",
    "mcp_settings.collapse_tools" to "Werkzeuge einklappen",
    "mcp_settings.manage_tools" to "%d Werkzeuge verwalten (%e aktiviert)",
    "mcp_settings.tool" to "MCP-Werkzeug",
    "assistant.message_template" to "Nachrichtenvorlage",
    "assistant.template_variables" to "Variablen: {{ message }}, {{ role }}, {{ date }}, {{ time }}",
    "assistant.template_invalid" to "Eine gültige Pebble-Vorlage muss {{ message }} enthalten",
    "assistant.conversation_system_prompt" to "Systemprompt der Konversation",
    "assistant.conversation_system_prompt_help" to "Einzelnen Konversationen erlauben, den Systemprompt dieses Assistenten zu überschreiben",
    "assistant.conversation_lorebooks" to "Konversations-Lorebooks",
    "assistant.conversation_lorebooks_help" to "Einzelnen Konversationen erlauben, die Prompt-Injektionen dieses Assistenten zu aktivieren oder zu deaktivieren",
    "assistant.web_search" to "Websuche",
    "assistant.web_search_help" to "OpenAI-kompatible Websuche standardmäßig in neuen Konversationen aktivieren",
    "assistant.local_time_tool" to "Lokales Zeit-Werkzeug",
    "assistant.local_time_tool_help" to "Dem Modell erlauben, die lokale Zeit und Zeitzone dieses Geräts bei Bedarf auszulesen",
    "assistant.ask_user_tool" to "Benutzer fragen",
    "assistant.ask_user_tool_help" to "Dem Modell erlauben, bei Bedarf um Klärung oder Bestätigung zu bitten",
    "assistant.max_tool_rounds" to "Maximale Werkzeugaufruf-Runden pro Antwort",
    "assistant.max_tool_rounds_help" to "0 bedeutet unbegrenzt; Standard ist 8",
    "assistant.agent_workspace" to "Agent-Arbeitsbereich",
    "assistant.agent_workspace_help" to "Dem Modell erlauben, im ausgewählten Verzeichnis Dateien zu lesen/schreiben, Befehle auszuführen und aktivierte Skills zu laden",
    "assistant.workspace_directory" to "Arbeitsbereichsverzeichnis",
    "assistant.workspace_directory_help" to "Nur Agent-Dateiwerkzeuge können auf dieses Verzeichnis zugreifen; die lokale Shell erfordert weiterhin jedes Mal eine Bestätigung",
    "assistant.docker_container" to "Docker-Container",
    "assistant.local_shell" to "Lokale Shell",
    "assistant.docker_image" to "Docker-Image",
    "assistant.docker_image_help" to "Standardmäßig offline, ohne Privilegien und bindet nur den Arbeitsbereich ein; der erste Pull benötigt eine Genehmigung",
    "assistant.enabled_skills" to "Aktivierte Skills",
    "assistant.enabled_skills_help" to "Kommagetrennt; gespeichert in ~/.config/rikkahub/skills/<Name>/SKILL.md",
    "assistant.stream_output" to "Streaming-Ausgabe",
    "assistant.stream_output_help" to "Antwortinhalt bei Ankunft anzeigen, anstatt auf die vollständige Antwort zu warten",
    "assistant.memory" to "Speicher",
    "assistant.memory_help" to "Dem Modell erlauben, langfristige Informationen konversationsübergreifend aufzuzeichnen, zu aktualisieren und zu verwenden",
    "assistant.global_memory" to "Globaler gemeinsamer Speicher",
    "assistant.global_memory_help" to "Einen Speicher mit anderen Assistenten teilen, die globalen Speicher verwenden",
    "assistant.add_global_memory" to "Globalen Speicher hinzufügen",
    "assistant.delete_global_memory" to "Globalen Speicher löschen",
    "assistant.shared_memory_content" to "Gemeinsame Tatsache oder Präferenz",
    "assistant.memory_entries" to "Speichereinträge",
    "assistant.add_memory" to "Speicher hinzufügen",
    "assistant.delete_memory" to "Speicher löschen",
    "assistant.memory_content" to "Tatsache oder Präferenz",
    "assistant.temperature" to "Temperatur",
    "assistant.inherit_provider" to "Leer lassen, um die Anbietereinstellung zu übernehmen",
    "assistant.max_output_tokens" to "Maximale Ausgabe-Token",
    "assistant.context_messages" to "Kontextnachrichten",
    "assistant.keep_all_when_empty" to "Leer lassen, um alle zu behalten",
    "common.add" to "Hinzufügen",
    "role.system" to "System",
    "role.user" to "Benutzer",
    "role.assistant" to "Assistent",
    "assistant.preset_messages" to "Voreingestellte Nachrichten",
    "assistant.preset_messages_help" to "Beispielnachrichten zu jeder neuen Konversation hinzufügen",
    "assistant.message" to "Nachricht",
    "assistant.delete_preset_message" to "Voreingestellte Nachricht löschen",
    "assistant.quick_messages" to "Schnellnachrichten",
    "assistant.quick_messages_help" to "Wiederverwendbare Eingabeaufforderungen aus dem Chat-Editor einfügen",
    "assistant.title" to "Titel",
    "assistant.content" to "Inhalt",
    "assistant.delete_quick_message" to "Schnellnachricht löschen",
    "assistant.regex_transforms" to "Regex-Transformationen",
    "assistant.regex_transforms_help" to "Benutzereingabe, Assistentenausgabe oder angezeigten Text transformieren",
    "assistant.rule_name" to "Regelname",
    "assistant.delete_regex_rule" to "Regex-Regel löschen",
    "assistant.find_regex" to "Such-Regex",
    "assistant.replace_with" to "Ersetzen durch",
    "assistant.visual_only" to "Nur visuell",
    "assistant.prompt_injections" to "Prompt-Injektionen / Lorebooks",
    "assistant.prompt_injections_help" to "Kontext per Schlüsselwort abgleichen oder eine Injektion immer aktiv halten",
    "assistant.entry_name" to "Eintragsname",
    "assistant.delete_injection" to "Injektionseintrag löschen",
    "assistant.injection_content" to "Injektionsinhalt",
    "assistant.keywords" to "Schlüsselwörter (durch Kommas getrennt)",
    "assistant.keywords_help" to "Wenn leer, aktivieren Sie „Immer aktiv“",
    "assistant.priority" to "Priorität",
    "assistant.priority_help" to "Höhere Werte werden früher platziert",
    "assistant.scan_depth" to "Zu scannende Nachrichten",
    "assistant.scan_depth_help" to "Wird für den Schlüsselwortabgleich verwendet",
    "assistant.injection_depth" to "Injektionstiefe",
    "assistant.injection_depth_help" to "Vom Ende aus zählen",
    "assistant.injection_role" to "Injektionsrolle",
    "assistant.before_system" to "Vor Systemprompt",
    "assistant.after_system" to "Nach Systemprompt",
    "assistant.top_of_chat" to "Chat-Anfang",
    "assistant.bottom_of_chat" to "Chat-Ende",
    "assistant.at_depth" to "Auf Tiefe",
    "assistant.always_active" to "Immer aktiv",
    "assistant.regex_keywords" to "Regex-Schlüsselwörter",
    "assistant.case_sensitive" to "Groß-/Kleinschreibung beachten",
    "assistant.saved" to "Assistenteneinstellungen gespeichert",
    "assistant.save" to "Assistenten speichern",
    "provider.title_model" to "Titelmodell",
    "provider.title_model_help" to "Leer lassen, um das Chat-Modell zu verwenden",
    "provider.title_prompt" to "Titel-Prompt",
    "provider.title_prompt_help" to "Unterstützt die Platzhalter {locale} und {content}",
    "provider.token_usage" to "Token-Nutzung",
    "provider.token_usage_help" to "Eingabe- und Ausgabe-Token-Zählung von kompatiblen Streaming-APIs anfordern",
    "provider.use_provider_default" to "Leer lassen, um den Anbieterstandard zu verwenden",
    "provider.system_prompt" to "Systemprompt",
    "provider.balance_query" to "Guthabenabfrage",
    "provider.balance_query_help" to "Kontostand oder Kontingent über die Anbieter-API abfragen",
    "provider.balance_api_path" to "Guthaben-API-Pfad",
    "provider.balance_api_path_help" to "Relativen Pfad oder vollständige URL eingeben",
    "provider.balance_result_path" to "Ergebnis-JSON-Pfad",
    "provider.balance_result_path_help" to "Zum Beispiel: data.balance oder data.items[0].amount",
    "provider.checking_balance" to "Guthaben wird geprüft...",
    "provider.current_balance" to "Aktuelles Guthaben: %s",
    "provider.balance_failed" to "Guthabenabfrage fehlgeschlagen: %s",
    "provider.check_balance" to "Guthaben prüfen",
    "request_overrides.headers" to "Benutzerdefinierte Header",
    "request_overrides.headers_help" to "Zu Chat- und Modellanfragen hinzufügen",
    "request_overrides.add_header" to "Benutzerdefinierten Header hinzufügen",
    "request_overrides.header" to "Header",
    "request_overrides.value" to "Wert",
    "request_overrides.delete_header" to "Benutzerdefinierten Header löschen",
    "request_overrides.body" to "Benutzerdefinierter Anfragetext",
    "request_overrides.body_help" to "JSON in Top-Level-Felder der Anfrage einfügen",
    "request_overrides.add_body" to "Anfragetext hinzufügen",
    "request_overrides.key" to "Schlüssel",
    "request_overrides.json_value" to "JSON-Wert",
    "request_overrides.invalid_json" to "Gültiges JSON eingeben",
    "request_overrides.delete_body" to "Anfragetext löschen",
    "chat.restore_snapshot" to "Verlaufssnapshot %d wiederherstellen: %s",
    "chat.snapshot_messages" to "%d Nachrichten",
    "chat.delete_snapshot" to "Verlaufssnapshot löschen",
    "jumper.top" to "Zum Anfang",
    "jumper.previous" to "Vorherige Nachricht",
    "jumper.next" to "Nächste Nachricht",
    "jumper.bottom" to "Zum Ende",
    "tool.calling" to "Wird ausgeführt",
    "tool.completed" to "Abgeschlossen",
    "tool.input" to "Eingabe",
    "tool.output" to "Ausgabe",
    "tool.result" to "Werkzeugergebnis",
    "tool.answer_required" to "Ihre Antwort ist erforderlich",
    "tool.web_search" to "Web durchsuchen",
    "tool.current_time" to "Aktuelle Uhrzeit abrufen",
    "tool.memory" to "Speicher verwalten",
    "tool.list_files" to "Dateien auflisten",
    "tool.search_files" to "Dateien suchen",
    "tool.read_file" to "Datei lesen",
    "tool.write_file" to "Datei schreiben",
    "tool.edit_file" to "Datei bearbeiten",
    "tool.run_command" to "Befehl ausführen",
    "tool.use_skill" to "Skill verwenden",
    "model_picker.refresh_balance" to "Guthaben von %s aktualisieren",
    "model_picker.current_model" to "Aktuelles Modell",
    "model_capability.text" to "Text",
    "model_capability.vision" to "Bild",
    "model_capability.reasoning" to "Denken",
    "model_capability.tools" to "Werkzeuge",
    "attachment.remove" to "Anhang entfernen",
    "mcp.unnamed_service" to "Unbenannter MCP-Dienst",
    "language.system_default" to "Systemstandard",
    "language.chinese" to "Chinesisch",
    "user.you" to "Du",
    "message.user_avatar" to "Benutzeravatar",
    "common.unnamed" to "Unbenannt",
    "theme.sakura" to "Sakura",
    "theme.ocean" to "Ozean",
    "theme.forest" to "Wald",
    "theme.sunset" to "Sonnenuntergang",
    "theme.lavender" to "Lavendel",
    "theme.slate" to "Schiefer",
    "font.system" to "Systemstandard",
    "font.sans_serif" to "Serifenlos",
    "font.serif" to "Serif",
    "font.monospace" to "Monospace",
    "runtime.unknown_error" to "Unbekannter Fehler",
    "runtime.save_failed" to "Speichern fehlgeschlagen: %s",
    "runtime.title_empty" to "Das Titelmodell hat keinen Inhalt zurückgegeben",
    "runtime.title_failed" to "Titelgenerierung fehlgeschlagen",
    "runtime.suggestions_empty" to "Das Vorschlagsmodell hat keinen Inhalt zurückgegeben",
    "runtime.suggestions_failed" to "Generierung von Antwortvorschlägen fehlgeschlagen",
    "runtime.mcp_configuration_invalid" to "Die MCP-Konfiguration ist nicht mehr gültig. Wählen Sie die Server in den Assistenteneinstellungen erneut aus",
    "runtime.mcp_no_tools" to "Der MCP-Server %s hat keine verwendbaren Werkzeuge bereitgestellt",
    "runtime.mcp_sync_failed" to "Synchronisierung der MCP-Werkzeuge fehlgeschlagen: %s",
    "runtime.invalid_message_template" to "Ungültige Nachrichtenvorlage",
    "runtime.request_failed" to "Anfrage fehlgeschlagen",
    "runtime.not_enough_messages" to "Es sind nicht genügend Nachrichten zum Komprimieren vorhanden",
    "runtime.compression_empty" to "Das Komprimierungsmodell hat keine Zusammenfassung zurückgegeben",
    "runtime.compression_failed" to "Komprimierung der Konversation fehlgeschlagen",
    "runtime.translation_empty" to "Das Übersetzungsmodell hat keinen Inhalt zurückgegeben",
    "runtime.translation_failed" to "Übersetzung fehlgeschlagen",
    "runtime.export_failed" to "Export fehlgeschlagen: %s",
    "runtime.import_failed" to "Import fehlgeschlagen: %s",
    "runtime.tool_round_limit" to "Diese Antwort hat das Limit von %d Werkzeugaufruf-Runden erreicht. Senden Sie eine weitere Nachricht, um einen neuen Lauf zu starten.",
    "runtime.add_attachment_failed" to "Anhang konnte nicht hinzugefügt werden",
    "defaults.new_provider" to "Neuer Anbieter",
    "defaults.new_assistant" to "Neuer Assistent",
    "file.import_backup" to "RikkaHub-Sicherung importieren",
    "file.imported_backup" to "Sicherung aus %s importiert",
    "file.choose_attachments" to "Bilder, Audio, Text oder Dokumente hinzufügen",
    "mermaid.diagram" to "Diagramm",
    "mermaid.code" to "Code",
    "mermaid.save_image" to "Bild speichern",
    "mermaid.download" to "Herunterladen",
    "mermaid.fullscreen" to "Vollbild",
    "mermaid.exit_fullscreen" to "Vollbild beenden",
    "provider.connection_success" to "Verbunden · %d Modelle verfügbar"
)
