package me.rerere.rikkahub.desktop

internal val PortugueseBrazilDesktopTranslations = mapOf(
    "settings.language" to "Idioma",
    "settings.language_description" to "Escolha o idioma do aplicativo para desktop",
    "settings.title" to "Configurações",
    "settings.subtitle" to "Aparência, interação e modelos",
    "settings.back" to "Voltar",
    "settings.color_mode" to "Modo de cor",
    "settings.color_mode_description" to "Seguir o sistema, ou usar um tema claro ou escuro fixo",
    "settings.system" to "Sistema",
    "settings.light" to "Claro",
    "settings.dark" to "Escuro",
    "settings.theme_color" to "Cor do tema",
    "settings.theme_color_description" to "Escolha uma cor de destaque e tons correspondentes para a interface",
    "settings.font" to "Fonte da interface",
    "settings.font_description" to "%s; blocos de código permanecem monoespaçados",
    "settings.chat_font_size" to "Tamanho da fonte do chat",
    "sidebar.welcome" to "Bem-vindo de volta",
    "sidebar.new_chat" to "Novo chat",
    "sidebar.search_chats" to "Pesquisar chats",
    "sidebar.back_to_chats" to "Voltar aos chats",
    "sidebar.favorite_messages" to "Mensagens favoritas",
    "sidebar.search" to "Pesquisar",
    "sidebar.all_assistants" to "Todos os assistentes",
    "sidebar.all_tags" to "Todas as tags",
    "sidebar.chats" to "Chats",
    "chat.open_conversations" to "Abrir conversas",
    "chat.options" to "Opções da conversa",
    "chat.rename" to "Renomear",
    "chat.export_markdown" to "Exportar Markdown",
    "chat.generate_title" to "Gerar título",
    "chat.statistics" to "Estatísticas da conversa",
    "chat.generate_suggestions" to "Gerar sugestões de resposta",
    "chat.compress_history" to "Compactar histórico",
    "chat.set_system_prompt" to "Definir prompt do sistema",
    "chat.edit_system_prompt" to "Editar prompt do sistema",
    "chat.enable_lorebooks" to "Ativar livros de lore da conversa",
    "chat.disable_lorebooks" to "Desativar livros de lore da conversa",
    "chat.move_to_folder" to "Mover para pasta",
    "chat.uncategorized" to "Sem categoria",
    "chat.new_folder" to "Nova pasta",
    "chat.close" to "Fechar",
    "message.sources" to "Fontes",
    "message.source_number" to "Fonte %d",
    "message.input_tokens" to "Tokens de entrada",
    "message.output_tokens" to "Tokens de saída",
    "message.cached_tokens" to "Tokens em cache",
    "message.previous_version" to "Versão anterior",
    "message.next_version" to "Próxima versão",
    "message.copy" to "Copiar",
    "message.fork" to "Ramificar a partir daqui",
    "message.regenerate" to "Gerar novamente",
    "message.translate" to "Traduzir",
    "message.favorite" to "Favoritar",
    "message.unfavorite" to "Remover dos favoritos",
    "message.edit" to "Editar",
    "message.delete" to "Excluir",
    "empty_chat.greeting" to "Como posso ajudar?",
    "composer.collapse" to "Fechar compositor",
    "composer.expand" to "Expandir compositor",
    "composer.add_attachment" to "Adicionar anexo",
    "composer.enable_web_search" to "Ativar pesquisa na web",
    "composer.disable_web_search" to "Desativar pesquisa na web",
    "composer.quick_messages" to "Mensagens rápidas",
    "composer.manage_assistants" to "Gerenciar assistentes e tags",
    "composer.stop_generation" to "Parar geração",
    "composer.send" to "Enviar; mantenha pressionado para adicionar sem resposta",
    "settings.show_user_avatar" to "Mostrar avatar do usuário",
    "settings.show_user_avatar_description" to "Mostrar um avatar ao lado das mensagens do usuário",
    "settings.user_nickname" to "Apelido do usuário",
    "settings.user_nickname_description" to "Exibido ao lado das mensagens do usuário; padrão \"Você\" se vazio",
    "settings.user_nickname_placeholder" to "Você",
    "settings.show_model_icon" to "Mostrar ícone do modelo",
    "settings.show_model_icon_description" to "Mostrar o ícone do modelo ao lado das mensagens do assistente",
    "settings.show_model_name" to "Mostrar nome do modelo",
    "settings.show_model_name_description" to "Mostrar o nome do modelo acima das mensagens do assistente",
    "settings.assistant_bubble" to "Balão do assistente",
    "settings.assistant_bubble_description" to "Mostrar o texto do assistente em um balão preenchido",
    "settings.message_timestamp" to "Horário da mensagem",
    "settings.message_timestamp_description" to "Mostrar a hora de criação no cabeçalho de cada mensagem",
    "settings.reasoning" to "Conteúdo do raciocínio",
    "settings.reasoning_description" to "Mostrar o raciocínio retornado por modelos compatíveis",
    "settings.collapse_reasoning" to "Recolher raciocínio após a conclusão",
    "settings.collapse_reasoning_description" to "Expandir o raciocínio apenas enquanto a resposta é gerada",
    "settings.code_wrap" to "Quebrar linhas em blocos de código",
    "settings.code_wrap_description" to "Quebrar linhas longas de código em vez de rolar horizontalmente",
    "settings.chinese_typography" to "Tipografia chinesa",
    "settings.chinese_typography_description" to "Adicionar espaçamento entre texto chinês e latino, números ou símbolos",
    "settings.mermaid_rendering" to "Renderizar diagramas Mermaid",
    "settings.mermaid_rendering_description" to "Renderizar blocos de código Mermaid como diagramas interativos",
    "settings.mermaid_cli" to "Permitir Mermaid CLI",
    "settings.mermaid_cli_description" to "Permitir a execução local do Mermaid CLI para renderizar diagramas",
    "settings.mermaid_cli_path" to "Caminho do Mermaid CLI",
    "settings.mermaid_cli_path_description" to "Deixe vazio para detectar automaticamente PATH, npm global e locais do usuário",
    "settings.mermaid_system_browser" to "Usar navegador do sistema",
    "settings.mermaid_system_browser_description" to "Permitir que o Mermaid CLI use um navegador baseado em Chromium instalado",
    "settings.send_on_enter" to "Enviar com Enter",
    "settings.send_on_enter_description" to "Quando desligado, Ctrl+Enter envia e Enter adiciona uma nova linha",
    "settings.auto_scroll" to "Rolagem automática",
    "settings.auto_scroll_description" to "Acompanhar novo conteúdo de raciocínio e resposta durante a geração",
    "settings.smooth_scroll" to "Rolagem suave",
    "settings.smooth_scroll_description" to "Animar a rolagem da roda do mouse na conversa",
    "settings.message_navigation" to "Navegação de mensagens",
    "settings.message_navigation_description" to "Mostrar botões para topo, anterior, próximo e final após rolar",
    "settings.message_navigation_left" to "Navegação de mensagens à esquerda",
    "settings.message_navigation_left_description" to "Por padrão, exibida no lado direito da área de mensagens",
    "settings.export_backup" to "Exportar backup",
    "settings.export_backup_description" to "Salvar provedores, assistentes, preferências e chats como JSON",
    "settings.export" to "Exportar",
    "settings.import_backup" to "Importar backup",
    "settings.import_backup_description" to "Substituir os dados atuais do desktop por um backup do RikkaHub",
    "settings.import" to "Importar",
    "settings.reset_data" to "Redefinir todos os dados",
    "settings.reset_data_description" to "Excluir provedores locais, assistentes, preferências e chats. Isso não pode ser desfeito.",
    "settings.reset" to "Redefinir",
    "settings.web_search" to "Serviço de pesquisa na web",
    "settings.web_search_description" to "Usar um serviço de pesquisa externo quando configurado; caso contrário, usar a pesquisa nativa do provedor do modelo",
    "settings.searxng_url" to "URL do SearXNG",
    "settings.api_key" to "Chave da API",
    "settings.search_result_count" to "%d resultados por pesquisa",
    "settings.test_search" to "Testar pesquisa",
    "settings.search_test_success" to "A conexão de pesquisa na web está funcionando",
    "settings.search_test_failed" to "Falha no teste de pesquisa",
    "settings.add_assistant" to "Adicionar assistente",
    "settings.assistant_name" to "Nome do assistente",
    "settings.copy_assistant" to "Copiar assistente",
    "settings.delete_assistant" to "Excluir assistente",
    "settings.tags" to "Tags (separadas por vírgulas)",
    "settings.model_inherit" to "Modelo (deixe em branco para usar o padrão do provedor)",
    "settings.select_model" to "Escolher modelo",
    "settings.system_prompt_inherit" to "Prompt do sistema (deixe em branco para usar o padrão do provedor)",
    "settings.apply_preset" to "Aplicar predefinição",
    "settings.add_provider" to "Adicionar provedor",
    "settings.provider_name" to "Nome do provedor",
    "settings.delete_provider" to "Excluir provedor",
    "settings.base_url" to "URL base",
    "settings.hide_api_key" to "Ocultar chave da API",
    "settings.show_api_key" to "Mostrar chave da API",
    "settings.model" to "Modelo",
    "settings.select_discovered_model" to "Selecionar modelo descoberto",
    "settings.test_and_fetch_models" to "Testar e buscar modelos",
    "settings.provider_saved" to "Configurações do provedor salvas",
    "settings.save_provider" to "Salvar provedor",
    "settings.back_to_chat" to "Voltar ao chat",
    "settings.unsaved_changes_title" to "Salvar alterações?",
    "settings.unsaved_changes_description" to "As configurações foram alteradas. Salvar antes de sair?",
    "settings.discard_changes" to "Não salvar",
    "settings.reset_confirmation_title" to "Redefinir todos os dados?",
    "settings.reset_confirmation_description" to "Isso exclui permanentemente os segredos do provedor de desktop, assistentes, configurações e todas as conversas.",
    "settings.confirm_reset" to "Redefinir dados",
    "common.cancel" to "Cancelar",
    "common.save" to "Salvar",
    "common.submit" to "Enviar",
    "common.expand" to "Expandir ",
    "common.collapse" to "Recolher ",
    "message.thinking" to "Pensando...",
    "message.translation" to "Tradução",
    "attachment.audio" to "Áudio",
    "timeline.execution" to "Execução",
    "timeline.expand_execution" to "Expandir execução",
    "timeline.collapse_execution" to "Recolher execução",
    "timeline.expand_steps" to "Expandir %d etapas",
    "timeline.reasoning" to "Raciocínio",
    "timeline.reasoning_duration" to "Raciocinou por %s segundos",
    "timeline.today" to "Hoje",
    "timeline.yesterday" to "Ontem",
    "timeline.day_before_yesterday" to "Anteontem",
    "timeline.days_ago" to "%d dias atrás",
    "sidebar.recent" to "Recentes",
    "sidebar.most_active" to "Mais usados",
    "sidebar.sort_recent" to "Ordenar por atividade recente",
    "sidebar.sort_most_active" to "Ordenar por frequência de uso",
    "sidebar.tool_call" to "Chamada de ferramenta",
    "sidebar.rename_folder" to "Renomear pasta",
    "common.new" to "Novo",
    "conversation.branch" to "Ramificação da conversa",
    "conversation.pinned" to "Fixado",
    "conversation.pin" to "Fixar",
    "conversation.unpin" to "Desafixar",
    "conversation.move_to_chat" to "Mover para chats",
    "conversation.move_to_folder" to "Mover para %s",
    "dialog.rename_conversation" to "Renomear conversa",
    "dialog.conversation_system_prompt" to "Prompt do sistema da conversa",
    "dialog.compress_history" to "Compactar histórico da conversa",
    "dialog.compress_history_description" to "Resumir mensagens anteriores e manter as recentes. O histórico completo é salvo como um snapshot restaurável.",
    "dialog.target_tokens" to "Tokens de destino",
    "dialog.keep_recent_messages" to "Manter mensagens recentes (de %d no total)",
    "dialog.additional_instructions" to "Instruções adicionais (opcional)",
    "dialog.compress" to "Compactar",
    "dialog.translate_message" to "Traduzir mensagem",
    "dialog.target_language" to "Idioma de destino",
    "stats.messages" to "Mensagens",
    "stats.attachments" to "Anexos",
    "stats.characters" to "Caracteres de texto e raciocínio",
    "stats.created_at" to "Criado",
    "stats.updated_at" to "Atualizado",
    "file.add_attachments" to "Adicionar anexos",
    "file.parent_directory" to "Diretório pai",
    "file.selected" to "Selecionado",
    "file.add_count" to "Adicionar (%d)",
    "file.file_name" to "Nome do arquivo",
    "file.export_conversation_markdown" to "Exportar conversa como Markdown",
    "file.export_backup" to "Exportar backup do RikkaHub",
    "agent.approval_request" to "O agente solicita esta operação. Permitir?",
    "agent.docker_network_warning" to "Executa em um contêiner Docker restrito com rede temporária do host e depois retorna a um contêiner isolado offline.",
    "agent.docker_warning" to "Executa em um contêiner Docker restrito que monta apenas o espaço de trabalho selecionado.",
    "agent.local_shell_warning" to "O shell local é executado com as permissões do seu usuário atual. Confirme o comando e o impacto.",
    "agent.confirm_impact" to "Confirme o comando e seu impacto.",
    "agent.image_pull_warning" to "Baixa conteúdo de um registro de imagem para o cache local do Docker.",
    "agent.skill_warning" to "As instruções de habilidade podem afetar o comportamento posterior do agente.",
    "agent.write_warning" to "As alterações de arquivos são limitadas ao diretório do espaço de trabalho selecionado.",
    "agent.remember_docker_shell" to "Aprovar automaticamente comandos Docker para este espaço de trabalho nesta conversa",
    "agent.remember_docker_network" to "Aprovar automaticamente comandos de rede Docker para este espaço de trabalho nesta conversa",
    "agent.remember_image_pull" to "Aprovar automaticamente este download de imagem nesta conversa",
    "agent.remember_operation" to "Aprovar automaticamente este tipo de operação nesta conversa",
    "agent.allow" to "Permitir",
    "agent.deny" to "Negar",
    "settings.navigation" to "Categorias de configurações",
    "settings.section.general" to "Geral",
    "settings.section.messages" to "Mensagens",
    "settings.section.interaction" to "Interação",
    "settings.section.data" to "Dados, backups e pesquisa na web",
    "settings.section.assistants" to "Assistentes",
    "settings.section.providers" to "Modelos e serviços",
    "composer.placeholder" to "Enviar mensagem para RikkaHub",
    "model_picker.title" to "Escolher modelo",
    "model_picker.filter" to "Filtrar modelos",
    "model_picker.reasoning" to "Nível de raciocínio",
    "model_picker.default" to "Padrão",
    "model_picker.low" to "Baixo",
    "model_picker.medium" to "Médio",
    "model_picker.high" to "Alto",
    "model_picker.manage_providers" to "Gerenciar provedores",
    "model_picker.checking_balance" to "Consultando saldo",
    "model_picker.balance" to "Saldo: %s",
    "model_picker.balance_failed" to "Saldo indisponível",
    "mcp.manage" to "Gerenciar serviços MCP",
    "mcp.check" to "Verificar disponibilidade",
    "mcp.title" to "Serviços MCP",
    "mcp.services_for_assistant" to "%d serviços para este assistente",
    "mcp.check_all" to "Verificar todos",
    "mcp.open_settings" to "Abrir configurações MCP",
    "mcp.no_servers" to "Nenhum serviço MCP configurado",
    "mcp.not_checked" to "Não verificado",
    "mcp.checking" to "Verificando",
    "mcp.tools_synced" to "%d ferramentas sincronizadas",
    "mcp.available_tools" to "Disponível · %d ferramentas",
    "mcp.current_assistant" to "Este assistente",
    "mcp.enabled" to "Ativado",
    "mcp.available" to "Disponível",
    "mcp.unavailable" to "Indisponível",
    "mcp_settings.title" to "Servidores MCP",
    "mcp_settings.description" to "Sincronize ferramentas remotas e depois habilite os servidores que este assistente precisa",
    "mcp_settings.add_server" to "Adicionar servidor MCP",
    "mcp_settings.unnamed_server" to "Servidor MCP sem nome",
    "mcp_settings.delete_server" to "Excluir servidor MCP",
    "mcp_settings.server_name" to "Nome do servidor",
    "mcp_settings.server_name_help" to "Apenas letras e números; usado para criar nomes de ferramentas estáveis",
    "mcp_settings.command" to "Comando",
    "mcp_settings.arguments" to "Argumentos do comando",
    "mcp_settings.arguments_help" to "Um argumento por linha",
    "mcp_settings.environment" to "Variáveis de ambiente",
    "mcp_settings.environment_help" to "Um par CHAVE=VALOR por linha",
    "mcp_settings.server_url" to "URL do servidor",
    "mcp_settings.enable_server" to "Ativar servidor",
    "mcp_settings.enable_server_help" to "Quando desligado, suas ferramentas não são expostas ao modelo",
    "mcp_settings.sync_failed" to "Falha ao sincronizar ferramentas MCP",
    "mcp_settings.sync_timeout" to "A sincronização das ferramentas MCP expirou após 10 segundos",
    "mcp_settings.sync_tools" to "Sincronizar ferramentas",
    "mcp_settings.collapse_tools" to "Recolher ferramentas",
    "mcp_settings.manage_tools" to "Gerenciar %d ferramentas (%e ativadas)",
    "mcp_settings.tool" to "Ferramenta MCP",
    "assistant.message_template" to "Modelo de mensagem",
    "assistant.template_variables" to "Variáveis: {{ message }}, {{ role }}, {{ date }}, {{ time }}",
    "assistant.template_invalid" to "Um modelo Pebble válido deve incluir {{ message }}",
    "assistant.conversation_system_prompt" to "Prompt do sistema da conversa",
    "assistant.conversation_system_prompt_help" to "Permitir que conversas individuais substituam o prompt do sistema deste assistente",
    "assistant.conversation_lorebooks" to "Livros de lore da conversa",
    "assistant.conversation_lorebooks_help" to "Permitir que conversas individuais ativem ou desativem as injeções de prompt deste assistente",
    "assistant.web_search" to "Pesquisa na web",
    "assistant.web_search_help" to "Ativar a pesquisa na web compatível com OpenAI por padrão em novas conversas",
    "assistant.local_time_tool" to "Ferramenta de hora local",
    "assistant.local_time_tool_help" to "Permitir que o modelo leia a hora local e o fuso horário deste dispositivo quando necessário",
    "assistant.ask_user_tool" to "Perguntar ao usuário",
    "assistant.ask_user_tool_help" to "Permitir que o modelo solicite esclarecimentos ou confirmação quando necessário",
    "assistant.max_tool_rounds" to "Máximo de rodadas de chamadas de ferramentas por resposta",
    "assistant.max_tool_rounds_help" to "0 significa ilimitado; o padrão é 8",
    "assistant.agent_workspace" to "Espaço de trabalho do agente",
    "assistant.agent_workspace_help" to "Permitir que o modelo leia e escreva arquivos, execute comandos e carregue habilidades habilitadas no diretório selecionado",
    "assistant.workspace_directory" to "Diretório do espaço de trabalho",
    "assistant.workspace_directory_help" to "Apenas as ferramentas de arquivo do agente podem acessar este diretório; o shell local ainda requer confirmação a cada vez",
    "assistant.docker_container" to "Contêiner Docker",
    "assistant.local_shell" to "Shell local",
    "assistant.docker_image" to "Imagem Docker",
    "assistant.docker_image_help" to "Offline, sem privilégios e monta apenas o espaço de trabalho por padrão; o primeiro pull precisa de aprovação",
    "assistant.enabled_skills" to "Habilidades ativadas",
    "assistant.enabled_skills_help" to "Separadas por vírgulas; armazenadas em ~/.config/rikkahub/skills/<nome>/SKILL.md",
    "assistant.stream_output" to "Saída em streaming",
    "assistant.stream_output_help" to "Mostrar o conteúdo da resposta à medida que chega, em vez de esperar pela resposta completa",
    "assistant.memory" to "Memória",
    "assistant.memory_help" to "Permitir que o modelo registre, atualize e use informações de longo prazo entre conversas",
    "assistant.global_memory" to "Memória global compartilhada",
    "assistant.global_memory_help" to "Compartilhar um armazenamento de memória com outros assistentes que usam memória global",
    "assistant.add_global_memory" to "Adicionar memória global",
    "assistant.delete_global_memory" to "Excluir memória global",
    "assistant.shared_memory_content" to "Fato ou preferência compartilhada",
    "assistant.memory_entries" to "Entradas de memória",
    "assistant.add_memory" to "Adicionar memória",
    "assistant.delete_memory" to "Excluir memória",
    "assistant.memory_content" to "Fato ou preferência",
    "assistant.temperature" to "Temperatura",
    "assistant.inherit_provider" to "Deixe em branco para herdar a configuração do provedor",
    "assistant.max_output_tokens" to "Máximo de tokens de saída",
    "assistant.context_messages" to "Mensagens de contexto",
    "assistant.keep_all_when_empty" to "Deixe em branco para manter todas",
    "common.add" to "Adicionar",
    "role.system" to "Sistema",
    "role.user" to "Usuário",
    "role.assistant" to "Assistente",
    "assistant.preset_messages" to "Mensagens predefinidas",
    "assistant.preset_messages_help" to "Adicionar mensagens de exemplo a cada nova conversa",
    "assistant.message" to "Mensagem",
    "assistant.delete_preset_message" to "Excluir mensagem predefinida",
    "assistant.quick_messages" to "Mensagens rápidas",
    "assistant.quick_messages_help" to "Inserir prompts reutilizáveis do compositor de chat",
    "assistant.title" to "Título",
    "assistant.content" to "Conteúdo",
    "assistant.delete_quick_message" to "Excluir mensagem rápida",
    "assistant.regex_transforms" to "Transformações regex",
    "assistant.regex_transforms_help" to "Transformar entrada do usuário, saída do assistente ou texto exibido",
    "assistant.rule_name" to "Nome da regra",
    "assistant.delete_regex_rule" to "Excluir regra regex",
    "assistant.find_regex" to "Regex de busca",
    "assistant.replace_with" to "Substituir por",
    "assistant.visual_only" to "Apenas visual",
    "assistant.prompt_injections" to "Injeções de prompt / livros de lore",
    "assistant.prompt_injections_help" to "Corresponder o contexto por palavra-chave ou manter uma injeção sempre ativa",
    "assistant.entry_name" to "Nome da entrada",
    "assistant.delete_injection" to "Excluir entrada de injeção",
    "assistant.injection_content" to "Conteúdo da injeção",
    "assistant.keywords" to "Palavras-chave (separadas por vírgulas)",
    "assistant.keywords_help" to "Se vazio, ative \"sempre ativo\"",
    "assistant.priority" to "Prioridade",
    "assistant.priority_help" to "Valores mais altos são colocados antes",
    "assistant.scan_depth" to "Mensagens a escanear",
    "assistant.scan_depth_help" to "Usado para correspondência de palavras-chave",
    "assistant.injection_depth" to "Profundidade da injeção",
    "assistant.injection_depth_help" to "Contar a partir do final",
    "assistant.injection_role" to "Papel da injeção",
    "assistant.before_system" to "Antes do prompt do sistema",
    "assistant.after_system" to "Após o prompt do sistema",
    "assistant.top_of_chat" to "Topo do chat",
    "assistant.bottom_of_chat" to "Final do chat",
    "assistant.at_depth" to "Na profundidade",
    "assistant.always_active" to "Sempre ativo",
    "assistant.regex_keywords" to "Palavras-chave regex",
    "assistant.case_sensitive" to "Diferenciar maiúsculas e minúsculas",
    "assistant.saved" to "Configurações do assistente salvas",
    "assistant.save" to "Salvar assistente",
    "provider.title_model" to "Modelo de título",
    "provider.title_model_help" to "Deixe em branco para usar o modelo de chat",
    "provider.suggestion_model" to "Modelo de sugestões de resposta",
    "provider.suggestion_model_help" to "Deixe em branco para usar o modelo de chat; o raciocínio é desativado para sugestões",
    "provider.title_prompt" to "Prompt de título",
    "provider.title_prompt_help" to "Suporta os marcadores {locale} e {content}",
    "provider.token_usage" to "Uso de tokens",
    "provider.token_usage_help" to "Solicitar contagens de tokens de entrada e saída de APIs de streaming compatíveis",
    "provider.use_provider_default" to "Deixe em branco para usar o padrão do provedor",
    "provider.system_prompt" to "Prompt do sistema",
    "provider.balance_query" to "Consulta de saldo",
    "provider.balance_query_help" to "Consultar saldo ou cota da conta através da API do provedor",
    "provider.balance_api_path" to "Caminho da API de saldo",
    "provider.balance_api_path_help" to "Insira um caminho relativo ou uma URL completa",
    "provider.balance_result_path" to "Caminho JSON do resultado",
    "provider.balance_result_path_help" to "Por exemplo: data.balance ou data.items[0].amount",
    "provider.checking_balance" to "Consultando saldo...",
    "provider.current_balance" to "Saldo atual: %s",
    "provider.balance_failed" to "Falha na consulta de saldo: %s",
    "provider.check_balance" to "Consultar saldo",
    "request_overrides.headers" to "Cabeçalhos personalizados",
    "request_overrides.headers_help" to "Adicionar às requisições de chat e modelo",
    "request_overrides.add_header" to "Adicionar cabeçalho personalizado",
    "request_overrides.header" to "Cabeçalho",
    "request_overrides.value" to "Valor",
    "request_overrides.delete_header" to "Excluir cabeçalho personalizado",
    "request_overrides.body" to "Corpo de solicitação personalizado",
    "request_overrides.body_help" to "Mesclar JSON nos campos de nível superior da requisição",
    "request_overrides.add_body" to "Adicionar corpo de solicitação",
    "request_overrides.key" to "Chave",
    "request_overrides.json_value" to "Valor JSON",
    "request_overrides.invalid_json" to "Insira JSON válido",
    "request_overrides.delete_body" to "Excluir corpo de solicitação",
    "chat.restore_snapshot" to "Restaurar snapshot de histórico %d: %s",
    "chat.snapshot_messages" to "%d mensagens",
    "chat.delete_snapshot" to "Excluir snapshot de histórico",
    "jumper.top" to "Ir para o início",
    "jumper.previous" to "Mensagem anterior",
    "jumper.next" to "Próxima mensagem",
    "jumper.bottom" to "Ir para o fim",
    "tool.calling" to "Em execução",
    "tool.completed" to "Concluído",
    "tool.input" to "Entrada",
    "tool.output" to "Saída",
    "tool.result" to "Resultado da ferramenta",
    "tool.answer_required" to "Sua resposta é necessária",
    "tool.web_search" to "Pesquisar na web",
    "tool.current_time" to "Obter hora atual",
    "tool.memory" to "Gerenciar memória",
    "tool.list_files" to "Listar arquivos",
    "tool.search_files" to "Pesquisar arquivos",
    "tool.read_file" to "Ler arquivo",
    "tool.write_file" to "Escrever arquivo",
    "tool.edit_file" to "Editar arquivo",
    "tool.run_command" to "Executar comando",
    "tool.use_skill" to "Usar habilidade",
    "model_picker.refresh_balance" to "Atualizar saldo de %s",
    "model_picker.current_model" to "Modelo atual",
    "model_capability.text" to "Texto",
    "model_capability.vision" to "Visão",
    "model_capability.reasoning" to "Raciocínio",
    "model_capability.tools" to "Ferramentas",
    "attachment.remove" to "Remover anexo",
    "mcp.unnamed_service" to "Serviço MCP sem nome",
    "language.system_default" to "Padrão do sistema",
    "language.chinese" to "Chinês",
    "user.you" to "Você",
    "message.user_avatar" to "Avatar do usuário",
    "common.unnamed" to "Sem nome",
    "theme.sakura" to "Sakura",
    "theme.ocean" to "Oceano",
    "theme.forest" to "Floresta",
    "theme.sunset" to "Pôr do sol",
    "theme.lavender" to "Lavanda",
    "theme.slate" to "Ardósia",
    "font.system" to "Padrão do sistema",
    "font.sans_serif" to "Sem serifa",
    "font.serif" to "Com serifa",
    "font.monospace" to "Monoespaçada",
    "runtime.unknown_error" to "Erro desconhecido",
    "runtime.save_failed" to "Falha ao salvar: %s",
    "runtime.title_empty" to "O modelo de título não retornou conteúdo",
    "runtime.title_failed" to "Falha ao gerar título",
    "runtime.suggestions_empty" to "O modelo de sugestões não retornou conteúdo",
    "runtime.suggestions_failed" to "Falha ao gerar sugestões de resposta",
    "runtime.mcp_configuration_invalid" to "A configuração MCP não é mais válida. Selecione os servidores novamente nas configurações do assistente",
    "runtime.mcp_no_tools" to "O servidor MCP %s não forneceu ferramentas utilizáveis",
    "runtime.mcp_sync_failed" to "Falha ao sincronizar ferramentas MCP: %s",
    "runtime.invalid_message_template" to "Modelo de mensagem inválido",
    "runtime.request_failed" to "Falha na solicitação",
    "runtime.not_enough_messages" to "Não há mensagens suficientes para compactar",
    "runtime.compression_empty" to "O modelo de compactação não retornou um resumo",
    "runtime.compression_failed" to "Falha ao compactar a conversa",
    "runtime.translation_empty" to "O modelo de tradução não retornou conteúdo",
    "runtime.translation_failed" to "Falha na tradução",
    "runtime.export_failed" to "Falha na exportação: %s",
    "runtime.import_failed" to "Falha na importação: %s",
    "runtime.tool_round_limit" to "Esta resposta atingiu o limite de %d rodadas de chamadas de ferramentas. Envie outra mensagem para iniciar uma nova execução.",
    "runtime.add_attachment_failed" to "Não foi possível adicionar o anexo",
    "defaults.new_provider" to "Novo provedor",
    "defaults.new_assistant" to "Novo assistente",
    "file.import_backup" to "Importar backup do RikkaHub",
    "file.imported_backup" to "Backup importado de %s",
    "file.choose_attachments" to "Adicionar imagens, áudio, texto ou documentos",
    "mermaid.diagram" to "Diagrama",
    "mermaid.code" to "Código",
    "mermaid.save_image" to "Salvar imagem",
    "mermaid.download" to "Baixar",
    "mermaid.fullscreen" to "Tela cheia",
    "mermaid.exit_fullscreen" to "Sair da tela cheia",
    "provider.connection_success" to "Conectado · %d modelos disponíveis"
)
