package me.rerere.rikkahub.desktop

internal val RussianDesktopTranslations = mapOf(
    "settings.language" to "Язык",
    "settings.language_description" to "Выберите язык интерфейса настольного приложения",
    "settings.title" to "Настройки",
    "settings.subtitle" to "Оформление, взаимодействие и модели",
    "settings.back" to "Назад",
    "settings.color_mode" to "Режим цвета",
    "settings.color_mode_description" to "Следовать системе или использовать фиксированную светлую/тёмную тему",
    "settings.system" to "Системный",
    "settings.light" to "Светлый",
    "settings.dark" to "Тёмный",
    "settings.theme_color" to "Цвет темы",
    "settings.theme_color_description" to "Выберите акцентный цвет и тона для интерфейса",
    "settings.font" to "Шрифт интерфейса",
    "settings.font_description" to "%s; блоки кода остаются моноширинными",
    "settings.chat_font_size" to "Размер шрифта чата",
    "settings.composer_transparency" to "Прозрачность поля ввода",
    "settings.composer_blur" to "Сила размытия поля ввода",
    "sidebar.welcome" to "С возвращением",
    "sidebar.new_chat" to "Новый чат",
    "sidebar.search_chats" to "Поиск чатов",
    "sidebar.back_to_chats" to "Назад к чатам",
    "sidebar.favorite_messages" to "Избранные сообщения",
    "sidebar.search" to "Поиск",
    "sidebar.all_assistants" to "Все ассистенты",
    "sidebar.all_tags" to "Все теги",
    "sidebar.chats" to "Чаты",
    "chat.open_conversations" to "Открыть беседы",
    "chat.options" to "Параметры беседы",
    "chat.rename" to "Переименовать",
    "chat.export_markdown" to "Экспортировать Markdown",
    "chat.generate_title" to "Создать заголовок",
    "chat.statistics" to "Статистика беседы",
    "chat.generate_suggestions" to "Создать предложения ответа",
    "chat.compress_history" to "Сжать историю",
    "chat.set_system_prompt" to "Задать системный промпт",
    "chat.edit_system_prompt" to "Изменить системный промпт",
    "chat.enable_lorebooks" to "Включить лорбуки беседы",
    "chat.disable_lorebooks" to "Выключить лорбуки беседы",
    "chat.move_to_folder" to "Переместить в папку",
    "chat.uncategorized" to "Без категории",
    "chat.new_folder" to "Новая папка",
    "chat.close" to "Закрыть",
    "message.sources" to "Источники",
    "message.source_number" to "Источник %d",
    "message.input_tokens" to "Входные токены",
    "message.output_tokens" to "Выходные токены",
    "message.cached_tokens" to "Кэшированные токены",
    "message.previous_version" to "Предыдущая версия",
    "message.next_version" to "Следующая версия",
    "message.copy" to "Копировать",
    "message.fork" to "Ответвить отсюда",
    "message.regenerate" to "Сгенерировать снова",
    "message.translate" to "Перевести",
    "message.favorite" to "В избранное",
    "message.unfavorite" to "Убрать из избранного",
    "message.edit" to "Изменить",
    "message.delete" to "Удалить",
    "empty_chat.greeting" to "Чем я могу помочь?",
    "composer.collapse" to "Свернуть редактор",
    "composer.expand" to "Развернуть редактор",
    "composer.add_attachment" to "Добавить вложение",
    "composer.enable_web_search" to "Включить веб-поиск",
    "composer.disable_web_search" to "Выключить веб-поиск",
    "composer.quick_messages" to "Быстрые сообщения",
    "composer.manage_assistants" to "Управление ассистентами и тегами",
    "composer.stop_generation" to "Остановить генерацию",
    "composer.send" to "Отправить; удерживайте, чтобы добавить без ответа",
    "settings.show_user_avatar" to "Показывать аватар пользователя",
    "settings.show_user_avatar_description" to "Показывать аватар рядом с сообщениями пользователя",
    "settings.user_nickname" to "Псевдоним пользователя",
    "settings.user_nickname_description" to "Показывается рядом с сообщениями пользователя; если пусто — «Вы»",
    "settings.user_nickname_placeholder" to "Вы",
    "settings.show_model_icon" to "Показывать значок модели",
    "settings.show_model_icon_description" to "Показывать значок модели рядом с сообщениями ассистента",
    "settings.show_model_name" to "Показывать имя модели",
    "settings.show_model_name_description" to "Показывать имя модели над сообщениями ассистента",
    "settings.assistant_bubble" to "Пузырь ассистента",
    "settings.assistant_bubble_description" to "Показывать текст ассистента в заполненном пузыре",
    "settings.message_timestamp" to "Время сообщения",
    "settings.message_timestamp_description" to "Показывать время создания в заголовке каждого сообщения",
    "settings.reasoning" to "Содержание рассуждений",
    "settings.reasoning_description" to "Показывать рассуждения, возвращённые совместимыми моделями",
    "settings.collapse_reasoning" to "Сворачивать рассуждения после завершения",
    "settings.collapse_reasoning_description" to "Разворачивать рассуждения только во время генерации ответа",
    "settings.code_wrap" to "Переносить строки кода",
    "settings.code_wrap_description" to "Переносить длинные строки кода вместо горизонтальной прокрутки",
    "settings.chinese_typography" to "Китайская типографика",
    "settings.chinese_typography_description" to "Добавлять пробелы между китайским и латинским текстом, числами или символами",
    "settings.mermaid_rendering" to "Рендерить диаграммы Mermaid",
    "settings.mermaid_rendering_description" to "Рендерить блоки кода Mermaid как интерактивные диаграммы",
    "settings.mermaid_cli" to "Разрешить Mermaid CLI",
    "settings.mermaid_cli_description" to "Разрешить локальный запуск Mermaid CLI для рендеринга диаграмм",
    "settings.mermaid_cli_path" to "Путь к Mermaid CLI",
    "settings.mermaid_cli_path_description" to "Оставьте пустым для автоматического поиска в PATH, глобальном npm и локальных каталогах пользователя",
    "settings.mermaid_system_browser" to "Использовать системный браузер",
    "settings.mermaid_system_browser_description" to "Разрешить Mermaid CLI использовать установленный браузер на базе Chromium",
    "settings.send_on_enter" to "Отправлять по Enter",
    "settings.send_on_enter_description" to "Когда выключено: Ctrl+Enter отправляет, Enter — новая строка",
    "settings.auto_scroll" to "Автопрокрутка",
    "settings.auto_scroll_description" to "Следовать за новым содержанием рассуждений и ответом при генерации",
    "settings.smooth_scroll" to "Плавная прокрутка",
    "settings.smooth_scroll_description" to "Анимировать прокрутку колесом мыши в окне чата",
    "settings.message_navigation" to "Навигация по сообщениям",
    "settings.message_navigation_description" to "Показывать кнопки вверх, предыдущее, следующее и вниз после прокрутки",
    "settings.message_navigation_left" to "Навигация по сообщениям слева",
    "settings.message_navigation_left_description" to "По умолчанию отображается справа от области сообщений",
    "settings.export_backup" to "Экспорт резервной копии",
    "settings.export_backup_description" to "Сохранить провайдеров, ассистентов, настройки и чаты как JSON",
    "settings.export" to "Экспорт",
    "settings.import_backup" to "Импорт резервной копии",
    "settings.import_backup_description" to "Заменить текущие данные рабочего стола резервной копией RikkaHub",
    "settings.import" to "Импорт",
    "settings.reset_data" to "Сбросить все данные",
    "settings.reset_data_description" to "Удалить локальных провайдеров, ассистентов, настройки и чаты. Это действие необратимо.",
    "settings.reset" to "Сброс",
    "settings.web_search" to "Сервис веб-поиска",
    "settings.web_search_description" to "Использовать внешний поисковый сервис, если настроен; иначе — встроенный поиск провайдера модели",
    "settings.searxng_url" to "URL SearXNG",
    "settings.api_key" to "Ключ API",
    "settings.search_result_count" to "%d результатов на поиск",
    "settings.test_search" to "Проверить поиск",
    "settings.search_test_success" to "Подключение веб-поиска работает",
    "settings.search_test_failed" to "Ошибка проверки поиска",
    "settings.add_assistant" to "Добавить ассистента",
    "settings.assistant_name" to "Имя ассистента",
    "settings.copy_assistant" to "Копировать ассистента",
    "settings.delete_assistant" to "Удалить ассистента",
    "settings.tags" to "Теги (через запятую)",
    "settings.model_inherit" to "Модель (оставьте пустым для значения провайдера)",
    "settings.select_model" to "Выбрать модель",
    "settings.system_prompt_inherit" to "Системный промпт (оставьте пустым для значения провайдера)",
    "settings.apply_preset" to "Применить пресет",
    "settings.add_provider" to "Добавить провайдера",
    "settings.provider_name" to "Имя провайдера",
    "settings.delete_provider" to "Удалить провайдера",
    "settings.base_url" to "Базовый URL",
    "settings.hide_api_key" to "Скрыть ключ API",
    "settings.show_api_key" to "Показать ключ API",
    "settings.model" to "Модель",
    "settings.select_discovered_model" to "Выбрать обнаруженную модель",
    "settings.test_and_fetch_models" to "Проверить и получить модели",
    "settings.provider_saved" to "Настройки провайдера сохранены",
    "settings.save_provider" to "Сохранить провайдера",
    "settings.back_to_chat" to "Назад к чату",
    "settings.unsaved_changes_title" to "Сохранить изменения?",
    "settings.unsaved_changes_description" to "Настройки были изменены. Сохранить перед выходом?",
    "settings.discard_changes" to "Не сохранять",
    "settings.reset_confirmation_title" to "Сбросить все данные?",
    "settings.reset_confirmation_description" to "Это безвозвратно удалит секреты провайдеров на рабочем столе, ассистентов, настройки и все беседы.",
    "settings.confirm_reset" to "Сбросить данные",
    "common.cancel" to "Отмена",
    "common.save" to "Сохранить",
    "common.submit" to "Отправить",
    "common.expand" to "Развернуть ",
    "common.collapse" to "Свернуть ",
    "message.thinking" to "Думает...",
    "message.translation" to "Перевод",
    "attachment.audio" to "Аудио",
    "timeline.execution" to "Выполнение",
    "timeline.expand_execution" to "Развернуть выполнение",
    "timeline.collapse_execution" to "Свернуть выполнение",
    "timeline.expand_steps" to "Развернуть %d шагов",
    "timeline.reasoning" to "Рассуждение",
    "timeline.reasoning_duration" to "Рассуждение заняло %s с",
    "timeline.today" to "Сегодня",
    "timeline.yesterday" to "Вчера",
    "timeline.day_before_yesterday" to "Позавчера",
    "timeline.days_ago" to "%d дн. назад",
    "sidebar.recent" to "Недавние",
    "sidebar.most_active" to "Самые активные",
    "sidebar.sort_recent" to "Сортировать по недавней активности",
    "sidebar.sort_most_active" to "Сортировать по частоте использования",
    "sidebar.tool_call" to "Вызов инструмента",
    "sidebar.rename_folder" to "Переименовать папку",
    "common.new" to "Создать",
    "conversation.branch" to "Ветка беседы",
    "conversation.pinned" to "Закреплено",
    "conversation.pin" to "Закрепить",
    "conversation.unpin" to "Открепить",
    "conversation.move_to_chat" to "Переместить в чаты",
    "conversation.move_to_folder" to "Переместить в %s",
    "dialog.rename_conversation" to "Переименовать беседу",
    "dialog.conversation_system_prompt" to "Системный промпт беседы",
    "dialog.compress_history" to "Сжать историю беседы",
    "dialog.compress_history_description" to "Обобщить ранние сообщения и сохранить последние. Полная история сохраняется как восстанавливаемый снимок.",
    "dialog.target_tokens" to "Целевые токены",
    "dialog.keep_recent_messages" to "Сохранить последние сообщения (всего %d)",
    "dialog.additional_instructions" to "Дополнительные инструкции (необязательно)",
    "dialog.compress" to "Сжать",
    "dialog.translate_message" to "Перевести сообщение",
    "dialog.target_language" to "Целевой язык",
    "stats.messages" to "Сообщения",
    "stats.attachments" to "Вложения",
    "stats.characters" to "Символы текста и рассуждений",
    "stats.created_at" to "Создано",
    "stats.updated_at" to "Обновлено",
    "file.add_attachments" to "Добавить вложения",
    "file.parent_directory" to "Родительский каталог",
    "file.selected" to "Выбрано",
    "file.add_count" to "Добавить (%d)",
    "file.file_name" to "Имя файла",
    "file.export_conversation_markdown" to "Экспортировать беседу как Markdown",
    "file.export_backup" to "Экспортировать резервную копию RikkaHub",
    "agent.approval_request" to "Агент запрашивает эту операцию. Разрешить?",
    "agent.docker_network_warning" to "Выполняется в ограниченном Docker-контейнере с временным сетевым доступом к хосту, затем возвращается в изолированный офлайн-контейнер.",
    "agent.docker_warning" to "Выполняется в ограниченном Docker-контейнере, монтирующем только выбранное рабочее пространство.",
    "agent.local_shell_warning" to "Локальная оболочка выполняется с правами вашего текущего пользователя. Подтвердите команду и её последствия.",
    "agent.confirm_impact" to "Подтвердите команду и её последствия.",
    "agent.image_pull_warning" to "Загружает содержимое из реестра образов в локальный кэш Docker.",
    "agent.skill_warning" to "Инструкции навыков могут повлиять на дальнейшее поведение агента.",
    "agent.write_warning" to "Изменения файлов ограничены выбранным каталогом рабочей области.",
    "agent.remember_docker_shell" to "Автоматически одобрять Docker-команды для этой рабочей области в этом разговоре",
    "agent.remember_docker_network" to "Автоматически одобрять сетевые Docker-команды для этой рабочей области в этом разговоре",
    "agent.remember_image_pull" to "Автоматически одобрять эту загрузку образа в этом разговоре",
    "agent.remember_operation" to "Автоматически одобрять этот тип операции в этом разговоре",
    "agent.allow" to "Разрешить",
    "agent.deny" to "Отклонить",
    "settings.navigation" to "Разделы настроек",
    "settings.section.general" to "Общие",
    "settings.section.messages" to "Сообщения",
    "settings.section.interaction" to "Взаимодействие",
    "settings.section.data" to "Данные и общие сервисы",
    "settings.section.assistants" to "Ассистенты",
    "settings.section.providers" to "Модели и сервисы",
    "composer.placeholder" to "Сообщение для RikkaHub",
    "model_picker.title" to "Выбор модели",
    "model_picker.filter" to "Фильтр моделей",
    "model_picker.reasoning" to "Уровень рассуждений",
    "model_picker.default" to "По умолчанию",
    "model_picker.low" to "Низкий",
    "model_picker.medium" to "Средний",
    "model_picker.high" to "Высокий",
    "model_picker.manage_providers" to "Управление провайдерами",
    "model_picker.checking_balance" to "Проверка баланса",
    "model_picker.balance" to "Баланс: %s",
    "model_picker.balance_failed" to "Баланс недоступен",
    "mcp.manage" to "Управление MCP-сервисами",
    "mcp.check" to "Проверить доступность",
    "mcp.title" to "Сервисы MCP",
    "mcp.services_for_assistant" to "Сервисов для ассистента: %d",
    "mcp.check_all" to "Проверить все",
    "mcp.open_settings" to "Открыть настройки MCP",
    "mcp.no_servers" to "Сервисы MCP не настроены",
    "mcp.not_checked" to "Не проверено",
    "mcp.checking" to "Проверка",
    "mcp.tools_synced" to "Синхронизировано инструментов: %d",
    "mcp.available_tools" to "Доступно · инструментов: %d",
    "mcp.current_assistant" to "Этот ассистент",
    "mcp.enabled" to "Включено",
    "mcp.available" to "Доступно",
    "mcp.unavailable" to "Недоступно",
    "mcp_settings.title" to "Серверы MCP",
    "mcp_settings.description" to "Настройте общие серверы удалённых инструментов",
    "mcp_settings.assistant_description" to "Выберите общие серверы, доступные этому ассистенту",
    "mcp_settings.no_servers" to "Серверы MCP не настроены",
    "mcp_settings.add_server" to "Добавить сервер MCP",
    "mcp_settings.unnamed_server" to "Безымянный сервер MCP",
    "mcp_settings.delete_server" to "Удалить сервер MCP",
    "mcp_settings.server_name" to "Имя сервера",
    "mcp_settings.server_name_help" to "Только буквы и цифры; используется для создания стабильных имён инструментов",
    "mcp_settings.command" to "Команда",
    "mcp_settings.arguments" to "Аргументы команды",
    "mcp_settings.arguments_help" to "Один аргумент на строку",
    "mcp_settings.environment" to "Переменные окружения",
    "mcp_settings.environment_help" to "Одна пара КЛЮЧ=ЗНАЧЕНИЕ на строку",
    "mcp_settings.server_url" to "URL сервера",
    "mcp_settings.enable_server" to "Включить сервер",
    "mcp_settings.enable_server_help" to "Когда выключено, его инструменты не передаются модели",
    "mcp_settings.sync_failed" to "Не удалось синхронизировать инструменты MCP",
    "mcp_settings.sync_timeout" to "Синхронизация инструментов MCP превысила лимит в 10 секунд",
    "mcp_settings.sync_tools" to "Синхронизировать инструменты",
    "mcp_settings.collapse_tools" to "Свернуть инструменты",
    "mcp_settings.manage_tools" to "Управлять %d инструментами (включено %e)",
    "mcp_settings.tool" to "Инструмент MCP",
    "assistant.message_template" to "Шаблон сообщения",
    "assistant.template_variables" to "Переменные: {{ message }}, {{ role }}, {{ date }}, {{ time }}",
    "assistant.template_invalid" to "Допустимый шаблон Pebble должен содержать {{ message }}",
    "assistant.conversation_system_prompt" to "Системный промпт беседы",
    "assistant.conversation_system_prompt_help" to "Разрешить отдельным беседам переопределять системный промпт этого ассистента",
    "assistant.conversation_lorebooks" to "Лорбуки беседы",
    "assistant.conversation_lorebooks_help" to "Разрешить отдельным беседам включать или отключать инъекции промптов этого ассистента",
    "assistant.web_search" to "Веб-поиск",
    "assistant.web_search_help" to "По умолчанию включать совместимый с OpenAI веб-поиск в новых беседах",
    "assistant.local_time_tool" to "Инструмент локального времени",
    "assistant.local_time_tool_help" to "Разрешить модели считывать локальное время и часовой пояс устройства при необходимости",
    "assistant.ask_user_tool" to "Спросить пользователя",
    "assistant.ask_user_tool_help" to "Разрешить модели запрашивать у вас уточнение или подтверждение при необходимости",
    "assistant.max_tool_rounds" to "Максимальное количество раундов вызова инструментов на ответ",
    "assistant.max_tool_rounds_help" to "0 — без ограничений; по умолчанию 8",
    "assistant.agent_workspace" to "Рабочая область агента",
    "assistant.agent_workspace_help" to "Разрешить модели читать и записывать файлы, выполнять команды и загружать включённые навыки в выбранном каталоге",
    "assistant.workspace_directory" to "Каталог рабочей области",
    "assistant.workspace_directory_help" to "Только файловые инструменты агента могут обращаться к этому каталогу; локальная оболочка по-прежнему требует подтверждения каждый раз",
    "assistant.docker_container" to "Контейнер Docker",
    "assistant.local_shell" to "Локальная оболочка",
    "assistant.docker_image" to "Образ Docker",
    "assistant.docker_image_help" to "По умолчанию автономен, без привилегий и монтирует только рабочую область; первое получение требует одобрения",
    "assistant.enabled_skills" to "Включённые навыки",
    "assistant.enabled_skills_help" to "Разделяются запятыми; находятся в ~/.config/rikkahub/skills/<имя>/SKILL.md",
    "assistant.stream_output" to "Потоковый вывод",
    "assistant.stream_output_help" to "Показывать содержимое ответа по мере поступления, не дожидаясь полного ответа",
    "assistant.memory" to "Память",
    "assistant.memory_help" to "Позволить модели записывать, обновлять и использовать долговременную информацию между беседами",
    "assistant.global_memory" to "Глобальная общая память",
    "assistant.global_memory_help" to "Делиться хранилищем памяти с другими ассистентами, использующими глобальную память",
    "assistant.add_global_memory" to "Добавить глобальную память",
    "assistant.delete_global_memory" to "Удалить глобальную память",
    "assistant.shared_memory_content" to "Общий факт или предпочтение",
    "assistant.memory_entries" to "Записи памяти",
    "assistant.add_memory" to "Добавить память",
    "assistant.delete_memory" to "Удалить память",
    "assistant.memory_content" to "Факт или предпочтение",
    "assistant.temperature" to "Температура",
    "assistant.inherit_provider" to "Оставьте пустым для наследования настроек провайдера",
    "assistant.max_output_tokens" to "Максимум выходных токенов",
    "assistant.context_messages" to "Контекстные сообщения",
    "assistant.keep_all_when_empty" to "Оставьте пустым, чтобы сохранить все",
    "common.add" to "Добавить",
    "role.system" to "Система",
    "role.user" to "Пользователь",
    "role.assistant" to "Ассистент",
    "assistant.preset_messages" to "Предустановленные сообщения",
    "assistant.preset_messages_help" to "Добавлять примеры сообщений в каждую новую беседу",
    "assistant.message" to "Сообщение",
    "assistant.delete_preset_message" to "Удалить предустановленное сообщение",
    "assistant.quick_messages" to "Быстрые сообщения",
    "assistant.quick_messages_help" to "Вставлять повторно используемые подсказки из редактора чата",
    "assistant.title" to "Заголовок",
    "assistant.content" to "Содержимое",
    "assistant.delete_quick_message" to "Удалить быстрое сообщение",
    "assistant.regex_transforms" to "Преобразования regex",
    "assistant.regex_transforms_help" to "Преобразовывать пользовательский ввод, вывод ассистента или отображаемый текст",
    "assistant.rule_name" to "Имя правила",
    "assistant.delete_regex_rule" to "Удалить правило regex",
    "assistant.find_regex" to "Поисковое regex",
    "assistant.replace_with" to "Заменить на",
    "assistant.visual_only" to "Только визуально",
    "assistant.prompt_injections" to "Инъекции промптов / лорбуки",
    "assistant.prompt_injections_help" to "Сопоставлять контекст по ключевым словам или держать инъекцию всегда активной",
    "assistant.entry_name" to "Имя записи",
    "assistant.delete_injection" to "Удалить запись инъекции",
    "assistant.injection_content" to "Содержание инъекции",
    "assistant.keywords" to "Ключевые слова (через запятую)",
    "assistant.keywords_help" to "Если пусто — включите «всегда активно»",
    "assistant.priority" to "Приоритет",
    "assistant.priority_help" to "Чем выше значение, тем раньше вставляется",
    "assistant.scan_depth" to "Сообщений для сканирования",
    "assistant.scan_depth_help" to "Используется для поиска по ключевым словам",
    "assistant.injection_depth" to "Глубина инъекции",
    "assistant.injection_depth_help" to "Отсчёт с конца",
    "assistant.injection_role" to "Роль инъекции",
    "assistant.before_system" to "Перед системным промптом",
    "assistant.after_system" to "После системного промпта",
    "assistant.top_of_chat" to "Начало чата",
    "assistant.bottom_of_chat" to "Конец чата",
    "assistant.at_depth" to "На глубине",
    "assistant.always_active" to "Всегда активно",
    "assistant.regex_keywords" to "Regex-ключевые слова",
    "assistant.case_sensitive" to "С учётом регистра",
    "assistant.saved" to "Настройки ассистента сохранены",
    "assistant.save" to "Сохранить ассистента",
    "provider.title_model" to "Модель заголовка",
    "provider.response_format" to "Формат ответа",
    "provider.group.connection" to "Подключение",
    "provider.group.model" to "Модель и возможности",
    "provider.group.automation" to "Автоматизация",
    "provider.group.generation" to "Параметры генерации",
    "provider.group.advanced" to "Дополнительно",
    "provider.title_model_help" to "Оставьте пустым, чтобы использовать модель чата",
    "provider.suggestion_model" to "Модель предложений ответа",
    "provider.suggestion_model_help" to "Оставьте пустым, чтобы использовать модель чата; для предложений рассуждение отключено",
    "provider.title_prompt" to "Промпт заголовка",
    "provider.title_prompt_help" to "Поддерживает заполнители {locale} и {content}",
    "provider.token_usage" to "Использование токенов",
    "provider.token_usage_help" to "Запрашивать количество входных и выходных токенов у совместимых потоковых API",
    "provider.use_provider_default" to "Оставьте пустым для значения провайдера по умолчанию",
    "provider.system_prompt" to "Системный промпт",
    "provider.balance_query" to "Запрос баланса",
    "provider.balance_query_help" to "Запрашивать баланс или квоту учётной записи через API провайдера",
    "provider.balance_api_path" to "Путь API баланса",
    "provider.balance_api_path_help" to "Введите относительный путь или полный URL",
    "provider.balance_result_path" to "Путь JSON результата",
    "provider.balance_result_path_help" to "Например: data.balance или data.items[0].amount",
    "provider.checking_balance" to "Проверка баланса...",
    "provider.current_balance" to "Текущий баланс: %s",
    "provider.balance_failed" to "Не удалось проверить баланс: %s",
    "provider.check_balance" to "Проверить баланс",
    "request_overrides.headers" to "Пользовательские заголовки",
    "request_overrides.headers_help" to "Добавлять к запросам чата и моделей",
    "request_overrides.add_header" to "Добавить заголовок",
    "request_overrides.header" to "Заголовок",
    "request_overrides.value" to "Значение",
    "request_overrides.delete_header" to "Удалить заголовок",
    "request_overrides.body" to "Пользовательское тело запроса",
    "request_overrides.body_help" to "Объединять JSON с полями верхнего уровня запроса",
    "request_overrides.add_body" to "Добавить тело запроса",
    "request_overrides.key" to "Ключ",
    "request_overrides.json_value" to "JSON-значение",
    "request_overrides.invalid_json" to "Введите корректный JSON",
    "request_overrides.delete_body" to "Удалить тело запроса",
    "chat.restore_snapshot" to "Восстановить снимок истории %d: %s",
    "chat.snapshot_messages" to "%d сообщений",
    "chat.delete_snapshot" to "Удалить снимок истории",
    "jumper.top" to "К началу",
    "jumper.previous" to "Предыдущее сообщение",
    "jumper.next" to "Следующее сообщение",
    "jumper.bottom" to "К концу",
    "tool.calling" to "Выполняется",
    "tool.completed" to "Выполнено",
    "tool.input" to "Ввод",
    "tool.output" to "Вывод",
    "tool.result" to "Результат инструмента",
    "tool.answer_required" to "Требуется ваш ответ",
    "tool.web_search" to "Поиск в интернете",
    "tool.current_time" to "Получить текущее время",
    "tool.memory" to "Управление памятью",
    "tool.list_files" to "Список файлов",
    "tool.search_files" to "Поиск файлов",
    "tool.read_file" to "Прочитать файл",
    "tool.write_file" to "Записать файл",
    "tool.edit_file" to "Изменить файл",
    "tool.run_command" to "Выполнить команду",
    "tool.use_skill" to "Использовать навык",
    "model_picker.refresh_balance" to "Обновить баланс %s",
    "model_picker.current_model" to "Текущая модель",
    "model_capability.text" to "Текст",
    "model_capability.vision" to "Зрение",
    "model_capability.reasoning" to "Рассуждение",
    "model_capability.tools" to "Инструменты",
    "attachment.remove" to "Удалить вложение",
    "mcp.unnamed_service" to "Безымянный сервис MCP",
    "language.system_default" to "Системное значение",
    "language.chinese" to "Китайский",
    "user.you" to "Вы",
    "message.user_avatar" to "Аватар пользователя",
    "common.unnamed" to "Без названия",
    "theme.sakura" to "Сакура",
    "theme.ocean" to "Океан",
    "theme.forest" to "Лес",
    "theme.sunset" to "Закат",
    "theme.lavender" to "Лаванда",
    "theme.slate" to "Сланец",
    "font.system" to "Системный по умолчанию",
    "font.sans_serif" to "Без засечек",
    "font.serif" to "С засечками",
    "font.monospace" to "Моноширинный",
    "runtime.unknown_error" to "Неизвестная ошибка",
    "runtime.save_failed" to "Сбой сохранения: %s",
    "runtime.title_empty" to "Модель заголовка не вернула содержимого",
    "runtime.title_failed" to "Не удалось сгенерировать заголовок",
    "runtime.suggestions_empty" to "Модель предложений не вернула содержимого",
    "runtime.suggestions_failed" to "Не удалось сгенерировать предложения ответа",
    "runtime.mcp_configuration_invalid" to "Конфигурация MCP больше недействительна. Выберите серверы заново в настройках ассистента",
    "runtime.mcp_no_tools" to "Сервер MCP %s не предоставил пригодных инструментов",
    "runtime.mcp_sync_failed" to "Не удалось синхронизировать инструменты MCP: %s",
    "runtime.invalid_message_template" to "Недопустимый шаблон сообщения",
    "runtime.request_failed" to "Сбой запроса",
    "runtime.not_enough_messages" to "Недостаточно сообщений для сжатия",
    "runtime.compression_empty" to "Модель сжатия не вернула сводку",
    "runtime.compression_failed" to "Не удалось сжать беседу",
    "runtime.translation_empty" to "Модель перевода не вернула содержимого",
    "runtime.translation_failed" to "Ошибка перевода",
    "runtime.export_failed" to "Ошибка экспорта: %s",
    "runtime.import_failed" to "Ошибка импорта: %s",
    "runtime.tool_round_limit" to "Этот ответ достиг лимита в %d раундов вызова инструментов. Отправьте ещё одно сообщение, чтобы начать новый запуск.",
    "runtime.add_attachment_failed" to "Не удалось добавить вложение",
    "defaults.new_provider" to "Новый провайдер",
    "defaults.new_assistant" to "Новый ассистент",
    "file.import_backup" to "Импорт резервной копии RikkaHub",
    "file.imported_backup" to "Резервная копия импортирована из %s",
    "file.choose_attachments" to "Добавить изображения, аудио, текст или документы",
    "mermaid.diagram" to "Диаграмма",
    "mermaid.code" to "Код",
    "mermaid.save_image" to "Сохранить изображение",
    "mermaid.download" to "Скачать",
    "mermaid.fullscreen" to "На весь экран",
    "mermaid.exit_fullscreen" to "Выйти из полноэкранного режима",
    "provider.connection_success" to "Подключено · доступно моделей: %d"
)
