package me.rerere.rikkahub.desktop

internal val EnglishDesktopTranslations = mapOf(
    "settings.language" to "Language",
    "settings.language_description" to "Choose the language used by the desktop app",
    "settings.title" to "Settings",
    "settings.subtitle" to "Appearance, interaction & model services",
    "settings.back" to "Back",
    "settings.color_mode" to "Color mode",
    "settings.color_mode_description" to "Follow the system, or use a fixed light or dark theme",
    "settings.system" to "System",
    "settings.light" to "Light",
    "settings.dark" to "Dark",
    "settings.theme_color" to "Theme color",
    "settings.theme_color_description" to "Choose an accent color and matching tones for the interface",
    "settings.font" to "Interface font",
    "settings.font_description" to "%s; code blocks remain monospaced",
    "settings.chat_font_size" to "Chat font size",
    "sidebar.welcome" to "Welcome back",
    "sidebar.new_chat" to "New chat",
    "sidebar.search_chats" to "Search chats",
    "sidebar.back_to_chats" to "Back to chats",
    "sidebar.favorite_messages" to "Favorite messages",
    "sidebar.search" to "Search",
    "sidebar.all_assistants" to "All assistants",
    "sidebar.all_tags" to "All tags",
    "sidebar.chats" to "Chats",
    "chat.open_conversations" to "Open conversations",
    "chat.options" to "Conversation options",
    "chat.rename" to "Rename",
    "chat.export_markdown" to "Export Markdown",
    "chat.generate_title" to "Generate title",
    "chat.statistics" to "Conversation statistics",
    "chat.generate_suggestions" to "Generate reply suggestions",
    "chat.compress_history" to "Compress history",
    "chat.set_system_prompt" to "Set system prompt",
    "chat.edit_system_prompt" to "Edit system prompt",
    "chat.enable_lorebooks" to "Enable conversation lorebooks",
    "chat.disable_lorebooks" to "Disable conversation lorebooks",
    "chat.move_to_folder" to "Move to folder",
    "chat.uncategorized" to "Uncategorized",
    "chat.new_folder" to "New folder",
    "chat.close" to "Close",
    "message.sources" to "Sources",
    "message.source_number" to "Source %d",
    "message.input_tokens" to "Input tokens",
    "message.output_tokens" to "Output tokens",
    "message.cached_tokens" to "Cached tokens",
    "message.previous_version" to "Previous version",
    "message.next_version" to "Next version",
    "message.copy" to "Copy",
    "message.fork" to "Fork from here",
    "message.regenerate" to "Regenerate",
    "message.translate" to "Translate",
    "message.favorite" to "Favorite",
    "message.unfavorite" to "Remove favorite",
    "message.edit" to "Edit",
    "message.delete" to "Delete",
    "empty_chat.greeting" to "How can I help?",
    "composer.collapse" to "Collapse composer",
    "composer.expand" to "Expand composer",
    "composer.add_attachment" to "Add attachment",
    "composer.enable_web_search" to "Enable web search",
    "composer.disable_web_search" to "Disable web search",
    "composer.quick_messages" to "Quick messages",
    "composer.manage_assistants" to "Manage assistants and tags",
    "composer.stop_generation" to "Stop generating",
    "composer.send" to "Send; long press to add without a reply",
    "settings.show_user_avatar" to "Show user avatar",
    "settings.show_user_avatar_description" to "Show an avatar beside user messages",
    "settings.user_nickname" to "User nickname",
    "settings.user_nickname_description" to "Shown beside user messages; defaults to You when empty",
    "settings.user_nickname_placeholder" to "You",
    "settings.show_model_icon" to "Show model icon",
    "settings.show_model_icon_description" to "Show the model icon beside assistant messages",
    "settings.show_model_name" to "Show model name",
    "settings.show_model_name_description" to "Show the model name above assistant messages",
    "settings.assistant_bubble" to "Assistant bubble",
    "settings.assistant_bubble_description" to "Show assistant text in a filled bubble",
    "settings.message_timestamp" to "Message timestamp",
    "settings.message_timestamp_description" to "Show the creation time in each message header",
    "settings.reasoning" to "Reasoning content",
    "settings.reasoning_description" to "Show reasoning returned by compatible models",
    "settings.collapse_reasoning" to "Collapse reasoning after completion",
    "settings.collapse_reasoning_description" to "Only expand reasoning while a response is generating",
    "settings.code_wrap" to "Wrap code blocks",
    "settings.code_wrap_description" to "Wrap long code lines instead of scrolling horizontally",
    "settings.chinese_typography" to "Chinese typography",
    "settings.chinese_typography_description" to "Add spacing between Chinese and Latin text, numbers, or symbols",
    "settings.mermaid_rendering" to "Render Mermaid diagrams",
    "settings.mermaid_rendering_description" to "Render Mermaid code blocks as interactive diagrams",
    "settings.mermaid_cli" to "Allow Mermaid CLI",
    "settings.mermaid_cli_description" to "Permit Mermaid CLI to run locally for diagram rendering",
    "settings.mermaid_cli_path" to "Mermaid CLI path",
    "settings.mermaid_cli_path_description" to "Leave empty to detect PATH, npm global, and local user locations automatically",
    "settings.mermaid_system_browser" to "Use system browser",
    "settings.mermaid_system_browser_description" to "Allow Mermaid CLI to use an installed Chromium-based browser",
    "settings.send_on_enter" to "Send with Enter",
    "settings.send_on_enter_description" to "When off, Ctrl+Enter sends and Enter adds a new line",
    "settings.auto_scroll" to "Auto-scroll",
    "settings.auto_scroll_description" to "Follow new reasoning and response content while generating",
    "settings.smooth_scroll" to "Smooth scrolling",
    "settings.smooth_scroll_description" to "Animate mouse-wheel scrolling in the chat view",
    "settings.message_navigation" to "Message navigation",
    "settings.message_navigation_description" to "Show buttons for the top, previous, next, and bottom after scrolling",
    "settings.message_navigation_left" to "Message navigation on the left",
    "settings.message_navigation_left_description" to "Shown on the right side of the message area by default",
    "jumper.search_messages" to "Search messages",
    "jumper.no_matching_messages" to "No matching messages",
    "jumper.user" to "You",
    "jumper.assistant" to "Assistant",
    "jumper.empty_message" to "No message text",
    "settings.export_backup" to "Export backup",
    "settings.export_backup_description" to "Save providers, assistants, preferences, and chats as JSON",
    "settings.export" to "Export",
    "settings.import_backup" to "Import backup",
    "settings.import_backup_description" to "Replace current desktop data with a RikkaHub backup",
    "settings.import" to "Import",
    "settings.reset_data" to "Reset all data",
    "settings.reset_data_description" to "Delete local providers, assistants, preferences, and chats. This cannot be undone.",
    "settings.reset" to "Reset",
    "settings.web_search" to "Web search service",
    "settings.web_search_description" to "Use an external search service when configured; otherwise use the model provider's native search",
    "settings.searxng_url" to "SearXNG URL",
    "settings.api_key" to "API key",
    "settings.search_result_count" to "%d results per search",
    "settings.test_search" to "Test search",
    "settings.search_test_success" to "Web search connection is working",
    "settings.search_test_failed" to "Search test failed",
    "settings.add_assistant" to "Add assistant",
    "settings.assistant_name" to "Assistant name",
    "settings.copy_assistant" to "Copy assistant",
    "settings.delete_assistant" to "Delete assistant",
    "settings.tags" to "Tags (comma-separated)",
    "settings.model_inherit" to "Model (leave empty to use the provider default)",
    "settings.select_model" to "Select model",
    "settings.system_prompt_inherit" to "System prompt (leave empty to use the provider default)",
    "settings.apply_preset" to "Apply preset",
    "settings.add_provider" to "Add provider",
    "settings.provider_name" to "Provider name",
    "settings.delete_provider" to "Delete provider",
    "settings.base_url" to "Base URL",
    "settings.hide_api_key" to "Hide API key",
    "settings.show_api_key" to "Show API key",
    "settings.model" to "Model",
    "settings.select_discovered_model" to "Select discovered model",
    "settings.test_and_fetch_models" to "Test and fetch models",
    "settings.provider_saved" to "Provider settings saved",
    "settings.save_provider" to "Save provider",
    "settings.back_to_chat" to "Back to chat",
    "settings.unsaved_changes_title" to "Save changes?",
    "settings.unsaved_changes_description" to "Your settings have changed. Save before leaving?",
    "settings.discard_changes" to "Don't save",
    "settings.reset_confirmation_title" to "Reset all data?",
    "settings.reset_confirmation_description" to "This permanently deletes desktop provider secrets, assistants, settings, and every conversation.",
    "settings.confirm_reset" to "Reset data",
    "common.cancel" to "Cancel",
    "common.save" to "Save",
    "common.submit" to "Submit",
    "common.expand" to "Expand ",
    "common.collapse" to "Collapse ",
    "message.thinking" to "Thinking...",
    "message.translation" to "Translation",
    "attachment.audio" to "Audio",
    "timeline.execution" to "Execution",
    "timeline.expand_execution" to "Expand execution",
    "timeline.collapse_execution" to "Collapse execution",
    "timeline.expand_steps" to "Expand %d steps",
    "timeline.reasoning" to "Reasoning",
    "timeline.reasoning_duration" to "Reasoned for %s seconds",
    "timeline.today" to "Today",
    "timeline.yesterday" to "Yesterday",
    "timeline.day_before_yesterday" to "Day before yesterday",
    "timeline.days_ago" to "%d days ago",
    "sidebar.recent" to "Recent",
    "sidebar.most_active" to "Most active",
    "sidebar.sort_recent" to "Sort by recent activity",
    "sidebar.sort_most_active" to "Sort by usage frequency",
    "sidebar.tool_call" to "Tool call",
    "sidebar.rename_folder" to "Rename folder",
    "common.new" to "New",
    "conversation.branch" to "Conversation branch",
    "conversation.pinned" to "Pinned",
    "conversation.pin" to "Pin",
    "conversation.unpin" to "Unpin",
    "conversation.move_to_chat" to "Move to chats",
    "conversation.move_to_folder" to "Move to %s",
    "dialog.rename_conversation" to "Rename conversation",
    "dialog.conversation_system_prompt" to "Conversation system prompt",
    "dialog.compress_history" to "Compress conversation history",
    "dialog.compress_history_description" to "Summarize earlier messages and keep recent messages. The full history is saved as a restorable snapshot.",
    "dialog.target_tokens" to "Target tokens",
    "dialog.keep_recent_messages" to "Keep recent messages (of %d total)",
    "dialog.additional_instructions" to "Additional instructions (optional)",
    "dialog.compress" to "Compress",
    "dialog.translate_message" to "Translate message",
    "dialog.target_language" to "Target language",
    "stats.messages" to "Messages",
    "stats.attachments" to "Attachments",
    "stats.characters" to "Text and reasoning characters",
    "stats.created_at" to "Created",
    "stats.updated_at" to "Updated",
    "file.add_attachments" to "Add attachments",
    "file.parent_directory" to "Parent directory",
    "file.selected" to "Selected",
    "file.add_count" to "Add (%d)",
    "file.file_name" to "File name",
    "file.export_conversation_markdown" to "Export conversation as Markdown",
    "file.export_backup" to "Export RikkaHub backup",
    "agent.approval_request" to "The agent requests this operation. Allow it?",
    "agent.docker_network_warning" to "Runs in a restricted Docker container with temporary host networking, then returns to an isolated offline container.",
    "agent.docker_warning" to "Runs in a restricted Docker container that mounts only the selected workspace.",
    "agent.local_shell_warning" to "The local shell runs with your current user permissions. Confirm the command and its impact.",
    "agent.confirm_impact" to "Confirm the command and its impact.",
    "agent.image_pull_warning" to "Downloads content from an image registry into the local Docker cache.",
    "agent.skill_warning" to "Skill instructions may affect later agent behavior.",
    "agent.write_warning" to "File changes are limited to the selected workspace directory.",
    "agent.remember_docker_shell" to "Automatically approve Docker commands for this workspace in this conversation",
    "agent.remember_docker_network" to "Automatically approve Docker network commands for this workspace in this conversation",
    "agent.remember_image_pull" to "Automatically approve this image download in this conversation",
    "agent.remember_operation" to "Automatically approve this type of operation in this conversation",
    "agent.allow" to "Allow",
    "agent.deny" to "Deny",
    "settings.navigation" to "Settings",
    "settings.section.general" to "General",
    "settings.section.messages" to "Messages",
    "settings.section.interaction" to "Interaction",
    "settings.section.data" to "Data, backup & web search",
    "settings.section.assistants" to "Assistants",
    "settings.section.providers" to "Models & services",
    "composer.placeholder" to "Message RikkaHub",
    "model_picker.title" to "Choose model",
    "model_picker.filter" to "Filter models",
    "model_picker.reasoning" to "Reasoning effort",
    "model_picker.default" to "Default",
    "model_picker.low" to "Low",
    "model_picker.medium" to "Medium",
    "model_picker.high" to "High",
    "model_picker.manage_providers" to "Manage providers",
    "model_picker.checking_balance" to "Checking balance",
    "model_picker.balance" to "Balance: %s",
    "model_picker.balance_failed" to "Balance unavailable",
    "mcp.manage" to "Manage MCP services",
    "mcp.check" to "Check availability",
    "mcp.title" to "MCP services",
    "mcp.services_for_assistant" to "%d services for this assistant",
    "mcp.check_all" to "Check all",
    "mcp.open_settings" to "Open MCP settings",
    "mcp.no_servers" to "No MCP services configured",
    "mcp.not_checked" to "Not checked",
    "mcp.checking" to "Checking",
    "mcp.tools_synced" to "%d tools synced",
    "mcp.available_tools" to "Available · %d tools",
    "mcp.current_assistant" to "This assistant",
    "mcp.enabled" to "Enabled",
    "mcp.available" to "Available",
    "mcp.unavailable" to "Unavailable",
    "mcp_settings.title" to "MCP servers",
    "mcp_settings.description" to "Sync remote tools, then enable the servers this assistant needs",
    "mcp_settings.add_server" to "Add MCP server",
    "mcp_settings.unnamed_server" to "Unnamed MCP server",
    "mcp_settings.delete_server" to "Delete MCP server",
    "mcp_settings.server_name" to "Server name",
    "mcp_settings.server_name_help" to "Letters and numbers only; used to create stable tool names",
    "mcp_settings.command" to "Command",
    "mcp_settings.arguments" to "Command arguments",
    "mcp_settings.arguments_help" to "One argument per line",
    "mcp_settings.environment" to "Environment variables",
    "mcp_settings.environment_help" to "One KEY=VALUE pair per line",
    "mcp_settings.server_url" to "Server URL",
    "mcp_settings.enable_server" to "Enable server",
    "mcp_settings.enable_server_help" to "When off, its tools are not exposed to the model",
    "mcp_settings.sync_failed" to "Failed to sync MCP tools",
    "mcp_settings.sync_timeout" to "MCP tool sync timed out after 10 seconds",
    "mcp_settings.sync_tools" to "Sync tools",
    "mcp_settings.collapse_tools" to "Collapse tools",
    "mcp_settings.manage_tools" to "Manage %d tools (%e enabled)",
    "mcp_settings.tool" to "MCP tool",
    "assistant.message_template" to "Message template",
    "assistant.template_variables" to "Variables: {{ message }}, {{ role }}, {{ date }}, {{ time }}",
    "assistant.template_invalid" to "A valid Pebble template must include {{ message }}",
    "assistant.conversation_system_prompt" to "Conversation system prompt",
    "assistant.conversation_system_prompt_help" to "Allow individual conversations to override this assistant's system prompt",
    "assistant.conversation_lorebooks" to "Conversation lorebooks",
    "assistant.conversation_lorebooks_help" to "Allow individual conversations to enable or disable this assistant's prompt injections",
    "assistant.web_search" to "Web search",
    "assistant.web_search_help" to "Enable OpenAI-compatible web search in new conversations by default",
    "assistant.local_time_tool" to "Local time tool",
    "assistant.local_time_tool_help" to "Allow the model to read this device's local time and time zone when needed",
    "assistant.ask_user_tool" to "Ask user",
    "assistant.ask_user_tool_help" to "Allow the model to ask you for clarification or confirmation when needed",
    "assistant.max_tool_rounds" to "Maximum tool-call rounds per reply",
    "assistant.max_tool_rounds_help" to "0 means unlimited; the default is 8",
    "assistant.agent_workspace" to "Agent workspace",
    "assistant.agent_workspace_help" to "Allow the model to read and write files, run commands, and load enabled skills in the selected directory",
    "assistant.workspace_directory" to "Workspace directory",
    "assistant.workspace_directory_help" to "Only agent file tools can access this directory; the local shell still requires confirmation each time",
    "assistant.docker_container" to "Docker container",
    "assistant.local_shell" to "Local shell",
    "assistant.docker_image" to "Docker image",
    "assistant.docker_image_help" to "Offline, unprivileged, and mounts only the workspace by default; the first pull needs approval",
    "assistant.enabled_skills" to "Enabled skills",
    "assistant.enabled_skills_help" to "Comma-separated; stored in ~/.config/rikkahub/skills/<name>/SKILL.md",
    "assistant.stream_output" to "Stream output",
    "assistant.stream_output_help" to "Show response content as it arrives instead of waiting for the full response",
    "assistant.memory" to "Memory",
    "assistant.memory_help" to "Allow the model to record, update, and use long-term information across conversations",
    "assistant.global_memory" to "Global shared memory",
    "assistant.global_memory_help" to "Share a memory store with other assistants using global memory",
    "assistant.add_global_memory" to "Add global memory",
    "assistant.delete_global_memory" to "Delete global memory",
    "assistant.shared_memory_content" to "Shared fact or preference",
    "assistant.memory_entries" to "Memory entries",
    "assistant.add_memory" to "Add memory",
    "assistant.delete_memory" to "Delete memory",
    "assistant.memory_content" to "Fact or preference",
    "assistant.temperature" to "Temperature",
    "assistant.inherit_provider" to "Leave empty to inherit the provider setting",
    "assistant.max_output_tokens" to "Maximum output tokens",
    "assistant.context_messages" to "Context messages",
    "assistant.keep_all_when_empty" to "Leave empty to keep all",
    "common.add" to "Add",
    "role.system" to "System",
    "role.user" to "User",
    "role.assistant" to "Assistant",
    "assistant.preset_messages" to "Preset messages",
    "assistant.preset_messages_help" to "Add example messages to every new conversation",
    "assistant.message" to "Message",
    "assistant.delete_preset_message" to "Delete preset message",
    "assistant.quick_messages" to "Quick messages",
    "assistant.quick_messages_help" to "Insert reusable prompts from the chat composer",
    "assistant.title" to "Title",
    "assistant.content" to "Content",
    "assistant.delete_quick_message" to "Delete quick message",
    "assistant.regex_transforms" to "Regex transforms",
    "assistant.regex_transforms_help" to "Transform user input, assistant output, or displayed text",
    "assistant.rule_name" to "Rule name",
    "assistant.delete_regex_rule" to "Delete regex rule",
    "assistant.find_regex" to "Find regex",
    "assistant.replace_with" to "Replace with",
    "assistant.visual_only" to "Visual only",
    "assistant.prompt_injections" to "Prompt injections / lorebooks",
    "assistant.prompt_injections_help" to "Match context by keyword, or keep an injection always active",
    "assistant.entry_name" to "Entry name",
    "assistant.delete_injection" to "Delete injection entry",
    "assistant.injection_content" to "Injection content",
    "assistant.keywords" to "Keywords (comma-separated)",
    "assistant.keywords_help" to "Enable always active when left empty",
    "assistant.priority" to "Priority",
    "assistant.priority_help" to "Higher values are placed earlier",
    "assistant.scan_depth" to "Messages to scan",
    "assistant.scan_depth_help" to "Used for keyword matching",
    "assistant.injection_depth" to "Injection depth",
    "assistant.injection_depth_help" to "Count from the end",
    "assistant.injection_role" to "Injection role",
    "assistant.before_system" to "Before system prompt",
    "assistant.after_system" to "After system prompt",
    "assistant.top_of_chat" to "Top of chat",
    "assistant.bottom_of_chat" to "Bottom of chat",
    "assistant.at_depth" to "At depth",
    "assistant.always_active" to "Always active",
    "assistant.regex_keywords" to "Regex keywords",
    "assistant.case_sensitive" to "Case-sensitive",
    "assistant.saved" to "Assistant settings saved",
    "assistant.save" to "Save assistant",
    "provider.title_model" to "Title model",
    "provider.title_model_help" to "Leave empty to use the chat model",
    "provider.suggestion_model" to "Reply suggestion model",
    "provider.suggestion_model_help" to "Leave empty to use the chat model; reasoning is disabled for suggestions",
    "provider.title_prompt" to "Title prompt",
    "provider.title_prompt_help" to "Supports the {locale} and {content} placeholders",
    "provider.token_usage" to "Token usage",
    "provider.token_usage_help" to "Request input and output token counts from compatible streaming APIs",
    "provider.use_provider_default" to "Leave empty to use the provider default",
    "provider.system_prompt" to "System prompt",
    "provider.balance_query" to "Balance query",
    "provider.balance_query_help" to "Query account balance or quota through the provider API",
    "provider.balance_api_path" to "Balance API path",
    "provider.balance_api_path_help" to "Enter a relative path or a full URL",
    "provider.balance_result_path" to "Result JSON path",
    "provider.balance_result_path_help" to "For example: data.balance or data.items[0].amount",
    "provider.checking_balance" to "Checking balance...",
    "provider.current_balance" to "Current balance: %s",
    "provider.balance_failed" to "Balance check failed: %s",
    "provider.check_balance" to "Check balance",
    "request_overrides.headers" to "Custom headers",
    "request_overrides.headers_help" to "Add to chat and model requests",
    "request_overrides.add_header" to "Add custom header",
    "request_overrides.header" to "Header",
    "request_overrides.value" to "Value",
    "request_overrides.delete_header" to "Delete custom header",
    "request_overrides.body" to "Custom request body",
    "request_overrides.body_help" to "Merge JSON into top-level request fields",
    "request_overrides.add_body" to "Add custom request body",
    "request_overrides.key" to "Key",
    "request_overrides.json_value" to "JSON value",
    "request_overrides.invalid_json" to "Enter valid JSON",
    "request_overrides.delete_body" to "Delete custom request body",
    "chat.restore_snapshot" to "Restore history snapshot %d: %s",
    "chat.snapshot_messages" to "%d messages",
    "chat.delete_snapshot" to "Delete history snapshot",
    "jumper.top" to "Jump to top",
    "jumper.previous" to "Previous message",
    "jumper.next" to "Next message",
    "jumper.bottom" to "Jump to bottom",
    "tool.calling" to "Calling",
    "tool.completed" to "Completed",
    "tool.input" to "Input",
    "tool.output" to "Output",
    "tool.result" to "Tool result",
    "tool.answer_required" to "Your answer is needed",
    "tool.web_search" to "Search the web",
    "tool.current_time" to "Get current time",
    "tool.memory" to "Manage memory",
    "tool.list_files" to "List files",
    "tool.search_files" to "Search files",
    "tool.read_file" to "Read file",
    "tool.write_file" to "Write file",
    "tool.edit_file" to "Edit file",
    "tool.run_command" to "Run command",
    "tool.use_skill" to "Use skill",
    "model_picker.refresh_balance" to "Refresh %s balance",
    "model_picker.current_model" to "Current model",
    "model_capability.text" to "Text",
    "model_capability.vision" to "Vision",
    "model_capability.reasoning" to "Reasoning",
    "model_capability.tools" to "Tools",
    "attachment.remove" to "Remove attachment",
    "mcp.unnamed_service" to "Unnamed MCP service",
    "language.system_default" to "System default",
    "language.chinese" to "Chinese",
    "user.you" to "You",
    "message.user_avatar" to "User avatar",
    "common.unnamed" to "Unnamed",
    "theme.sakura" to "Sakura",
    "theme.ocean" to "Ocean",
    "theme.forest" to "Forest",
    "theme.sunset" to "Sunset",
    "theme.lavender" to "Lavender",
    "theme.slate" to "Slate",
    "font.system" to "System default",
    "font.sans_serif" to "Sans serif",
    "font.serif" to "Serif",
    "font.monospace" to "Monospace",
    "runtime.unknown_error" to "Unknown error",
    "runtime.save_failed" to "Save failed: %s",
    "runtime.title_empty" to "The title model returned no content",
    "runtime.title_failed" to "Failed to generate title",
    "runtime.suggestions_empty" to "The suggestion model returned no content",
    "runtime.suggestions_failed" to "Failed to generate reply suggestions",
    "runtime.mcp_configuration_invalid" to "The MCP configuration is no longer valid. Select the servers again in assistant settings.",
    "runtime.mcp_no_tools" to "MCP server %s did not provide usable tools",
    "runtime.mcp_sync_failed" to "Failed to sync MCP tools: %s",
    "runtime.invalid_message_template" to "Invalid message template",
    "runtime.request_failed" to "Request failed",
    "runtime.not_enough_messages" to "There are not enough messages to compress",
    "runtime.compression_empty" to "The compression model returned no summary",
    "runtime.compression_failed" to "Failed to compress conversation",
    "runtime.translation_empty" to "The translation model returned no content",
    "runtime.translation_failed" to "Translation failed",
    "runtime.export_failed" to "Export failed: %s",
    "runtime.import_failed" to "Import failed: %s",
    "runtime.tool_round_limit" to "This reply reached the limit of %d tool-call rounds. Send another message to begin a new run.",
    "runtime.add_attachment_failed" to "Failed to add attachment",
    "defaults.new_provider" to "New provider",
    "defaults.new_assistant" to "New assistant",
    "file.import_backup" to "Import RikkaHub backup",
    "file.imported_backup" to "Imported backup from %s",
    "file.choose_attachments" to "Add images, audio, text, or documents",
    "mermaid.diagram" to "Diagram",
    "mermaid.code" to "Code",
    "mermaid.save_image" to "Save image",
    "mermaid.download" to "Download",
    "mermaid.fullscreen" to "Full screen",
    "mermaid.exit_fullscreen" to "Exit full screen",
    "provider.connection_success" to "Connected · %d models available"
)
