package me.rerere.rikkahub.desktop

internal val JapaneseDesktopTranslations = mapOf(
        "settings.language" to "言語", "settings.language_description" to "デスクトップアプリの表示言語を選択します",
        "settings.title" to "設定", "settings.subtitle" to "外観、操作、モデルサービス",
        "settings.back" to "戻る", "settings.color_mode" to "カラーモード",
        "settings.color_mode_description" to "システムに従うか、固定のライトまたはダークテーマを使用します",
        "settings.system" to "システム", "settings.light" to "ライト", "settings.dark" to "ダーク",
        "settings.theme_color" to "テーマカラー", "settings.theme_color_description" to "インターフェースのアクセントカラーと階調を選択します",
        "settings.font" to "インターフェースのフォント", "settings.font_description" to "%s。コードブロックは等幅のままです",
        "settings.chat_font_size" to "チャットのフォントサイズ",
        "sidebar.welcome" to "おかえりなさい", "sidebar.new_chat" to "新しいチャット",
        "sidebar.search_chats" to "チャットを検索", "sidebar.back_to_chats" to "チャットに戻る",
        "sidebar.favorite_messages" to "お気に入りのメッセージ", "sidebar.search" to "検索",
        "sidebar.all_assistants" to "すべてのアシスタント", "sidebar.all_tags" to "すべてのタグ",
        "sidebar.chats" to "チャット", "chat.open_conversations" to "会話を開く",
        "chat.options" to "会話オプション", "chat.rename" to "名前を変更",
        "chat.export_markdown" to "Markdown をエクスポート", "chat.generate_title" to "タイトルを生成",
        "chat.statistics" to "会話の統計", "chat.generate_suggestions" to "返信候補を生成",
        "chat.compress_history" to "履歴を圧縮", "chat.set_system_prompt" to "システムプロンプトを設定",
        "chat.edit_system_prompt" to "システムプロンプトを編集", "chat.enable_lorebooks" to "会話ロアブックを有効化",
        "chat.disable_lorebooks" to "会話ロアブックを無効化", "chat.move_to_folder" to "フォルダーへ移動",
        "chat.uncategorized" to "未分類", "chat.new_folder" to "新しいフォルダー",
        "chat.close" to "閉じる", "message.sources" to "ソース",
        "message.source_number" to "ソース %d", "message.input_tokens" to "入力トークン",
        "message.output_tokens" to "出力トークン", "message.cached_tokens" to "キャッシュトークン",
        "message.previous_version" to "前のバージョン", "message.next_version" to "次のバージョン",
        "message.copy" to "コピー", "message.fork" to "ここから分岐",
        "message.regenerate" to "再生成", "message.translate" to "翻訳",
        "message.favorite" to "お気に入り", "message.unfavorite" to "お気に入りから削除",
        "message.edit" to "編集", "message.delete" to "削除",
        "empty_chat.greeting" to "どのようにお手伝いしましょうか？",
        "composer.collapse" to "作成を折りたたむ", "composer.expand" to "作成を展開",
        "composer.add_attachment" to "添付を追加", "composer.enable_web_search" to "ウェブ検索を有効化",
        "composer.disable_web_search" to "ウェブ検索を無効化", "composer.quick_messages" to "クイックメッセージ",
        "composer.manage_assistants" to "アシスタントとタグを管理", "composer.stop_generation" to "生成を停止",
        "composer.send" to "送信。長押しで返信なしで追加",
        "settings.show_user_avatar" to "ユーザーアバターを表示", "settings.show_user_avatar_description" to "ユーザーメッセージの横にアバターを表示",
        "settings.user_nickname" to "ユーザー名", "settings.user_nickname_description" to "ユーザーメッセージの横に表示。空の場合は「あなた」になります",
        "settings.user_nickname_placeholder" to "あなた", "settings.show_model_icon" to "モデルアイコンを表示",
        "settings.show_model_icon_description" to "アシスタントメッセージの横にモデルアイコンを表示",
        "settings.show_model_name" to "モデル名を表示", "settings.show_model_name_description" to "アシスタントメッセージの上にモデル名を表示",
        "settings.assistant_bubble" to "アシスタントの吹き出し", "settings.assistant_bubble_description" to "塗りつぶしの吹き出しでアシスタントのテキストを表示",
        "settings.message_timestamp" to "メッセージ時刻", "settings.message_timestamp_description" to "各メッセージヘッダーに作成時刻を表示",
        "settings.reasoning" to "推論内容", "settings.reasoning_description" to "互換モデルが返す推論を表示",
        "settings.collapse_reasoning" to "完了後に推論を折りたたむ", "settings.collapse_reasoning_description" to "応答生成中のみ推論を展開します",
        "settings.code_wrap" to "コードブロックを折り返す", "settings.code_wrap_description" to "長いコード行を横スクロールではなく折り返します",
        "settings.chinese_typography" to "中国語組版", "settings.chinese_typography_description" to "中国語とラテン文字、数字、記号の間に間隔を追加します",
        "settings.mermaid_rendering" to "Mermaid 図をレンダリング", "settings.mermaid_rendering_description" to "Mermaid コードブロックをインタラクティブな図としてレンダリングします",
        "settings.mermaid_cli" to "Mermaid CLI を許可", "settings.mermaid_cli_description" to "Mermaid CLI によるローカルでの図のレンダリングを許可します",
        "settings.mermaid_cli_path" to "Mermaid CLI のパス", "settings.mermaid_cli_path_description" to "空欄の場合、PATH、npm グローバル、ユーザーのローカルディレクトリを自動検出します",
        "settings.mermaid_system_browser" to "システムブラウザーを使用", "settings.mermaid_system_browser_description" to "Mermaid CLI がインストール済みの Chromium ベースブラウザーを使用することを許可します",
        "settings.send_on_enter" to "Enter で送信", "settings.send_on_enter_description" to "オフの場合、Ctrl+Enter で送信、Enter で改行",
        "settings.auto_scroll" to "自動スクロール", "settings.auto_scroll_description" to "生成中に新しい推論と応答を追います",
        "settings.smooth_scroll" to "スムーズスクロール", "settings.smooth_scroll_description" to "チャット画面のマウスホイール操作をアニメーション表示します",
        "settings.message_navigation" to "メッセージナビゲーション", "settings.message_navigation_description" to "スクロール後に先頭、前、次、末尾ボタンを表示",
        "settings.message_navigation_left" to "メッセージナビゲーションを左に表示", "settings.message_navigation_left_description" to "デフォルトではメッセージ領域の右側に表示されます",
        "settings.export_backup" to "バックアップをエクスポート", "settings.export_backup_description" to "プロバイダー、アシスタント、設定、チャットを JSON で保存",
        "settings.export" to "エクスポート", "settings.import_backup" to "バックアップをインポート",
        "settings.import_backup_description" to "RikkaHub バックアップでデスクトップデータを置き換えます",
        "settings.import" to "インポート", "settings.reset_data" to "すべてのデータをリセット",
        "settings.reset_data_description" to "ローカルのプロバイダー、アシスタント、設定、チャットを削除します。元に戻せません。",
        "settings.reset" to "リセット", "settings.web_search" to "ウェブ検索サービス",
        "settings.web_search_description" to "設定時は外部検索サービスを使用。未設定時はモデルプロバイダーのネイティブ検索",
        "settings.searxng_url" to "SearXNG URL", "settings.api_key" to "API キー",
        "settings.search_result_count" to "検索あたり %d 件", "settings.test_search" to "検索をテスト",
        "settings.search_test_success" to "ウェブ検索の接続は正常です", "settings.search_test_failed" to "検索テストに失敗しました",
        "settings.add_assistant" to "アシスタントを追加", "settings.assistant_name" to "アシスタント名",
        "settings.copy_assistant" to "アシスタントをコピー", "settings.delete_assistant" to "アシスタントを削除",
        "settings.tags" to "タグ（カンマ区切り）", "settings.model_inherit" to "モデル（空欄でプロバイダーの既定値を使用）",
        "settings.select_model" to "モデルを選択", "settings.system_prompt_inherit" to "システムプロンプト（空欄でプロバイダーの既定値を使用）",
        "settings.apply_preset" to "プリセットを適用", "settings.add_provider" to "プロバイダーを追加",
        "settings.provider_name" to "プロバイダー名", "settings.delete_provider" to "プロバイダーを削除",
        "settings.base_url" to "ベース URL", "settings.hide_api_key" to "API キーを隠す",
        "settings.show_api_key" to "API キーを表示", "settings.model" to "モデル",
        "settings.select_discovered_model" to "検出されたモデルを選択", "settings.test_and_fetch_models" to "接続テストとモデル取得",
        "settings.provider_saved" to "プロバイダー設定を保存しました", "settings.save_provider" to "プロバイダーを保存",
        "settings.back_to_chat" to "チャットに戻る", "settings.reset_confirmation_title" to "すべてのデータをリセットしますか？",
        "settings.reset_confirmation_description" to "デスクトップ上のプロバイダー秘密情報、アシスタント、設定、すべての会話を完全に削除します。",
        "settings.confirm_reset" to "データをリセット", "common.cancel" to "キャンセル",
        "common.save" to "保存", "common.submit" to "送信",
        "common.expand" to "展開 ", "common.collapse" to "折りたたむ ",
        "message.thinking" to "考え中...", "message.translation" to "翻訳",
        "attachment.audio" to "音声", "timeline.execution" to "実行",
        "timeline.expand_execution" to "実行を展開", "timeline.collapse_execution" to "実行を折りたたむ",
        "timeline.expand_steps" to "%d ステップを展開", "timeline.reasoning" to "推論",
        "timeline.reasoning_duration" to "%s 秒間推論", "timeline.today" to "今日",
        "timeline.yesterday" to "昨日", "timeline.day_before_yesterday" to "一昨日",
        "timeline.days_ago" to "%d 日前", "sidebar.recent" to "最近",
        "sidebar.most_active" to "よく使う", "sidebar.sort_recent" to "最近の活動順",
        "sidebar.sort_most_active" to "使用頻度順", "sidebar.tool_call" to "ツール呼び出し",
        "sidebar.rename_folder" to "フォルダー名を変更", "common.new" to "新規",
        "conversation.branch" to "会話ブランチ", "conversation.pinned" to "固定済み",
        "conversation.pin" to "固定", "conversation.unpin" to "固定を解除",
        "conversation.move_to_chat" to "チャットに移動", "conversation.move_to_folder" to "%s に移動",
        "dialog.rename_conversation" to "会話名を変更", "dialog.conversation_system_prompt" to "会話システムプロンプト",
        "dialog.compress_history" to "会話履歴を圧縮", "dialog.compress_history_description" to "以前のメッセージを要約し、最近のメッセージを保持します。全履歴は復元可能なスナップショットとして保存されます。",
        "dialog.target_tokens" to "目標トークン数", "dialog.keep_recent_messages" to "最近のメッセージを保持（全 %d 件）",
        "dialog.additional_instructions" to "追加指示（任意）", "dialog.compress" to "圧縮",
        "dialog.translate_message" to "メッセージを翻訳", "dialog.target_language" to "翻訳先の言語",
        "stats.messages" to "メッセージ", "stats.attachments" to "添付",
        "stats.characters" to "テキストと推論の文字数", "stats.created_at" to "作成日時",
        "stats.updated_at" to "更新日時", "file.add_attachments" to "添付を追加",
        "file.parent_directory" to "親ディレクトリ", "file.selected" to "選択済み",
        "file.add_count" to "追加 (%d)", "file.file_name" to "ファイル名",
                                      "file.export_conversation_markdown" to "会話を Markdown でエクスポート",
                                      "file.export_backup" to "RikkaHub バックアップをエクスポート",
                                      "agent.approval_request" to "エージェントがこの操作を要求しています。許可しますか？",
                                      "agent.docker_network_warning" to "制限付き Docker コンテナで一時的にホストネットワークを使用し、その後オフラインの隔離コンテナに戻ります。",
                                      "agent.docker_warning" to "選択したワークスペースのみをマウントした制限付き Docker コンテナで実行されます。",
                                      "agent.local_shell_warning" to "ローカルシェルは現在のユーザー権限で実行されます。コマンドと影響を確認してください。",
                                      "agent.confirm_impact" to "コマンドとその影響を確認してください。",
                                      "agent.image_pull_warning" to "イメージレジストリからローカル Docker キャッシュにコンテンツをダウンロードします。",
                                      "agent.skill_warning" to "スキルの指示は後のエージェントの動作に影響を与える可能性があります。",
                                      "agent.write_warning" to "ファイル変更は選択したワークスペースディレクトリに限定されます。",
                                      "agent.remember_docker_shell" to "この会話でこのワークスペースの Docker コマンドを自動承認",
                                      "agent.remember_docker_network" to "この会話でこのワークスペースの Docker ネットワークコマンドを自動承認",
                                      "agent.remember_image_pull" to "この会話でこのイメージのダウンロードを自動承認",
                                      "agent.remember_operation" to "この会話でこの種類の操作を自動承認",
                                      "agent.allow" to "許可", "agent.deny" to "拒否",
                                      "settings.navigation" to "設定カテゴリ", "settings.section.general" to "一般",
                                      "settings.section.messages" to "メッセージ表示", "settings.section.interaction" to "操作",
                                      "settings.section.data" to "データ、バックアップ、Web 検索",
                                      "settings.section.assistants" to "アシスタント", "settings.section.providers" to "モデルとサービス",
                                      "composer.placeholder" to "RikkaHub にメッセージ", "model_picker.title" to "モデルを選択",
                                      "model_picker.filter" to "モデルを絞り込む", "model_picker.reasoning" to "推論の強さ",
                                      "model_picker.default" to "デフォルト", "model_picker.low" to "低", "model_picker.medium" to "中", "model_picker.high" to "高",
                                      "model_picker.manage_providers" to "プロバイダーを管理", "model_picker.checking_balance" to "残高を確認中",
                                      "model_picker.balance" to "残高: %s", "model_picker.balance_failed" to "残高を取得できません",
                                      "mcp.manage" to "MCP サービスを管理", "mcp.check" to "接続を確認",
                                      "mcp.title" to "MCP サービス", "mcp.services_for_assistant" to "現在のアシスタントで %d サービス",
                                      "mcp.check_all" to "すべて確認", "mcp.open_settings" to "MCP 設定を開く",
                                      "mcp.no_servers" to "MCP サービスが設定されていません", "mcp.not_checked" to "未確認",
                                      "mcp.checking" to "確認中", "mcp.tools_synced" to "%d 個のツールを同期済み",
                                      "mcp.available_tools" to "利用可能 · %d 個のツール", "mcp.current_assistant" to "このアシスタント",
                                      "mcp.enabled" to "有効", "mcp.available" to "利用可能", "mcp.unavailable" to "利用不可",
                                      "mcp_settings.title" to "MCP サーバー", "mcp_settings.description" to "リモートツールを同期し、このアシスタントに必要なサーバーを有効にします",
                                      "mcp_settings.add_server" to "MCP サーバーを追加", "mcp_settings.unnamed_server" to "名前のない MCP サーバー",
                                      "mcp_settings.delete_server" to "MCP サーバーを削除", "mcp_settings.server_name" to "サーバー名",
                                      "mcp_settings.server_name_help" to "英数字のみ。安定したツール名を作成するために使用",
                                      "mcp_settings.command" to "コマンド", "mcp_settings.arguments" to "コマンド引数",
                                      "mcp_settings.arguments_help" to "1 行に 1 つの引数", "mcp_settings.environment" to "環境変数",
                                      "mcp_settings.environment_help" to "1 行に KEY=VALUE ペア", "mcp_settings.server_url" to "サーバー URL",
                                      "mcp_settings.enable_server" to "サーバーを有効化", "mcp_settings.enable_server_help" to "オフの場合、ツールはモデルに公開されません",
                                      "mcp_settings.sync_failed" to "MCP ツールの同期に失敗", "mcp_settings.sync_tools" to "ツールを同期",
                                      "mcp_settings.collapse_tools" to "ツールを折りたたむ", "mcp_settings.manage_tools" to "%d ツールを管理 (%e 有効)",
                                      "mcp_settings.tool" to "MCP ツール", "assistant.message_template" to "メッセージテンプレート",
                                      "assistant.template_variables" to "変数: {{ message }}, {{ role }}, {{ date }}, {{ time }}",
                                      "assistant.template_invalid" to "有効な Pebble テンプレートには {{ message }} が必要です",
                                      "assistant.conversation_system_prompt" to "会話システムプロンプト",
                                      "assistant.conversation_system_prompt_help" to "個別の会話がこのアシスタントのシステムプロンプトを上書きできるようにします",
                                      "assistant.conversation_lorebooks" to "会話ロアブック",
                                      "assistant.conversation_lorebooks_help" to "個別の会話がこのアシスタントのプロンプト注入を有効/無効にできるようにします",
                                      "assistant.web_search" to "ウェブ検索",
                                      "assistant.web_search_help" to "新しい会話でデフォルトで OpenAI 互換のウェブ検索を有効にします",
                                      "assistant.local_time_tool" to "ローカル時刻ツール",
                                      "assistant.local_time_tool_help" to "モデルが必要に応じてデバイスのローカル時刻とタイムゾーンを読み取ることを許可",
                                      "assistant.ask_user_tool" to "ユーザーに質問",
                                      "assistant.ask_user_tool_help" to "モデルが必要に応じて確認や説明を求めることを許可",
                                      "assistant.max_tool_rounds" to "返信あたりの最大ツール呼び出しラウンド",
                                      "assistant.max_tool_rounds_help" to "0 は無制限。デフォルトは 8",
                                      "assistant.agent_workspace" to "エージェントワークスペース",
                                      "assistant.agent_workspace_help" to "選択したディレクトリでファイルの読み書き、コマンド実行、有効なスキルの読み込みを許可",
                                      "assistant.workspace_directory" to "ワークスペースディレクトリ",
                                      "assistant.workspace_directory_help" to "エージェントファイルツールのみがこのディレクトリにアクセス可能。ローカルシェルは毎回確認が必要",
                                      "assistant.docker_container" to "Docker コンテナ", "assistant.local_shell" to "ローカルシェル",
                                      "assistant.docker_image" to "Docker イメージ",
                                      "assistant.docker_image_help" to "デフォルトでオフライン、非特権、ワークスペースのみマウント。初回プルは承認が必要",
                                      "assistant.enabled_skills" to "有効なスキル",
                                      "assistant.enabled_skills_help" to "カンマ区切り。~/.config/rikkahub/skills/<name>/SKILL.md に配置",
                                      "assistant.stream_output" to "ストリーム出力",
                                      "assistant.stream_output_help" to "完全な応答を待つ代わりに、到着次第応答内容を表示",
                                      "assistant.memory" to "メモリー",
                                      "assistant.memory_help" to "モデルが会話をまたいで長期的な情報を記録、更新、使用できるようにする",
                                      "assistant.global_memory" to "グローバル共有メモリー",
                                      "assistant.global_memory_help" to "グローバルメモリーを使用している他のアシスタントとメモリーストアを共有",
                                      "assistant.add_global_memory" to "グローバルメモリーを追加",
                                      "assistant.delete_global_memory" to "グローバルメモリーを削除",
                                      "assistant.shared_memory_content" to "共有する事実または好み",
                                      "assistant.memory_entries" to "メモリー項目",
                                      "assistant.add_memory" to "メモリーを追加",
                                      "assistant.delete_memory" to "メモリーを削除",
                                      "assistant.memory_content" to "事実または好み",
                                      "assistant.temperature" to "温度",
                                      "assistant.inherit_provider" to "空欄でプロバイダー設定を継承",
                                      "assistant.max_output_tokens" to "最大出力トークン",
                                      "assistant.context_messages" to "コンテキストメッセージ数",
                                      "assistant.keep_all_when_empty" to "空欄の場合はすべて保持"
                                      ,"common.add" to "追加",
                                      "role.system" to "システム", "role.user" to "ユーザー", "role.assistant" to "アシスタント",
                                      "assistant.preset_messages" to "プリセットメッセージ",
                                      "assistant.preset_messages_help" to "すべての新しい会話にサンプルメッセージを追加",
                                      "assistant.message" to "メッセージ",
                                      "assistant.delete_preset_message" to "プリセットメッセージを削除",
                                      "assistant.quick_messages" to "クイックメッセージ",
                                      "assistant.quick_messages_help" to "チャット作成から再利用可能なプロンプトを挿入",
                                      "assistant.title" to "タイトル", "assistant.content" to "内容",
                                      "assistant.delete_quick_message" to "クイックメッセージを削除",
                                      "assistant.regex_transforms" to "正規表現変換",
                                      "assistant.regex_transforms_help" to "ユーザー入力、アシスタント出力、または表示テキストを変換",
                                      "assistant.rule_name" to "ルール名",
                                      "assistant.delete_regex_rule" to "正規表現ルールを削除",
                                      "assistant.find_regex" to "検索正規表現",
                                      "assistant.replace_with" to "置換後",
                                      "assistant.visual_only" to "表示のみ",
                                      "assistant.prompt_injections" to "プロンプト注入 / ロアブック",
                                      "assistant.prompt_injections_help" to "キーワードでコンテキストを一致させるか、注入を常にアクティブに保つ",
                                      "assistant.entry_name" to "項目名",
                                      "assistant.delete_injection" to "注入エントリを削除",
                                      "assistant.injection_content" to "注入内容",
                                      "assistant.keywords" to "キーワード（カンマ区切り）",
                                      "assistant.keywords_help" to "空の場合は常にアクティブを有効に",
                                      "assistant.priority" to "優先度",
                                      "assistant.priority_help" to "値が大きいほど前方に配置",
                                      "assistant.scan_depth" to "スキャンするメッセージ数",
                                      "assistant.scan_depth_help" to "キーワード一致に使用",
                                      "assistant.injection_depth" to "注入深度",
                                      "assistant.injection_depth_help" to "末尾から数える",
                                      "assistant.injection_role" to "注入ロール",
                                      "assistant.before_system" to "システム前", "assistant.after_system" to "システム後",
                                      "assistant.top_of_chat" to "チャット先頭", "assistant.bottom_of_chat" to "チャット末尾",
                                      "assistant.at_depth" to "指定深度", "assistant.always_active" to "常に有効",
                                      "assistant.regex_keywords" to "正規表現キーワード",
                                      "assistant.case_sensitive" to "大文字小文字を区別",
                                      "assistant.saved" to "アシスタント設定を保存しました",
                                      "assistant.save" to "アシスタントを保存"
                                      ,"provider.title_model" to "タイトルモデル",
                                      "provider.title_model_help" to "空欄の場合はチャットモデルを使用",
                                      "provider.title_prompt" to "タイトルプロンプト",
                                      "provider.title_prompt_help" to "{locale} と {content} プレースホルダーをサポート",
                                      "provider.token_usage" to "トークン使用量",
                                      "provider.token_usage_help" to "互換性のあるストリーミング API から入出力トークン数をリクエスト",
                                      "provider.use_provider_default" to "空欄でプロバイダーの既定値を使用",
                                      "provider.system_prompt" to "システムプロンプト",
                                      "provider.balance_query" to "残高照会",
                                      "provider.balance_query_help" to "プロバイダー API を通じてアカウントの残高またはクォータを照会",
                                      "provider.balance_api_path" to "残高 API パス",
                                      "provider.balance_api_path_help" to "相対パスまたは完全な URL を入力",
                                      "provider.balance_result_path" to "結果 JSON パス",
                                      "provider.balance_result_path_help" to "例: data.balance や data.items[0].amount",
                                      "provider.checking_balance" to "残高を確認中...",
                                      "provider.current_balance" to "現在の残高: %s",
                                      "provider.balance_failed" to "残高照会に失敗しました: %s",
                                      "provider.check_balance" to "残高を確認",
                                      "request_overrides.headers" to "カスタムヘッダー",
                                      "request_overrides.headers_help" to "チャットとモデルリクエストに追加",
                                      "request_overrides.add_header" to "カスタムヘッダーを追加",
                                      "request_overrides.header" to "ヘッダー", "request_overrides.value" to "値",
                                      "request_overrides.delete_header" to "カスタムヘッダーを削除",
                                      "request_overrides.body" to "カスタムリクエスト本文",
                                      "request_overrides.body_help" to "JSON をリクエストのトップレベルフィールドにマージ",
                                      "request_overrides.add_body" to "カスタムリクエスト本文を追加",
                                      "request_overrides.key" to "キー", "request_overrides.json_value" to "JSON 値",
                                      "request_overrides.invalid_json" to "有効な JSON を入力してください",
                                      "request_overrides.delete_body" to "カスタムリクエスト本文を削除"
                                      ,"chat.restore_snapshot" to "履歴スナップショットを復元 %d: %s",
                                      "chat.snapshot_messages" to "%d メッセージ",
                                      "chat.delete_snapshot" to "履歴スナップショットを削除",
                                      "jumper.top" to "先頭へ移動", "jumper.previous" to "前のメッセージ",
                                      "jumper.next" to "次のメッセージ", "jumper.bottom" to "末尾へ移動",
                                      "tool.calling" to "呼び出し中", "tool.completed" to "完了",
                                      "tool.input" to "入力", "tool.output" to "出力", "tool.result" to "ツール結果",
                                      "tool.answer_required" to "あなたの回答が必要です",
                                      "tool.web_search" to "ウェブを検索", "tool.current_time" to "現在時刻を取得",
                                      "tool.memory" to "メモリーを管理", "tool.list_files" to "ファイル一覧",
                                      "tool.search_files" to "ファイルを検索", "tool.read_file" to "ファイルを読む",
                                      "tool.write_file" to "ファイルを書く", "tool.edit_file" to "ファイルを編集",
                                      "tool.run_command" to "コマンドを実行", "tool.use_skill" to "スキルを使用"
                                      ,"model_picker.refresh_balance" to "%s の残高を更新",
                                      "model_picker.current_model" to "現在のモデル",
                                      "model_capability.text" to "テキスト", "model_capability.vision" to "画像",
                                      "model_capability.reasoning" to "推論", "model_capability.tools" to "ツール",
                                      "attachment.remove" to "添付を削除", "mcp.unnamed_service" to "名前のない MCP サービス",
                                      "language.chinese" to "中国語", "user.you" to "あなた",
                                      "message.user_avatar" to "ユーザーアバター", "common.unnamed" to "名前なし",
                                      "theme.sakura" to "さくら", "theme.ocean" to "海", "theme.forest" to "森",
                                      "theme.sunset" to "夕日", "theme.lavender" to "ラベンダー", "theme.slate" to "スレート",
                                      "font.system" to "システム既定", "font.sans_serif" to "ゴシック",
                                      "font.serif" to "明朝", "font.monospace" to "等幅"
                                      ,"runtime.unknown_error" to "不明なエラー",
                                      "runtime.save_failed" to "保存に失敗: %s",
                                      "runtime.title_empty" to "タイトルモデルがコンテンツを返しませんでした",
                                      "runtime.title_failed" to "タイトルの生成に失敗しました",
                                      "runtime.suggestions_empty" to "提案モデルがコンテンツを返しませんでした",
                                      "runtime.suggestions_failed" to "返信候補の生成に失敗しました",
                                      "runtime.mcp_configuration_invalid" to "MCP 設定が無効です。アシスタント設定でサーバーを選び直してください",
                                      "runtime.mcp_no_tools" to "MCP サーバー %s は使用可能なツールを提供しませんでした",
                                      "runtime.mcp_sync_failed" to "MCP ツールの同期に失敗: %s",
                                      "runtime.invalid_message_template" to "無効なメッセージテンプレート",
                                      "runtime.request_failed" to "リクエストに失敗しました",
                                      "runtime.not_enough_messages" to "圧縮するのに十分なメッセージがありません",
                                      "runtime.compression_empty" to "圧縮モデルがサマリーを返しませんでした",
                                      "runtime.compression_failed" to "会話の圧縮に失敗しました",
                                      "runtime.translation_empty" to "翻訳モデルがコンテンツを返しませんでした",
                                      "runtime.translation_failed" to "翻訳に失敗しました",
                                      "runtime.export_failed" to "エクスポートに失敗: %s",
                                      "runtime.import_failed" to "インポートに失敗: %s"
                                      ,"runtime.tool_round_limit" to "この返信は %d ラウンドのツール呼び出し制限に達しました。新しいメッセージを送って再開してください。",
                                      "runtime.add_attachment_failed" to "添付の追加に失敗しました"
                                      ,"defaults.new_provider" to "新しいプロバイダー",
                                      "defaults.new_assistant" to "新しいアシスタント",
                                      "file.import_backup" to "RikkaHub バックアップをインポート",
                                      "file.imported_backup" to "%s からバックアップをインポートしました",
                                      "file.choose_attachments" to "画像、音声、テキスト、または文書を追加",
                                      "mermaid.diagram" to "図",
                                      "mermaid.code" to "コード",
                                      "mermaid.save_image" to "画像を保存",
                                      "mermaid.download" to "ダウンロード",
                                      "mermaid.fullscreen" to "全画面",
                                      "mermaid.exit_fullscreen" to "全画面を終了"
                                      ,"provider.connection_success" to "接続済み · %d モデル利用可能"
)
