package me.rerere.rikkahub.desktop

internal val FrenchDesktopTranslations = mapOf(
    "settings.language" to "Langue",
    "settings.language_description" to "Choisissez la langue de l'application de bureau",
    "settings.title" to "Paramètres",
    "settings.subtitle" to "Apparence, interaction et modèles",
    "settings.back" to "Retour",
    "settings.color_mode" to "Mode de couleur",
    "settings.color_mode_description" to "Suivre le système, ou utiliser un thème clair ou sombre fixe",
    "settings.system" to "Système",
    "settings.light" to "Clair",
    "settings.dark" to "Sombre",
    "settings.theme_color" to "Couleur du thème",
    "settings.theme_color_description" to "Choisissez une couleur d'accent et des tons assortis pour l'interface",
    "settings.font" to "Police de l'interface",
    "settings.font_description" to "%s ; les blocs de code restent à chasse fixe",
    "settings.chat_font_size" to "Taille de police du chat",
    "sidebar.welcome" to "Bon retour",
    "sidebar.new_chat" to "Nouveau chat",
    "sidebar.search_chats" to "Rechercher des chats",
    "sidebar.back_to_chats" to "Retour aux chats",
    "sidebar.favorite_messages" to "Messages favoris",
    "sidebar.search" to "Rechercher",
    "sidebar.all_assistants" to "Tous les assistants",
    "sidebar.all_tags" to "Toutes les étiquettes",
    "sidebar.chats" to "Chats",
    "chat.open_conversations" to "Ouvrir les conversations",
    "chat.options" to "Options de conversation",
    "chat.rename" to "Renommer",
    "chat.export_markdown" to "Exporter en Markdown",
    "chat.generate_title" to "Générer le titre",
    "chat.statistics" to "Statistiques de la conversation",
    "chat.generate_suggestions" to "Générer des suggestions de réponse",
    "chat.compress_history" to "Compresser l'historique",
    "chat.set_system_prompt" to "Définir l'invite système",
    "chat.edit_system_prompt" to "Modifier l'invite système",
    "chat.enable_lorebooks" to "Activer les lorebooks de la conversation",
    "chat.disable_lorebooks" to "Désactiver les lorebooks de la conversation",
    "chat.move_to_folder" to "Déplacer vers le dossier",
    "chat.uncategorized" to "Sans catégorie",
    "chat.new_folder" to "Nouveau dossier",
    "chat.close" to "Fermer",
    "message.sources" to "Sources",
    "message.source_number" to "Source %d",
    "message.input_tokens" to "Jetons d'entrée",
    "message.output_tokens" to "Jetons de sortie",
    "message.cached_tokens" to "Jetons en cache",
    "message.previous_version" to "Version précédente",
    "message.next_version" to "Version suivante",
    "message.copy" to "Copier",
    "message.fork" to "Fork à partir d'ici",
    "message.regenerate" to "Régénérer",
    "message.translate" to "Traduire",
    "message.favorite" to "Ajouter aux favoris",
    "message.unfavorite" to "Retirer des favoris",
    "message.edit" to "Modifier",
    "message.delete" to "Supprimer",
    "empty_chat.greeting" to "Comment puis-je vous aider ?",
    "composer.collapse" to "Réduire l'éditeur",
    "composer.expand" to "Développer l'éditeur",
    "composer.add_attachment" to "Ajouter une pièce jointe",
    "composer.enable_web_search" to "Activer la recherche web",
    "composer.disable_web_search" to "Désactiver la recherche web",
    "composer.quick_messages" to "Messages rapides",
    "composer.manage_assistants" to "Gérer les assistants et les étiquettes",
    "composer.stop_generation" to "Arrêter la génération",
    "composer.send" to "Envoyer ; maintenez pour ajouter sans réponse",
    "settings.show_user_avatar" to "Afficher l'avatar utilisateur",
    "settings.show_user_avatar_description" to "Afficher un avatar à côté des messages de l'utilisateur",
    "settings.user_nickname" to "Surnom de l'utilisateur",
    "settings.user_nickname_description" to "Affiché à côté des messages de l'utilisateur ; par défaut « Vous » si vide",
    "settings.user_nickname_placeholder" to "Vous",
    "settings.show_model_icon" to "Afficher l'icône du modèle",
    "settings.show_model_icon_description" to "Afficher l'icône du modèle à côté des messages de l'assistant",
    "settings.show_model_name" to "Afficher le nom du modèle",
    "settings.show_model_name_description" to "Afficher le nom du modèle au-dessus des messages de l'assistant",
    "settings.assistant_bubble" to "Bulle de l'assistant",
    "settings.assistant_bubble_description" to "Afficher le texte de l'assistant dans une bulle remplie",
    "settings.message_timestamp" to "Heure du message",
    "settings.message_timestamp_description" to "Afficher l'heure de création dans l'en-tête de chaque message",
    "settings.reasoning" to "Contenu du raisonnement",
    "settings.reasoning_description" to "Afficher le raisonnement renvoyé par les modèles compatibles",
    "settings.collapse_reasoning" to "Réduire le raisonnement après la fin",
    "settings.collapse_reasoning_description" to "Développer le raisonnement uniquement pendant la génération d'une réponse",
    "settings.code_wrap" to "Retour à la ligne dans les blocs de code",
    "settings.code_wrap_description" to "Passer à la ligne automatiquement pour les longues lignes de code au lieu du défilement horizontal",
    "settings.chinese_typography" to "Typographie chinoise",
    "settings.chinese_typography_description" to "Ajouter un espacement entre le texte chinois et latin, les nombres ou les symboles",
    "settings.mermaid_rendering" to "Afficher les diagrammes Mermaid",
    "settings.mermaid_rendering_description" to "Afficher les blocs de code Mermaid sous forme de diagrammes interactifs",
    "settings.mermaid_cli" to "Autoriser Mermaid CLI",
    "settings.mermaid_cli_description" to "Autoriser Mermaid CLI à s'exécuter localement pour afficher les diagrammes",
    "settings.mermaid_cli_path" to "Chemin de Mermaid CLI",
    "settings.mermaid_cli_path_description" to "Laissez vide pour détecter automatiquement PATH, npm global et les emplacements locaux de l'utilisateur",
    "settings.mermaid_system_browser" to "Utiliser le navigateur système",
    "settings.mermaid_system_browser_description" to "Autoriser Mermaid CLI à utiliser un navigateur basé sur Chromium installé",
    "settings.send_on_enter" to "Envoyer avec Entrée",
    "settings.send_on_enter_description" to "Lorsque désactivé, Ctrl+Entrée envoie et Entrée ajoute une nouvelle ligne",
    "settings.auto_scroll" to "Défilement automatique",
    "settings.auto_scroll_description" to "Suivre le nouveau contenu de raisonnement et de réponse pendant la génération",
    "settings.smooth_scroll" to "Défilement fluide",
    "settings.smooth_scroll_description" to "Animer le défilement à la molette dans la discussion",
    "settings.message_navigation" to "Navigation des messages",
    "settings.message_navigation_description" to "Afficher les boutons pour le haut, le précédent, le suivant et le bas après avoir fait défiler",
    "settings.message_navigation_left" to "Navigation des messages à gauche",
    "settings.message_navigation_left_description" to "Affiché par défaut sur le côté droit de la zone de messages",
    "settings.export_backup" to "Exporter la sauvegarde",
    "settings.export_backup_description" to "Enregistrer les fournisseurs, assistants, préférences et chats en JSON",
    "settings.export" to "Exporter",
    "settings.import_backup" to "Importer une sauvegarde",
    "settings.import_backup_description" to "Remplacer les données actuelles du bureau par une sauvegarde RikkaHub",
    "settings.import" to "Importer",
    "settings.reset_data" to "Réinitialiser toutes les données",
    "settings.reset_data_description" to "Supprimer les fournisseurs locaux, assistants, préférences et chats. Cette action est irréversible.",
    "settings.reset" to "Réinitialiser",
    "settings.web_search" to "Service de recherche web",
    "settings.web_search_description" to "Utiliser un service de recherche externe lorsqu'il est configuré ; sinon, utiliser la recherche native du fournisseur de modèle",
    "settings.searxng_url" to "URL SearXNG",
    "settings.api_key" to "Clé API",
    "settings.search_result_count" to "%d résultats par recherche",
    "settings.test_search" to "Tester la recherche",
    "settings.search_test_success" to "La connexion de recherche web fonctionne",
    "settings.search_test_failed" to "Échec du test de recherche",
    "settings.add_assistant" to "Ajouter un assistant",
    "settings.assistant_name" to "Nom de l'assistant",
    "settings.copy_assistant" to "Copier l'assistant",
    "settings.delete_assistant" to "Supprimer l'assistant",
    "settings.tags" to "Étiquettes (séparées par des virgules)",
    "settings.model_inherit" to "Modèle (laissez vide pour utiliser celui du fournisseur)",
    "settings.select_model" to "Choisir un modèle",
    "settings.system_prompt_inherit" to "Invite système (laissez vide pour utiliser celle du fournisseur)",
    "settings.apply_preset" to "Appliquer le préréglage",
    "settings.add_provider" to "Ajouter un fournisseur",
    "settings.provider_name" to "Nom du fournisseur",
    "settings.delete_provider" to "Supprimer le fournisseur",
    "settings.base_url" to "URL de base",
    "settings.hide_api_key" to "Masquer la clé API",
    "settings.show_api_key" to "Afficher la clé API",
    "settings.model" to "Modèle",
    "settings.select_discovered_model" to "Sélectionner le modèle découvert",
    "settings.test_and_fetch_models" to "Tester et récupérer les modèles",
    "settings.provider_saved" to "Paramètres du fournisseur enregistrés",
    "settings.save_provider" to "Enregistrer le fournisseur",
    "settings.back_to_chat" to "Retour au chat",
    "settings.unsaved_changes_title" to "Enregistrer les modifications ?",
    "settings.unsaved_changes_description" to "Les paramètres ont été modifiés. Les enregistrer avant de quitter ?",
    "settings.discard_changes" to "Ne pas enregistrer",
    "settings.reset_confirmation_title" to "Réinitialiser toutes les données ?",
    "settings.reset_confirmation_description" to "Cela supprime définitivement les secrets du fournisseur de bureau, les assistants, les paramètres et toutes les conversations.",
    "settings.confirm_reset" to "Réinitialiser les données",
    "common.cancel" to "Annuler",
    "common.save" to "Enregistrer",
    "common.submit" to "Envoyer",
    "common.expand" to "Développer ",
    "common.collapse" to "Réduire ",
    "message.thinking" to "Réflexion en cours...",
    "message.translation" to "Traduction",
    "attachment.audio" to "Audio",
    "timeline.execution" to "Exécution",
    "timeline.expand_execution" to "Développer l'exécution",
    "timeline.collapse_execution" to "Réduire l'exécution",
    "timeline.expand_steps" to "Développer %d étapes",
    "timeline.reasoning" to "Raisonnement",
    "timeline.reasoning_duration" to "A raisonné pendant %s secondes",
    "timeline.today" to "Aujourd'hui",
    "timeline.yesterday" to "Hier",
    "timeline.day_before_yesterday" to "Avant-hier",
    "timeline.days_ago" to "Il y a %d jours",
    "sidebar.recent" to "Récents",
    "sidebar.most_active" to "Les plus actifs",
    "sidebar.sort_recent" to "Trier par activité récente",
    "sidebar.sort_most_active" to "Trier par fréquence d'utilisation",
    "sidebar.tool_call" to "Appel d'outil",
    "sidebar.rename_folder" to "Renommer le dossier",
    "common.new" to "Nouveau",
    "conversation.branch" to "Branche de conversation",
    "conversation.pinned" to "Épinglé",
    "conversation.pin" to "Épingler",
    "conversation.unpin" to "Désépingler",
    "conversation.move_to_chat" to "Déplacer vers les chats",
    "conversation.move_to_folder" to "Déplacer vers %s",
    "dialog.rename_conversation" to "Renommer la conversation",
    "dialog.conversation_system_prompt" to "Invite système de la conversation",
    "dialog.compress_history" to "Compresser l'historique de la conversation",
    "dialog.compress_history_description" to "Résumer les messages antérieurs et conserver les messages récents. L'historique complet est sauvegardé en tant qu'instantané restaurable.",
    "dialog.target_tokens" to "Jetons cibles",
    "dialog.keep_recent_messages" to "Conserver les messages récents (sur %d au total)",
    "dialog.additional_instructions" to "Instructions supplémentaires (facultatif)",
    "dialog.compress" to "Compresser",
    "dialog.translate_message" to "Traduire le message",
    "dialog.target_language" to "Langue cible",
    "stats.messages" to "Messages",
    "stats.attachments" to "Pièces jointes",
    "stats.characters" to "Caractères de texte et de raisonnement",
    "stats.created_at" to "Créé",
    "stats.updated_at" to "Mis à jour",
    "file.add_attachments" to "Ajouter des pièces jointes",
    "file.parent_directory" to "Répertoire parent",
    "file.selected" to "Sélectionné",
    "file.add_count" to "Ajouter (%d)",
    "file.file_name" to "Nom de fichier",
    "file.export_conversation_markdown" to "Exporter la conversation en Markdown",
    "file.export_backup" to "Exporter la sauvegarde RikkaHub",
    "agent.approval_request" to "L'agent demande cette opération. L'autoriser ?",
    "agent.docker_network_warning" to "S'exécute dans un conteneur Docker restreint avec réseau hôte temporaire, puis retourne dans un conteneur isolé hors ligne.",
    "agent.docker_warning" to "S'exécute dans un conteneur Docker restreint qui monte uniquement l'espace de travail sélectionné.",
    "agent.local_shell_warning" to "Le shell local s'exécute avec les autorisations de votre utilisateur actuel. Confirmez la commande et son impact.",
    "agent.confirm_impact" to "Confirmez la commande et son impact.",
    "agent.image_pull_warning" to "Télécharge le contenu d'un registre d'images dans le cache Docker local.",
    "agent.skill_warning" to "Les instructions de compétence peuvent affecter le comportement ultérieur de l'agent.",
    "agent.write_warning" to "Les modifications de fichiers sont limitées au répertoire de l'espace de travail sélectionné.",
    "agent.remember_docker_shell" to "Approuver automatiquement les commandes Docker pour cet espace de travail dans cette conversation",
    "agent.remember_docker_network" to "Approuver automatiquement les commandes réseau Docker pour cet espace de travail dans cette conversation",
    "agent.remember_image_pull" to "Approuver automatiquement ce téléchargement d'image dans cette conversation",
    "agent.remember_operation" to "Approuver automatiquement ce type d'opération dans cette conversation",
    "agent.allow" to "Autoriser",
    "agent.deny" to "Refuser",
    "settings.navigation" to "Catégories des paramètres",
    "settings.section.general" to "Général",
    "settings.section.messages" to "Messages",
    "settings.section.interaction" to "Interaction",
    "settings.section.data" to "Données, sauvegardes et recherche web",
    "settings.section.assistants" to "Assistants",
    "settings.section.providers" to "Modèles et services",
    "composer.placeholder" to "Envoyer un message à RikkaHub",
    "model_picker.title" to "Choisir un modèle",
    "model_picker.filter" to "Filtrer les modèles",
    "model_picker.reasoning" to "Niveau de raisonnement",
    "model_picker.default" to "Par défaut",
    "model_picker.low" to "Faible",
    "model_picker.medium" to "Moyen",
    "model_picker.high" to "Élevé",
    "model_picker.manage_providers" to "Gérer les fournisseurs",
    "model_picker.checking_balance" to "Vérification du solde",
    "model_picker.balance" to "Solde : %s",
    "model_picker.balance_failed" to "Solde indisponible",
    "mcp.manage" to "Gérer les services MCP",
    "mcp.check" to "Vérifier la disponibilité",
    "mcp.title" to "Services MCP",
    "mcp.services_for_assistant" to "%d services pour cet assistant",
    "mcp.check_all" to "Tout vérifier",
    "mcp.open_settings" to "Ouvrir les paramètres MCP",
    "mcp.no_servers" to "Aucun service MCP configuré",
    "mcp.not_checked" to "Non vérifié",
    "mcp.checking" to "Vérification",
    "mcp.tools_synced" to "%d outils synchronisés",
    "mcp.available_tools" to "Disponible · %d outils",
    "mcp.current_assistant" to "Cet assistant",
    "mcp.enabled" to "Activé",
    "mcp.available" to "Disponible",
    "mcp.unavailable" to "Indisponible",
    "mcp_settings.title" to "Serveurs MCP",
    "mcp_settings.description" to "Synchronisez les outils distants, puis activez les serveurs dont cet assistant a besoin",
    "mcp_settings.add_server" to "Ajouter un serveur MCP",
    "mcp_settings.unnamed_server" to "Serveur MCP sans nom",
    "mcp_settings.delete_server" to "Supprimer le serveur MCP",
    "mcp_settings.server_name" to "Nom du serveur",
    "mcp_settings.server_name_help" to "Lettres et chiffres uniquement ; utilisé pour créer des noms d'outils stables",
    "mcp_settings.command" to "Commande",
    "mcp_settings.arguments" to "Arguments de la commande",
    "mcp_settings.arguments_help" to "Un argument par ligne",
    "mcp_settings.environment" to "Variables d'environnement",
    "mcp_settings.environment_help" to "Une paire CLÉ=VALEUR par ligne",
    "mcp_settings.server_url" to "URL du serveur",
    "mcp_settings.enable_server" to "Activer le serveur",
    "mcp_settings.enable_server_help" to "Lorsque désactivé, ses outils ne sont pas exposés au modèle",
    "mcp_settings.sync_failed" to "Échec de la synchronisation des outils MCP",
    "mcp_settings.sync_tools" to "Synchroniser les outils",
    "mcp_settings.collapse_tools" to "Réduire les outils",
    "mcp_settings.manage_tools" to "Gérer %d outils (%e activés)",
    "mcp_settings.tool" to "Outil MCP",
    "assistant.message_template" to "Modèle de message",
    "assistant.template_variables" to "Variables : {{ message }}, {{ role }}, {{ date }}, {{ time }}",
    "assistant.template_invalid" to "Un modèle Pebble valide doit inclure {{ message }}",
    "assistant.conversation_system_prompt" to "Invite système de la conversation",
    "assistant.conversation_system_prompt_help" to "Permettre aux conversations individuelles de remplacer l'invite système de cet assistant",
    "assistant.conversation_lorebooks" to "Lorebooks de la conversation",
    "assistant.conversation_lorebooks_help" to "Permettre aux conversations individuelles d'activer ou de désactiver les injections d'invites de cet assistant",
    "assistant.web_search" to "Recherche web",
    "assistant.web_search_help" to "Activer par défaut la recherche web compatible OpenAI dans les nouvelles conversations",
    "assistant.local_time_tool" to "Outil d'heure locale",
    "assistant.local_time_tool_help" to "Permettre au modèle de lire l'heure locale et le fuseau horaire de cet appareil si nécessaire",
    "assistant.ask_user_tool" to "Demander à l'utilisateur",
    "assistant.ask_user_tool_help" to "Permettre au modèle de vous demander des clarifications ou une confirmation si nécessaire",
    "assistant.max_tool_rounds" to "Nombre maximal de tours d'appels d'outils par réponse",
    "assistant.max_tool_rounds_help" to "0 signifie illimité ; la valeur par défaut est 8",
    "assistant.agent_workspace" to "Espace de travail de l'agent",
    "assistant.agent_workspace_help" to "Permettre au modèle de lire et d'écrire des fichiers, d'exécuter des commandes et de charger des compétences activées dans le répertoire sélectionné",
    "assistant.workspace_directory" to "Répertoire de l'espace de travail",
    "assistant.workspace_directory_help" to "Seuls les outils de fichiers de l'agent peuvent accéder à ce répertoire ; le shell local nécessite toujours une confirmation à chaque fois",
    "assistant.docker_container" to "Conteneur Docker",
    "assistant.local_shell" to "Shell local",
    "assistant.docker_image" to "Image Docker",
    "assistant.docker_image_help" to "Hors ligne, sans privilèges et monte uniquement l'espace de travail par défaut ; le premier téléchargement nécessite une approbation",
    "assistant.enabled_skills" to "Compétences activées",
    "assistant.enabled_skills_help" to "Séparées par des virgules ; stockées dans ~/.config/rikkahub/skills/<nom>/SKILL.md",
    "assistant.stream_output" to "Sortie en flux",
    "assistant.stream_output_help" to "Afficher le contenu de la réponse au fur et à mesure au lieu d'attendre la réponse complète",
    "assistant.memory" to "Mémoire",
    "assistant.memory_help" to "Permettre au modèle d'enregistrer, de mettre à jour et d'utiliser des informations à long terme entre les conversations",
    "assistant.global_memory" to "Mémoire partagée globale",
    "assistant.global_memory_help" to "Partager un magasin de mémoire avec d'autres assistants utilisant la mémoire globale",
    "assistant.add_global_memory" to "Ajouter une mémoire globale",
    "assistant.delete_global_memory" to "Supprimer la mémoire globale",
    "assistant.shared_memory_content" to "Fait ou préférence partagé",
    "assistant.memory_entries" to "Entrées de mémoire",
    "assistant.add_memory" to "Ajouter une mémoire",
    "assistant.delete_memory" to "Supprimer la mémoire",
    "assistant.memory_content" to "Fait ou préférence",
    "assistant.temperature" to "Température",
    "assistant.inherit_provider" to "Laissez vide pour hériter des réglages du fournisseur",
    "assistant.max_output_tokens" to "Maximum de jetons de sortie",
    "assistant.context_messages" to "Messages de contexte",
    "assistant.keep_all_when_empty" to "Laissez vide pour tout conserver",
    "common.add" to "Ajouter",
    "role.system" to "Système",
    "role.user" to "Utilisateur",
    "role.assistant" to "Assistant",
    "assistant.preset_messages" to "Messages prédéfinis",
    "assistant.preset_messages_help" to "Ajouter des messages d'exemple à chaque nouvelle conversation",
    "assistant.message" to "Message",
    "assistant.delete_preset_message" to "Supprimer le message prédéfini",
    "assistant.quick_messages" to "Messages rapides",
    "assistant.quick_messages_help" to "Insérer des invites réutilisables depuis l'éditeur de chat",
    "assistant.title" to "Titre",
    "assistant.content" to "Contenu",
    "assistant.delete_quick_message" to "Supprimer le message rapide",
    "assistant.regex_transforms" to "Transformations regex",
    "assistant.regex_transforms_help" to "Transformer l'entrée utilisateur, la sortie de l'assistant ou le texte affiché",
    "assistant.rule_name" to "Nom de règle",
    "assistant.delete_regex_rule" to "Supprimer la règle regex",
    "assistant.find_regex" to "Regex de recherche",
    "assistant.replace_with" to "Remplacer par",
    "assistant.visual_only" to "Visuel uniquement",
    "assistant.prompt_injections" to "Injections de prompt / lorebooks",
    "assistant.prompt_injections_help" to "Faire correspondre le contexte par mot-clé, ou garder une injection toujours active",
    "assistant.entry_name" to "Nom de l'entrée",
    "assistant.delete_injection" to "Supprimer l'entrée d'injection",
    "assistant.injection_content" to "Contenu de l'injection",
    "assistant.keywords" to "Mots-clés (séparés par des virgules)",
    "assistant.keywords_help" to "Si vide, activez « toujours actif »",
    "assistant.priority" to "Priorité",
    "assistant.priority_help" to "Plus la valeur est élevée, plus tôt elle est placée",
    "assistant.scan_depth" to "Messages à analyser",
    "assistant.scan_depth_help" to "Utilisé pour la correspondance des mots-clés",
    "assistant.injection_depth" to "Profondeur d'injection",
    "assistant.injection_depth_help" to "Compter à partir de la fin",
    "assistant.injection_role" to "Rôle d'injection",
    "assistant.before_system" to "Avant l'invite système",
    "assistant.after_system" to "Après l'invite système",
    "assistant.top_of_chat" to "Haut du chat",
    "assistant.bottom_of_chat" to "Bas du chat",
    "assistant.at_depth" to "À la profondeur",
    "assistant.always_active" to "Toujours actif",
    "assistant.regex_keywords" to "Mots-clés regex",
    "assistant.case_sensitive" to "Sensible à la casse",
    "assistant.saved" to "Paramètres de l'assistant enregistrés",
    "assistant.save" to "Enregistrer l'assistant",
    "provider.title_model" to "Modèle de titre",
    "provider.title_model_help" to "Laissez vide pour utiliser le modèle de chat",
    "provider.title_prompt" to "Invite de titre",
    "provider.title_prompt_help" to "Prend en charge les espaces réservés {locale} et {content}",
    "provider.token_usage" to "Utilisation des jetons",
    "provider.token_usage_help" to "Demander le nombre de jetons d'entrée et de sortie auprès des API de streaming compatibles",
    "provider.use_provider_default" to "Laissez vide pour utiliser la valeur par défaut du fournisseur",
    "provider.system_prompt" to "Invite système",
    "provider.balance_query" to "Consultation du solde",
    "provider.balance_query_help" to "Interroger le solde ou le quota du compte via l'API du fournisseur",
    "provider.balance_api_path" to "Chemin d'API du solde",
    "provider.balance_api_path_help" to "Entrez un chemin relatif ou une URL complète",
    "provider.balance_result_path" to "Chemin JSON du résultat",
    "provider.balance_result_path_help" to "Par exemple : data.balance ou data.items[0].amount",
    "provider.checking_balance" to "Vérification du solde...",
    "provider.current_balance" to "Solde actuel : %s",
    "provider.balance_failed" to "Échec de la vérification du solde : %s",
    "provider.check_balance" to "Vérifier le solde",
    "request_overrides.headers" to "En-têtes personnalisés",
    "request_overrides.headers_help" to "Ajouter aux requêtes de chat et de modèle",
    "request_overrides.add_header" to "Ajouter un en-tête personnalisé",
    "request_overrides.header" to "En-tête",
    "request_overrides.value" to "Valeur",
    "request_overrides.delete_header" to "Supprimer l'en-tête personnalisé",
    "request_overrides.body" to "Corps de requête personnalisé",
    "request_overrides.body_help" to "Fusionner JSON dans les champs de niveau supérieur de la requête",
    "request_overrides.add_body" to "Ajouter un corps de requête",
    "request_overrides.key" to "Clé",
    "request_overrides.json_value" to "Valeur JSON",
    "request_overrides.invalid_json" to "Saisissez un JSON valide",
    "request_overrides.delete_body" to "Supprimer le corps de requête",
    "chat.restore_snapshot" to "Restaurer l'instantané d'historique %d : %s",
    "chat.snapshot_messages" to "%d messages",
    "chat.delete_snapshot" to "Supprimer l'instantané d'historique",
    "jumper.top" to "Aller en haut",
    "jumper.previous" to "Message précédent",
    "jumper.next" to "Message suivant",
    "jumper.bottom" to "Aller en bas",
    "tool.calling" to "En cours",
    "tool.completed" to "Terminé",
    "tool.input" to "Entrée",
    "tool.output" to "Sortie",
    "tool.result" to "Résultat de l'outil",
    "tool.answer_required" to "Votre réponse est nécessaire",
    "tool.web_search" to "Rechercher sur le web",
    "tool.current_time" to "Obtenir l'heure actuelle",
    "tool.memory" to "Gérer la mémoire",
    "tool.list_files" to "Lister les fichiers",
    "tool.search_files" to "Rechercher des fichiers",
    "tool.read_file" to "Lire le fichier",
    "tool.write_file" to "Écrire le fichier",
    "tool.edit_file" to "Modifier le fichier",
    "tool.run_command" to "Exécuter la commande",
    "tool.use_skill" to "Utiliser la compétence",
    "model_picker.refresh_balance" to "Actualiser le solde de %s",
    "model_picker.current_model" to "Modèle actuel",
    "model_capability.text" to "Texte",
    "model_capability.vision" to "Vision",
    "model_capability.reasoning" to "Raisonnement",
    "model_capability.tools" to "Outils",
    "attachment.remove" to "Retirer la pièce jointe",
    "mcp.unnamed_service" to "Service MCP sans nom",
    "language.system_default" to "Par défaut du système",
    "language.chinese" to "Chinois",
    "user.you" to "Vous",
    "message.user_avatar" to "Avatar utilisateur",
    "common.unnamed" to "Sans nom",
    "theme.sakura" to "Sakura",
    "theme.ocean" to "Océan",
    "theme.forest" to "Forêt",
    "theme.sunset" to "Coucher de soleil",
    "theme.lavender" to "Lavande",
    "theme.slate" to "Ardoise",
    "font.system" to "Valeur système",
    "font.sans_serif" to "Sans empattement",
    "font.serif" to "Avec empattement",
    "font.monospace" to "Monospace",
    "runtime.unknown_error" to "Erreur inconnue",
    "runtime.save_failed" to "Échec de l'enregistrement : %s",
    "runtime.title_empty" to "Le modèle de titre n'a renvoyé aucun contenu",
    "runtime.title_failed" to "Échec de la génération du titre",
    "runtime.suggestions_empty" to "Le modèle de suggestions n'a renvoyé aucun contenu",
    "runtime.suggestions_failed" to "Échec de la génération des suggestions de réponse",
    "runtime.mcp_configuration_invalid" to "La configuration MCP n'est plus valide. Sélectionnez à nouveau les serveurs dans les paramètres de l'assistant",
    "runtime.mcp_no_tools" to "Le serveur MCP %s n'a pas fourni d'outils utilisables",
    "runtime.mcp_sync_failed" to "Échec de la synchronisation des outils MCP : %s",
    "runtime.invalid_message_template" to "Modèle de message invalide",
    "runtime.request_failed" to "Échec de la requête",
    "runtime.not_enough_messages" to "Il n'y a pas assez de messages à compresser",
    "runtime.compression_empty" to "Le modèle de compression n'a renvoyé aucun résumé",
    "runtime.compression_failed" to "Échec de la compression de la conversation",
    "runtime.translation_empty" to "Le modèle de traduction n'a renvoyé aucun contenu",
    "runtime.translation_failed" to "Échec de la traduction",
    "runtime.export_failed" to "Échec de l'exportation : %s",
    "runtime.import_failed" to "Échec de l'importation : %s",
    "runtime.tool_round_limit" to "Cette réponse a atteint la limite de %d tours d'appels d'outils. Envoyez un autre message pour commencer une nouvelle exécution.",
    "runtime.add_attachment_failed" to "Impossible d'ajouter la pièce jointe",
    "defaults.new_provider" to "Nouveau fournisseur",
    "defaults.new_assistant" to "Nouvel assistant",
    "file.import_backup" to "Importer une sauvegarde RikkaHub",
    "file.imported_backup" to "Sauvegarde importée depuis %s",
    "file.choose_attachments" to "Ajouter des images, de l'audio, du texte ou des documents",
    "mermaid.diagram" to "Diagramme",
    "mermaid.code" to "Code",
    "mermaid.save_image" to "Enregistrer l'image",
    "mermaid.download" to "Télécharger",
    "mermaid.fullscreen" to "Plein écran",
    "mermaid.exit_fullscreen" to "Quitter le plein écran",
    "provider.connection_success" to "Connecté · %d modèles disponibles"
)
