package me.rerere.rikkahub.desktop

internal val SimplifiedChineseDesktopTranslations = mapOf(
    "settings.language" to "语言",
    "settings.language_description" to "选择桌面应用显示语言",
    "settings.title" to "设置",
    "settings.subtitle" to "外观、交互与模型服务",
    "settings.back" to "返回",
    "settings.color_mode" to "颜色模式",
    "settings.color_mode_description" to "跟随系统，或固定使用浅色或深色主题",
    "settings.system" to "跟随系统",
    "settings.light" to "浅色",
    "settings.dark" to "深色",
    "settings.theme_color" to "主题色",
    "settings.theme_color_description" to "为界面选择一套强调色和配套的明暗色阶",
    "settings.font" to "界面字体",
    "settings.font_description" to "%s，代码块保持等宽字体",
    "settings.chat_font_size" to "聊天字体大小",
    "sidebar.welcome" to "欢迎回来",
    "sidebar.new_chat" to "新建对话",
    "sidebar.search_chats" to "搜索对话",
    "sidebar.back_to_chats" to "返回对话",
    "sidebar.favorite_messages" to "收藏消息",
    "sidebar.search" to "搜索",
    "sidebar.all_assistants" to "全部助手",
    "sidebar.all_tags" to "全部标签",
    "sidebar.chats" to "对话",
    "chat.open_conversations" to "打开对话列表",
    "chat.options" to "对话选项",
    "chat.rename" to "重命名",
    "chat.export_markdown" to "导出 Markdown",
    "chat.generate_title" to "生成标题",
    "chat.statistics" to "对话统计",
    "chat.generate_suggestions" to "生成回复建议",
    "chat.compress_history" to "压缩历史",
    "chat.set_system_prompt" to "设置系统提示词",
    "chat.edit_system_prompt" to "编辑系统提示词",
    "chat.enable_lorebooks" to "启用本对话世界书",
    "chat.disable_lorebooks" to "禁用本对话世界书",
    "chat.move_to_folder" to "移动到文件夹",
    "chat.uncategorized" to "未分类",
    "chat.new_folder" to "新建文件夹",
    "chat.close" to "关闭",
    "message.sources" to "来源",
    "message.source_number" to "来源 %d",
    "message.input_tokens" to "输入 Token",
    "message.output_tokens" to "输出 Token",
    "message.cached_tokens" to "缓存 Token",
    "message.previous_version" to "上一个版本",
    "message.next_version" to "下一个版本",
    "message.copy" to "复制",
    "message.fork" to "从此处分支",
    "message.regenerate" to "重新生成",
    "message.translate" to "翻译",
    "message.favorite" to "收藏",
    "message.unfavorite" to "取消收藏",
    "message.edit" to "编辑",
    "message.delete" to "删除",
    "empty_chat.greeting" to "有什么可以帮你的？",
    "composer.collapse" to "收起输入框",
    "composer.expand" to "展开输入框",
    "composer.add_attachment" to "添加文件",
    "composer.enable_web_search" to "开启联网搜索",
    "composer.disable_web_search" to "关闭联网搜索",
    "composer.quick_messages" to "快捷消息",
    "composer.manage_assistants" to "管理助手与标签",
    "composer.stop_generation" to "停止生成",
    "composer.send" to "发送；长按仅添加消息",
    "settings.show_user_avatar" to "显示用户头像",
    "settings.show_user_avatar_description" to "在用户消息旁显示头像",
    "settings.user_nickname" to "用户昵称",
    "settings.user_nickname_description" to "显示在用户消息旁，留空时使用“你”",
    "settings.user_nickname_placeholder" to "你",
    "settings.show_model_icon" to "显示模型图标",
    "settings.show_model_icon_description" to "在助手消息旁显示模型图标",
    "settings.show_model_name" to "显示模型名称",
    "settings.show_model_name_description" to "在助手消息上方显示模型名称",
    "settings.assistant_bubble" to "助手气泡",
    "settings.assistant_bubble_description" to "用填充气泡显示助手文本",
    "settings.message_timestamp" to "消息时间",
    "settings.message_timestamp_description" to "在每条消息标题中显示创建时间",
    "settings.reasoning" to "思考内容",
    "settings.reasoning_description" to "显示兼容模型返回的推理内容",
    "settings.collapse_reasoning" to "完成后折叠思考内容",
    "settings.collapse_reasoning_description" to "仅在生成进行中展开推理内容",
    "settings.code_wrap" to "代码块自动换行",
    "settings.code_wrap_description" to "长代码行自动换行，而不是横向滚动",
    "settings.chinese_typography" to "中文排版优化",
    "settings.chinese_typography_description" to "在中文与西文、数字或符号之间自动添加间距",
    "settings.mermaid_rendering" to "渲染 Mermaid 图表",
    "settings.mermaid_rendering_description" to "将 Mermaid 代码块渲染为可交互图表",
    "settings.mermaid_cli" to "允许调用 Mermaid CLI",
    "settings.mermaid_cli_description" to "允许 Mermaid CLI 在本地执行以渲染图表",
    "settings.mermaid_cli_path" to "Mermaid CLI 路径",
    "settings.mermaid_cli_path_description" to "留空时自动查找 PATH、npm 全局目录和用户本地目录",
    "settings.mermaid_system_browser" to "复用系统浏览器",
    "settings.mermaid_system_browser_description" to "允许 Mermaid CLI 使用已安装的 Chromium 系浏览器",
    "settings.send_on_enter" to "按 Enter 发送",
    "settings.send_on_enter_description" to "关闭后，Ctrl+Enter 发送，Enter 换行",
    "settings.auto_scroll" to "自动滚动",
    "settings.auto_scroll_description" to "生成时跟随新的推理和回复内容",
    "settings.smooth_scroll" to "平滑滚动",
    "settings.smooth_scroll_description" to "在聊天界面为鼠标滚轮滚动添加动画效果",
    "settings.message_navigation" to "消息导航",
    "settings.message_navigation_description" to "滚动消息后显示跳转到顶部、上一条、下一条和底部的按钮",
    "settings.message_navigation_left" to "消息导航置左",
    "settings.message_navigation_left_description" to "默认显示在消息区域右侧",
    "settings.export_backup" to "导出备份",
    "settings.export_backup_description" to "将服务商、助手、偏好和对话保存为 JSON",
    "settings.export" to "导出",
    "settings.import_backup" to "导入备份",
    "settings.import_backup_description" to "使用 RikkaHub 备份替换当前桌面端数据",
    "settings.import" to "导入",
    "settings.reset_data" to "重置全部数据",
    "settings.reset_data_description" to "删除本机的服务商、助手、偏好和对话，此操作无法撤销",
    "settings.reset" to "重置",
    "settings.web_search" to "联网搜索服务",
    "settings.web_search_description" to "配置后优先使用外部搜索服务；未配置时使用模型服务商的原生搜索",
    "settings.searxng_url" to "SearXNG 地址",
    "settings.api_key" to "API 密钥",
    "settings.search_result_count" to "每次搜索返回 %d 条结果",
    "settings.test_search" to "测试搜索",
    "settings.search_test_success" to "联网搜索连接正常",
    "settings.search_test_failed" to "搜索测试失败",
    "settings.add_assistant" to "添加助手",
    "settings.assistant_name" to "助手名称",
    "settings.copy_assistant" to "复制助手",
    "settings.delete_assistant" to "删除助手",
    "settings.tags" to "标签（逗号分隔）",
    "settings.model_inherit" to "模型（留空使用服务商默认值）",
    "settings.select_model" to "选择模型",
    "settings.system_prompt_inherit" to "系统提示词（留空使用服务商默认值）",
    "settings.apply_preset" to "应用预设",
    "settings.add_provider" to "添加服务商",
    "settings.provider_name" to "服务商名称",
    "settings.delete_provider" to "删除服务商",
    "settings.base_url" to "基础 URL",
    "settings.hide_api_key" to "隐藏 API 密钥",
    "settings.show_api_key" to "显示 API 密钥",
    "settings.model" to "模型",
    "settings.select_discovered_model" to "选择已发现的模型",
    "settings.test_and_fetch_models" to "测试并获取模型",
    "settings.provider_saved" to "服务商设置已保存",
    "settings.save_provider" to "保存服务商",
    "settings.back_to_chat" to "返回对话",
    "settings.unsaved_changes_title" to "保存更改？",
    "settings.unsaved_changes_description" to "设置已更改。是否在退出前保存？",
    "settings.discard_changes" to "不保存",
    "settings.reset_confirmation_title" to "重置全部数据？",
    "settings.reset_confirmation_description" to "这会永久删除桌面端的服务商密钥、助手、设置和所有对话。",
    "settings.confirm_reset" to "确认重置",
    "common.cancel" to "取消",
    "common.save" to "保存",
    "common.submit" to "提交",
    "common.expand" to "展开",
    "common.collapse" to "收起",
    "message.thinking" to "思考中...",
    "message.translation" to "翻译",
    "attachment.audio" to "音频",
    "timeline.execution" to "执行过程",
    "timeline.expand_execution" to "展开执行过程",
    "timeline.collapse_execution" to "收起执行过程",
    "timeline.expand_steps" to "展开 %d 个步骤",
    "timeline.reasoning" to "思考过程",
    "timeline.reasoning_duration" to "思考了 %s 秒",
    "timeline.today" to "今天",
    "timeline.yesterday" to "昨天",
    "timeline.day_before_yesterday" to "前天",
    "timeline.days_ago" to "%d 天前",
    "sidebar.recent" to "最近",
    "sidebar.most_active" to "最常用",
    "sidebar.sort_recent" to "按最近时间",
    "sidebar.sort_most_active" to "按使用频率",
    "sidebar.tool_call" to "工具调用",
    "sidebar.rename_folder" to "重命名文件夹",
    "common.new" to "新建",
    "conversation.branch" to "对话分支",
    "conversation.pinned" to "已置顶",
    "conversation.pin" to "置顶",
    "conversation.unpin" to "取消置顶",
    "conversation.move_to_chat" to "移至聊天",
    "conversation.move_to_folder" to "移至 %s",
    "dialog.rename_conversation" to "重命名对话",
    "dialog.conversation_system_prompt" to "对话系统提示词",
    "dialog.compress_history" to "压缩对话历史",
    "dialog.compress_history_description" to "将较早消息生成摘要，并保留最近消息。压缩前的完整历史会保存为可恢复快照。",
    "dialog.target_tokens" to "目标 Token 数",
    "dialog.keep_recent_messages" to "保留最近消息数（共 %d 条）",
    "dialog.additional_instructions" to "附加说明（可选）",
    "dialog.compress" to "压缩",
    "dialog.translate_message" to "翻译消息",
    "dialog.target_language" to "目标语言",
    "stats.messages" to "消息",
    "stats.attachments" to "附件",
    "stats.characters" to "文本与思维链字符",
    "stats.created_at" to "创建时间",
    "stats.updated_at" to "更新时间",
    "file.add_attachments" to "添加附件",
    "file.parent_directory" to "上级目录",
    "file.selected" to "已选择",
    "file.add_count" to "添加（%d）",
    "file.file_name" to "文件名",
    "file.export_conversation_markdown" to "将对话导出为 Markdown",
    "file.export_backup" to "导出 RikkaHub 备份",
    "agent.approval_request" to "Agent 请求此操作，是否允许？",
    "agent.docker_network_warning" to "将在受限 Docker 容器中执行，并临时使用宿主网络；完成后恢复到无外网的隔离容器。",
    "agent.docker_warning" to "将在受限 Docker 容器中执行；容器仅挂载选定工作区。",
    "agent.local_shell_warning" to "本机 Shell 以当前用户权限运行；请确认命令及其影响。",
    "agent.confirm_impact" to "请确认命令及其影响。",
    "agent.image_pull_warning" to "将从镜像仓库下载内容到本机 Docker 缓存。",
    "agent.skill_warning" to "Skill 指令可能影响后续 Agent 行为。",
    "agent.write_warning" to "文件修改限制在已选定的工作区目录内。",
    "agent.remember_docker_shell" to "本对话内自动批准此工作区的 Docker 命令",
    "agent.remember_docker_network" to "本对话内自动批准此工作区的 Docker 联网命令",
    "agent.remember_image_pull" to "本对话内自动批准此工作区的此镜像下载",
    "agent.remember_operation" to "本对话内自动批准此类操作",
    "agent.allow" to "允许",
    "agent.deny" to "拒绝",
    "settings.navigation" to "设置分类",
    "settings.section.general" to "通用设置",
    "settings.section.messages" to "消息显示",
    "settings.section.interaction" to "交互",
    "settings.section.data" to "数据、备份与联网搜索",
    "settings.section.assistants" to "助手",
    "settings.section.providers" to "模型与服务",
    "composer.placeholder" to "给 RikkaHub 发送消息",
    "model_picker.title" to "选择模型",
    "model_picker.filter" to "筛选模型",
    "model_picker.reasoning" to "推理强度",
    "model_picker.default" to "默认",
    "model_picker.low" to "低",
    "model_picker.medium" to "中",
    "model_picker.high" to "高",
    "model_picker.manage_providers" to "管理服务商",
    "model_picker.checking_balance" to "查询余额中",
    "model_picker.balance" to "余额：%s",
    "model_picker.balance_failed" to "余额查询失败",
    "mcp.manage" to "管理 MCP 服务",
    "mcp.check" to "检测可用性",
    "mcp.title" to "MCP 服务",
    "mcp.services_for_assistant" to "当前助手使用 %d 个服务",
    "mcp.check_all" to "检测全部",
    "mcp.open_settings" to "打开 MCP 设置",
    "mcp.no_servers" to "尚未配置 MCP 服务",
    "mcp.not_checked" to "尚未检测",
    "mcp.checking" to "正在检测",
    "mcp.tools_synced" to "已同步 %d 个工具",
    "mcp.available_tools" to "可用 · %d 个工具",
    "mcp.current_assistant" to "当前助手",
    "mcp.enabled" to "启用",
    "mcp.available" to "可用",
    "mcp.unavailable" to "不可用",
    "mcp_settings.title" to "MCP 服务器",
    "mcp_settings.description" to "同步远程工具后，为此助手启用所需服务器",
    "mcp_settings.add_server" to "添加 MCP 服务器",
    "mcp_settings.unnamed_server" to "未命名 MCP 服务器",
    "mcp_settings.delete_server" to "删除 MCP 服务器",
    "mcp_settings.server_name" to "服务器名称",
    "mcp_settings.server_name_help" to "仅允许字母和数字，用于生成稳定的工具名",
    "mcp_settings.command" to "启动命令",
    "mcp_settings.arguments" to "命令参数",
    "mcp_settings.arguments_help" to "每行一个参数",
    "mcp_settings.environment" to "环境变量",
    "mcp_settings.environment_help" to "每行一个 KEY=VALUE",
    "mcp_settings.server_url" to "服务器 URL",
    "mcp_settings.enable_server" to "启用服务器",
    "mcp_settings.enable_server_help" to "关闭后不会向模型暴露其中的工具",
    "mcp_settings.sync_failed" to "同步 MCP 工具失败",
    "mcp_settings.sync_timeout" to "同步 MCP 工具超时（10 秒）",
    "mcp_settings.sync_tools" to "同步工具",
    "mcp_settings.collapse_tools" to "收起工具",
    "mcp_settings.manage_tools" to "管理 %d 个工具（已启用 %e 个）",
    "mcp_settings.tool" to "MCP 工具",
    "assistant.message_template" to "消息模板",
    "assistant.template_variables" to "变量：{{ message }}、{{ role }}、{{ date }}、{{ time }}",
    "assistant.template_invalid" to "需要包含 {{ message }} 的有效 Pebble 模板",
    "assistant.conversation_system_prompt" to "对话系统提示词",
    "assistant.conversation_system_prompt_help" to "允许单个对话覆盖此助手的系统提示词",
    "assistant.conversation_lorebooks" to "对话世界书",
    "assistant.conversation_lorebooks_help" to "允许单个对话启用或禁用此助手的提示词注入",
    "assistant.web_search" to "联网搜索",
    "assistant.web_search_help" to "默认在新对话中启用兼容 OpenAI 的联网搜索",
    "assistant.local_time_tool" to "本地时间工具",
    "assistant.local_time_tool_help" to "允许模型按需读取此设备的本地时间和时区",
    "assistant.ask_user_tool" to "主动提问",
    "assistant.ask_user_tool_help" to "允许模型在需要澄清信息或确认时向你提问",
    "assistant.max_tool_rounds" to "每次回复的工具调用轮数上限",
    "assistant.max_tool_rounds_help" to "0 表示不限制；默认值为 8",
    "assistant.agent_workspace" to "Agent 工作区",
    "assistant.agent_workspace_help" to "允许模型在选定目录内读写文件、执行命令并加载已启用的 Skills",
    "assistant.workspace_directory" to "工作区目录",
    "assistant.workspace_directory_help" to "仅允许 Agent 文件工具访问此目录；本地 shell 每次仍会要求确认",
    "assistant.docker_container" to "Docker 容器",
    "assistant.local_shell" to "本机 Shell",
    "assistant.docker_image" to "Docker 镜像",
    "assistant.docker_image_help" to "默认断网、无特权、只挂载工作区；首次拉取需批准",
    "assistant.enabled_skills" to "已启用 Skills",
    "assistant.enabled_skills_help" to "逗号分隔；目录位于 ~/.config/rikkahub/skills/<名称>/SKILL.md",
    "assistant.stream_output" to "流式输出",
    "assistant.stream_output_help" to "实时显示回复内容，而不是等待完整回复",
    "assistant.memory" to "记忆",
    "assistant.memory_help" to "允许模型记录、更新和使用跨对话的长期信息",
    "assistant.global_memory" to "全局共享记忆",
    "assistant.global_memory_help" to "与其他启用共享记忆的助手共用记忆库",
    "assistant.add_global_memory" to "添加全局记忆",
    "assistant.delete_global_memory" to "删除全局记忆",
    "assistant.shared_memory_content" to "共享事实或偏好",
    "assistant.memory_entries" to "记忆条目",
    "assistant.add_memory" to "添加记忆",
    "assistant.delete_memory" to "删除记忆",
    "assistant.memory_content" to "事实或偏好",
    "assistant.temperature" to "温度",
    "assistant.inherit_provider" to "留空继承服务商设置",
    "assistant.max_output_tokens" to "最大输出 Token",
    "assistant.context_messages" to "上下文消息数",
    "assistant.keep_all_when_empty" to "留空保留全部",
    "common.add" to "添加",
    "role.system" to "系统",
    "role.user" to "用户",
    "role.assistant" to "助手",
    "assistant.preset_messages" to "预设消息",
    "assistant.preset_messages_help" to "在每个新对话中添加示例消息",
    "assistant.message" to "消息",
    "assistant.delete_preset_message" to "删除预设消息",
    "assistant.quick_messages" to "快捷消息",
    "assistant.quick_messages_help" to "从聊天输入框插入可复用提示词",
    "assistant.title" to "标题",
    "assistant.content" to "内容",
    "assistant.delete_quick_message" to "删除快捷消息",
    "assistant.regex_transforms" to "正则转换",
    "assistant.regex_transforms_help" to "转换用户输入、助手输出或显示文本",
    "assistant.rule_name" to "规则名称",
    "assistant.delete_regex_rule" to "删除正则规则",
    "assistant.find_regex" to "匹配正则",
    "assistant.replace_with" to "替换为",
    "assistant.visual_only" to "仅视觉显示",
    "assistant.prompt_injections" to "提示词注入 / 世界书",
    "assistant.prompt_injections_help" to "按关键词匹配上下文，或设为常驻注入",
    "assistant.entry_name" to "条目名称",
    "assistant.delete_injection" to "删除注入条目",
    "assistant.injection_content" to "注入内容",
    "assistant.keywords" to "关键词（逗号分隔）",
    "assistant.keywords_help" to "留空时请开启常驻",
    "assistant.priority" to "优先级",
    "assistant.priority_help" to "数值越大越靠前",
    "assistant.scan_depth" to "扫描消息数",
    "assistant.scan_depth_help" to "用于关键词匹配",
    "assistant.injection_depth" to "注入深度",
    "assistant.injection_depth_help" to "从末尾倒数",
    "assistant.injection_role" to "注入角色",
    "assistant.before_system" to "系统前",
    "assistant.after_system" to "系统后",
    "assistant.top_of_chat" to "聊天顶部",
    "assistant.bottom_of_chat" to "聊天底部",
    "assistant.at_depth" to "指定深度",
    "assistant.always_active" to "常驻",
    "assistant.regex_keywords" to "正则关键词",
    "assistant.case_sensitive" to "区分大小写",
    "assistant.saved" to "助手设置已保存",
    "assistant.save" to "保存助手",
    "provider.title_model" to "标题模型",
    "provider.title_model_help" to "留空时使用聊天模型",
    "provider.suggestion_model" to "回复建议模型",
    "provider.suggestion_model_help" to "留空时使用聊天模型；建议生成会关闭推理",
    "provider.title_prompt" to "标题提示词",
    "provider.title_prompt_help" to "支持 {locale} 与 {content} 占位符",
    "provider.token_usage" to "Token 用量",
    "provider.token_usage_help" to "从兼容的流式 API 请求输入和输出 Token 计数",
    "provider.use_provider_default" to "留空使用服务商默认值",
    "provider.system_prompt" to "系统提示词",
    "provider.balance_query" to "余额查询",
    "provider.balance_query_help" to "通过服务商 API 查询账户余额或额度",
    "provider.balance_api_path" to "余额 API 路径",
    "provider.balance_api_path_help" to "可填写相对路径或完整 URL",
    "provider.balance_result_path" to "结果 JSON 路径",
    "provider.balance_result_path_help" to "例如 data.balance 或 data.items[0].amount",
    "provider.checking_balance" to "正在查询余额...",
    "provider.current_balance" to "当前余额：%s",
    "provider.balance_failed" to "余额查询失败：%s",
    "provider.check_balance" to "查询余额",
    "request_overrides.headers" to "自定义请求头",
    "request_overrides.headers_help" to "添加到聊天和模型请求中",
    "request_overrides.add_header" to "添加自定义请求头",
    "request_overrides.header" to "请求头",
    "request_overrides.value" to "值",
    "request_overrides.delete_header" to "删除自定义请求头",
    "request_overrides.body" to "自定义请求体",
    "request_overrides.body_help" to "将 JSON 合并到请求顶层字段",
    "request_overrides.add_body" to "添加自定义请求体",
    "request_overrides.key" to "键",
    "request_overrides.json_value" to "JSON 值",
    "request_overrides.invalid_json" to "请输入有效 JSON",
    "request_overrides.delete_body" to "删除自定义请求体",
    "chat.restore_snapshot" to "恢复历史快照 %d：%s",
    "chat.snapshot_messages" to "%d 条消息",
    "chat.delete_snapshot" to "删除历史快照",
    "jumper.top" to "跳转到顶部",
    "jumper.previous" to "上一条消息",
    "jumper.next" to "下一条消息",
    "jumper.bottom" to "跳转到底部",
    "jumper.search_messages" to "搜索消息",
    "jumper.no_matching_messages" to "没有匹配的消息",
    "jumper.user" to "你",
    "jumper.assistant" to "助手",
    "jumper.empty_message" to "无消息正文",
    "tool.calling" to "正在调用",
    "tool.completed" to "调用完成",
    "tool.input" to "输入",
    "tool.output" to "输出",
    "tool.result" to "工具结果",
    "tool.answer_required" to "需要你的回答",
    "tool.web_search" to "搜索网页",
    "tool.current_time" to "获取时间",
    "tool.memory" to "管理记忆",
    "tool.list_files" to "列出文件",
    "tool.search_files" to "搜索文件",
    "tool.read_file" to "读取文件",
    "tool.write_file" to "写入文件",
    "tool.edit_file" to "编辑文件",
    "tool.run_command" to "执行命令",
    "tool.use_skill" to "使用技能",
    "model_picker.refresh_balance" to "刷新 %s 余额",
    "model_picker.current_model" to "当前模型",
    "model_capability.text" to "文本",
    "model_capability.vision" to "视觉",
    "model_capability.reasoning" to "推理",
    "model_capability.tools" to "工具",
    "attachment.remove" to "移除附件",
    "mcp.unnamed_service" to "未命名 MCP 服务",
    "language.system_default" to "系统默认",
    "language.chinese" to "中文",
    "user.you" to "你",
    "message.user_avatar" to "用户头像",
    "common.unnamed" to "未命名",
    "theme.sakura" to "樱花",
    "theme.ocean" to "海洋",
    "theme.forest" to "森林",
    "theme.sunset" to "落日",
    "theme.lavender" to "薰衣草",
    "theme.slate" to "石墨",
    "font.system" to "系统默认",
    "font.sans_serif" to "无衬线",
    "font.serif" to "衬线",
    "font.monospace" to "等宽",
    "runtime.unknown_error" to "未知错误",
    "runtime.save_failed" to "保存失败：%s",
    "runtime.title_empty" to "标题模型没有返回内容",
    "runtime.title_failed" to "生成标题失败",
    "runtime.suggestions_empty" to "建议模型没有返回内容",
    "runtime.suggestions_failed" to "生成回复建议失败",
    "runtime.mcp_configuration_invalid" to "MCP 配置已失效，请在助手设置中重新选择服务器",
    "runtime.mcp_no_tools" to "MCP 服务器 %s 未提供可用工具",
    "runtime.mcp_sync_failed" to "MCP 工具同步失败：%s",
    "runtime.invalid_message_template" to "无效的消息模板",
    "runtime.request_failed" to "请求失败",
    "runtime.not_enough_messages" to "没有足够的消息可压缩",
    "runtime.compression_empty" to "压缩模型没有返回摘要",
    "runtime.compression_failed" to "压缩对话失败",
    "runtime.translation_empty" to "翻译模型没有返回内容",
    "runtime.translation_failed" to "翻译失败",
    "runtime.export_failed" to "导出失败：%s",
    "runtime.import_failed" to "导入失败：%s",
    "runtime.tool_round_limit" to "本次回复已达到 %d 轮工具调用上限。请继续发送消息以开始新的处理。",
    "runtime.add_attachment_failed" to "无法添加文件",
    "defaults.new_provider" to "新服务商",
    "defaults.new_assistant" to "新助手",
    "file.import_backup" to "导入 RikkaHub 备份",
    "file.imported_backup" to "已从 %s 导入备份",
    "file.choose_attachments" to "添加图片、音频、文本或文档",
    "mermaid.diagram" to "图表",
    "mermaid.code" to "代码",
    "mermaid.save_image" to "保存图像",
    "mermaid.download" to "下载",
    "mermaid.fullscreen" to "全屏",
    "mermaid.exit_fullscreen" to "退出全屏",
    "provider.connection_success" to "已连接 · 可用 %d 个模型"
)
