package me.rerere.rikkahub.desktop

internal val SpanishDesktopTranslations = mapOf(
    "settings.language" to "Idioma",
    "settings.language_description" to "Elige el idioma de la aplicación de escritorio",
    "settings.title" to "Ajustes",
    "settings.subtitle" to "Apariencia, interacción y modelos",
    "settings.back" to "Volver",
    "settings.color_mode" to "Modo de color",
    "settings.color_mode_description" to "Seguir el sistema, o usar un tema claro u oscuro fijo",
    "settings.system" to "Sistema",
    "settings.light" to "Claro",
    "settings.dark" to "Oscuro",
    "settings.theme_color" to "Color del tema",
    "settings.theme_color_description" to "Elige un color de acento y tonos a juego para la interfaz",
    "settings.font" to "Fuente de la interfaz",
    "settings.font_description" to "%s; los bloques de código permanecen monoespaciados",
    "settings.chat_font_size" to "Tamaño de fuente del chat",
    "sidebar.welcome" to "Bienvenido de nuevo",
    "sidebar.new_chat" to "Chat nuevo",
    "sidebar.search_chats" to "Buscar chats",
    "sidebar.back_to_chats" to "Volver a chats",
    "sidebar.favorite_messages" to "Mensajes favoritos",
    "sidebar.search" to "Buscar",
    "sidebar.all_assistants" to "Todos los asistentes",
    "sidebar.all_tags" to "Todas las etiquetas",
    "sidebar.chats" to "Chats",
    "chat.open_conversations" to "Abrir conversaciones",
    "chat.options" to "Opciones de conversación",
    "chat.rename" to "Cambiar nombre",
    "chat.export_markdown" to "Exportar Markdown",
    "chat.generate_title" to "Generar título",
    "chat.statistics" to "Estadísticas de la conversación",
    "chat.generate_suggestions" to "Generar sugerencias de respuesta",
    "chat.compress_history" to "Comprimir historial",
    "chat.set_system_prompt" to "Establecer mensaje del sistema",
    "chat.edit_system_prompt" to "Editar mensaje del sistema",
    "chat.enable_lorebooks" to "Activar libros de lore de la conversación",
    "chat.disable_lorebooks" to "Desactivar libros de lore de la conversación",
    "chat.move_to_folder" to "Mover a carpeta",
    "chat.uncategorized" to "Sin categoría",
    "chat.new_folder" to "Carpeta nueva",
    "chat.close" to "Cerrar",
    "message.sources" to "Fuentes",
    "message.source_number" to "Fuente %d",
    "message.input_tokens" to "Tokens de entrada",
    "message.output_tokens" to "Tokens de salida",
    "message.cached_tokens" to "Tokens en caché",
    "message.previous_version" to "Versión anterior",
    "message.next_version" to "Siguiente versión",
    "message.copy" to "Copiar",
    "message.fork" to "Bifurcar desde aquí",
    "message.regenerate" to "Regenerar",
    "message.translate" to "Traducir",
    "message.favorite" to "Favorito",
    "message.unfavorite" to "Quitar de favoritos",
    "message.edit" to "Editar",
    "message.delete" to "Eliminar",
    "empty_chat.greeting" to "¿En qué puedo ayudarte?",
    "composer.collapse" to "Colapsar compositor",
    "composer.expand" to "Expandir compositor",
    "composer.add_attachment" to "Agregar archivo adjunto",
    "composer.enable_web_search" to "Activar búsqueda web",
    "composer.disable_web_search" to "Desactivar búsqueda web",
    "composer.quick_messages" to "Mensajes rápidos",
    "composer.manage_assistants" to "Gestionar asistentes y etiquetas",
    "composer.stop_generation" to "Detener generación",
    "composer.send" to "Enviar; mantén pulsado para agregar sin respuesta",
    "settings.show_user_avatar" to "Mostrar avatar de usuario",
    "settings.show_user_avatar_description" to "Mostrar un avatar junto a los mensajes del usuario",
    "settings.user_nickname" to "Apodo de usuario",
    "settings.user_nickname_description" to "Se muestra junto a los mensajes del usuario; por defecto «Tú» si está vacío",
    "settings.user_nickname_placeholder" to "Tú",
    "settings.show_model_icon" to "Mostrar icono del modelo",
    "settings.show_model_icon_description" to "Mostrar el icono del modelo junto a los mensajes del asistente",
    "settings.show_model_name" to "Mostrar nombre del modelo",
    "settings.show_model_name_description" to "Mostrar el nombre del modelo encima de los mensajes del asistente",
    "settings.assistant_bubble" to "Burbuja del asistente",
    "settings.assistant_bubble_description" to "Mostrar el texto del asistente en una burbuja rellena",
    "settings.message_timestamp" to "Hora del mensaje",
    "settings.message_timestamp_description" to "Mostrar la hora de creación en la cabecera de cada mensaje",
    "settings.reasoning" to "Contenido de razonamiento",
    "settings.reasoning_description" to "Mostrar el razonamiento devuelto por modelos compatibles",
    "settings.collapse_reasoning" to "Contraer razonamiento al terminar",
    "settings.collapse_reasoning_description" to "Solo expandir el razonamiento mientras se genera una respuesta",
    "settings.code_wrap" to "Ajustar bloques de código",
    "settings.code_wrap_description" to "Ajustar líneas largas de código en lugar de desplazar horizontalmente",
    "settings.chinese_typography" to "Tipografía china",
    "settings.chinese_typography_description" to "Añadir espaciado entre texto chino y latino, números o símbolos",
    "settings.mermaid_rendering" to "Renderizar diagramas Mermaid",
    "settings.mermaid_rendering_description" to "Renderizar bloques de código Mermaid como diagramas interactivos",
    "settings.mermaid_cli" to "Permitir Mermaid CLI",
    "settings.mermaid_cli_description" to "Permitir que Mermaid CLI se ejecute localmente para renderizar diagramas",
    "settings.mermaid_cli_path" to "Ruta de Mermaid CLI",
    "settings.mermaid_cli_path_description" to "Déjela vacía para detectar automáticamente PATH, npm global y ubicaciones locales del usuario",
    "settings.mermaid_system_browser" to "Usar el navegador del sistema",
    "settings.mermaid_system_browser_description" to "Permitir que Mermaid CLI use un navegador basado en Chromium instalado",
    "settings.send_on_enter" to "Enviar con Enter",
    "settings.send_on_enter_description" to "Cuando está desactivado, Ctrl+Enter envía y Enter añade una nueva línea",
    "settings.auto_scroll" to "Desplazamiento automático",
    "settings.auto_scroll_description" to "Seguir el nuevo contenido de razonamiento y respuesta mientras se genera",
    "settings.smooth_scroll" to "Desplazamiento suave",
    "settings.smooth_scroll_description" to "Animar el desplazamiento con la rueda del ratón en el chat",
    "settings.message_navigation" to "Navegación de mensajes",
    "settings.message_navigation_description" to "Mostrar botones para ir al principio, anterior, siguiente y final después de desplazarse",
    "settings.message_navigation_left" to "Navegación de mensajes a la izquierda",
    "settings.message_navigation_left_description" to "Se muestra en el lado derecho del área de mensajes por defecto",
    "settings.export_backup" to "Exportar copia de seguridad",
    "settings.export_backup_description" to "Guardar proveedores, asistentes, preferencias y chats como JSON",
    "settings.export" to "Exportar",
    "settings.import_backup" to "Importar copia de seguridad",
    "settings.import_backup_description" to "Reemplazar los datos actuales del escritorio con una copia de seguridad de RikkaHub",
    "settings.import" to "Importar",
    "settings.reset_data" to "Restablecer todos los datos",
    "settings.reset_data_description" to "Eliminar proveedores locales, asistentes, preferencias y chats. Esta acción no se puede deshacer.",
    "settings.reset" to "Restablecer",
    "settings.web_search" to "Servicio de búsqueda web",
    "settings.web_search_description" to "Usar un servicio de búsqueda externo cuando esté configurado; de lo contrario, usar la búsqueda nativa del proveedor del modelo",
    "settings.searxng_url" to "URL de SearXNG",
    "settings.api_key" to "Clave de API",
    "settings.search_result_count" to "%d resultados por búsqueda",
    "settings.test_search" to "Probar búsqueda",
    "settings.search_test_success" to "La conexión de búsqueda web funciona",
    "settings.search_test_failed" to "Error en la prueba de búsqueda",
    "settings.add_assistant" to "Agregar asistente",
    "settings.assistant_name" to "Nombre del asistente",
    "settings.copy_assistant" to "Copiar asistente",
    "settings.delete_assistant" to "Eliminar asistente",
    "settings.tags" to "Etiquetas (separadas por comas)",
    "settings.model_inherit" to "Modelo (déjalo vacío para usar el predeterminado del proveedor)",
    "settings.select_model" to "Elegir modelo",
    "settings.system_prompt_inherit" to "Mensaje del sistema (déjalo vacío para usar el predeterminado del proveedor)",
    "settings.apply_preset" to "Aplicar preajuste",
    "settings.add_provider" to "Agregar proveedor",
    "settings.provider_name" to "Nombre del proveedor",
    "settings.delete_provider" to "Eliminar proveedor",
    "settings.base_url" to "URL base",
    "settings.hide_api_key" to "Ocultar clave de API",
    "settings.show_api_key" to "Mostrar clave de API",
    "settings.model" to "Modelo",
    "settings.select_discovered_model" to "Seleccionar modelo descubierto",
    "settings.test_and_fetch_models" to "Probar y obtener modelos",
    "settings.provider_saved" to "Configuración del proveedor guardada",
    "settings.save_provider" to "Guardar proveedor",
    "settings.back_to_chat" to "Volver al chat",
    "settings.unsaved_changes_title" to "¿Guardar cambios?",
    "settings.unsaved_changes_description" to "La configuración ha cambiado. ¿Guardar antes de salir?",
    "settings.discard_changes" to "No guardar",
    "settings.reset_confirmation_title" to "¿Restablecer todos los datos?",
    "settings.reset_confirmation_description" to "Esto elimina permanentemente los secretos del proveedor de escritorio, asistentes, ajustes y todas las conversaciones.",
    "settings.confirm_reset" to "Restablecer datos",
    "common.cancel" to "Cancelar",
    "common.save" to "Guardar",
    "common.submit" to "Enviar",
    "common.expand" to "Expandir ",
    "common.collapse" to "Contraer ",
    "message.thinking" to "Pensando...",
    "message.translation" to "Traducción",
    "attachment.audio" to "Audio",
    "timeline.execution" to "Ejecución",
    "timeline.expand_execution" to "Expandir ejecución",
    "timeline.collapse_execution" to "Contraer ejecución",
    "timeline.expand_steps" to "Expandir %d pasos",
    "timeline.reasoning" to "Razonamiento",
    "timeline.reasoning_duration" to "Razonó durante %s segundos",
    "timeline.today" to "Hoy",
    "timeline.yesterday" to "Ayer",
    "timeline.day_before_yesterday" to "Anteayer",
    "timeline.days_ago" to "Hace %d días",
    "sidebar.recent" to "Recientes",
    "sidebar.most_active" to "Más activos",
    "sidebar.sort_recent" to "Ordenar por actividad reciente",
    "sidebar.sort_most_active" to "Ordenar por frecuencia de uso",
    "sidebar.tool_call" to "Llamada a herramienta",
    "sidebar.rename_folder" to "Renombrar carpeta",
    "common.new" to "Nuevo",
    "conversation.branch" to "Rama de conversación",
    "conversation.pinned" to "Fijado",
    "conversation.pin" to "Fijar",
    "conversation.unpin" to "Desfijar",
    "conversation.move_to_chat" to "Mover a chats",
    "conversation.move_to_folder" to "Mover a %s",
    "dialog.rename_conversation" to "Renombrar conversación",
    "dialog.conversation_system_prompt" to "Mensaje del sistema de la conversación",
    "dialog.compress_history" to "Comprimir historial de la conversación",
    "dialog.compress_history_description" to "Resumir los mensajes anteriores y conservar los recientes. El historial completo se guarda como una instantánea recuperable.",
    "dialog.target_tokens" to "Tokens objetivo",
    "dialog.keep_recent_messages" to "Conservar mensajes recientes (de %d en total)",
    "dialog.additional_instructions" to "Instrucciones adicionales (opcional)",
    "dialog.compress" to "Comprimir",
    "dialog.translate_message" to "Traducir mensaje",
    "dialog.target_language" to "Idioma de destino",
    "stats.messages" to "Mensajes",
    "stats.attachments" to "Archivos adjuntos",
    "stats.characters" to "Caracteres de texto y razonamiento",
    "stats.created_at" to "Creado",
    "stats.updated_at" to "Actualizado",
    "file.add_attachments" to "Agregar archivos adjuntos",
    "file.parent_directory" to "Directorio superior",
    "file.selected" to "Seleccionado",
    "file.add_count" to "Agregar (%d)",
    "file.file_name" to "Nombre de archivo",
    "file.export_conversation_markdown" to "Exportar conversación como Markdown",
    "file.export_backup" to "Exportar copia de seguridad de RikkaHub",
    "agent.approval_request" to "El agente solicita esta operación. ¿Permitir?",
    "agent.docker_network_warning" to "Se ejecuta en un contenedor Docker restringido con red de host temporal y luego vuelve a un contenedor aislado sin conexión.",
    "agent.docker_warning" to "Se ejecuta en un contenedor Docker restringido que monta solo el espacio de trabajo seleccionado.",
    "agent.local_shell_warning" to "La shell local se ejecuta con los permisos de tu usuario actual. Confirma el comando y su impacto.",
    "agent.confirm_impact" to "Confirma el comando y su impacto.",
    "agent.image_pull_warning" to "Descarga contenido de un registro de imágenes a la caché local de Docker.",
    "agent.skill_warning" to "Las instrucciones de la habilidad pueden afectar el comportamiento posterior del agente.",
    "agent.write_warning" to "Los cambios de archivos se limitan al directorio del espacio de trabajo seleccionado.",
    "agent.remember_docker_shell" to "Aprobar automáticamente comandos Docker para este espacio de trabajo en esta conversación",
    "agent.remember_docker_network" to "Aprobar automáticamente comandos de red Docker para este espacio de trabajo en esta conversación",
    "agent.remember_image_pull" to "Aprobar automáticamente esta descarga de imagen en esta conversación",
    "agent.remember_operation" to "Aprobar automáticamente este tipo de operación en esta conversación",
    "agent.allow" to "Permitir",
    "agent.deny" to "Denegar",
    "settings.navigation" to "Categorías de ajustes",
    "settings.section.general" to "General",
    "settings.section.messages" to "Mensajes",
    "settings.section.interaction" to "Interacción",
    "settings.section.data" to "Datos, copias de seguridad y búsqueda web",
    "settings.section.assistants" to "Asistentes",
    "settings.section.providers" to "Modelos y servicios",
    "composer.placeholder" to "Enviar mensaje a RikkaHub",
    "model_picker.title" to "Elegir modelo",
    "model_picker.filter" to "Filtrar modelos",
    "model_picker.reasoning" to "Nivel de razonamiento",
    "model_picker.default" to "Predeterminado",
    "model_picker.low" to "Bajo",
    "model_picker.medium" to "Medio",
    "model_picker.high" to "Alto",
    "model_picker.manage_providers" to "Gestionar proveedores",
    "model_picker.checking_balance" to "Consultando saldo",
    "model_picker.balance" to "Saldo: %s",
    "model_picker.balance_failed" to "Saldo no disponible",
    "mcp.manage" to "Gestionar servicios MCP",
    "mcp.check" to "Comprobar disponibilidad",
    "mcp.title" to "Servicios MCP",
    "mcp.services_for_assistant" to "%d servicios para este asistente",
    "mcp.check_all" to "Comprobar todo",
    "mcp.open_settings" to "Abrir ajustes de MCP",
    "mcp.no_servers" to "No hay servicios MCP configurados",
    "mcp.not_checked" to "Sin comprobar",
    "mcp.checking" to "Comprobando",
    "mcp.tools_synced" to "%d herramientas sincronizadas",
    "mcp.available_tools" to "Disponible · %d herramientas",
    "mcp.current_assistant" to "Este asistente",
    "mcp.enabled" to "Activado",
    "mcp.available" to "Disponible",
    "mcp.unavailable" to "No disponible",
    "mcp_settings.title" to "Servidores MCP",
    "mcp_settings.description" to "Sincroniza herramientas remotas y luego habilita los servidores que necesita este asistente",
    "mcp_settings.add_server" to "Agregar servidor MCP",
    "mcp_settings.unnamed_server" to "Servidor MCP sin nombre",
    "mcp_settings.delete_server" to "Eliminar servidor MCP",
    "mcp_settings.server_name" to "Nombre del servidor",
    "mcp_settings.server_name_help" to "Solo letras y números; se usa para crear nombres de herramientas estables",
    "mcp_settings.command" to "Comando",
    "mcp_settings.arguments" to "Argumentos del comando",
    "mcp_settings.arguments_help" to "Un argumento por línea",
    "mcp_settings.environment" to "Variables de entorno",
    "mcp_settings.environment_help" to "Un par CLAVE=VALOR por línea",
    "mcp_settings.server_url" to "URL del servidor",
    "mcp_settings.enable_server" to "Activar servidor",
    "mcp_settings.enable_server_help" to "Cuando está desactivado, sus herramientas no se exponen al modelo",
    "mcp_settings.sync_failed" to "Error al sincronizar herramientas MCP",
    "mcp_settings.sync_timeout" to "La sincronización de herramientas MCP agotó el tiempo tras 10 segundos",
    "mcp_settings.sync_tools" to "Sincronizar herramientas",
    "mcp_settings.collapse_tools" to "Contraer herramientas",
    "mcp_settings.manage_tools" to "Gestionar %d herramientas (%e habilitadas)",
    "mcp_settings.tool" to "Herramienta MCP",
    "assistant.message_template" to "Plantilla de mensaje",
    "assistant.template_variables" to "Variables: {{ message }}, {{ role }}, {{ date }}, {{ time }}",
    "assistant.template_invalid" to "Una plantilla Pebble válida debe incluir {{ message }}",
    "assistant.conversation_system_prompt" to "Mensaje del sistema de la conversación",
    "assistant.conversation_system_prompt_help" to "Permitir que las conversaciones individuales anulen el mensaje del sistema de este asistente",
    "assistant.conversation_lorebooks" to "Libros de lore de la conversación",
    "assistant.conversation_lorebooks_help" to "Permitir que las conversaciones individuales activen o desactiven las inyecciones de mensajes de este asistente",
    "assistant.web_search" to "Búsqueda web",
    "assistant.web_search_help" to "Activar la búsqueda web compatible con OpenAI en nuevas conversaciones por defecto",
    "assistant.local_time_tool" to "Herramienta de hora local",
    "assistant.local_time_tool_help" to "Permitir que el modelo lea la hora local y la zona horaria de este dispositivo cuando sea necesario",
    "assistant.ask_user_tool" to "Preguntar al usuario",
    "assistant.ask_user_tool_help" to "Permitir que el modelo te pida aclaraciones o confirmación cuando sea necesario",
    "assistant.max_tool_rounds" to "Máximo de rondas de llamadas a herramientas por respuesta",
    "assistant.max_tool_rounds_help" to "0 significa ilimitado; el valor predeterminado es 8",
    "assistant.agent_workspace" to "Espacio de trabajo del agente",
    "assistant.agent_workspace_help" to "Permitir que el modelo lea y escriba archivos, ejecute comandos y cargue habilidades habilitadas en el directorio seleccionado",
    "assistant.workspace_directory" to "Directorio del espacio de trabajo",
    "assistant.workspace_directory_help" to "Solo las herramientas de archivos del agente pueden acceder a este directorio; la shell local aún requiere confirmación cada vez",
    "assistant.docker_container" to "Contenedor Docker",
    "assistant.local_shell" to "Shell local",
    "assistant.docker_image" to "Imagen Docker",
    "assistant.docker_image_help" to "Por defecto, sin conexión, sin privilegios y solo monta el espacio de trabajo; la primera descarga necesita aprobación",
    "assistant.enabled_skills" to "Habilidades activadas",
    "assistant.enabled_skills_help" to "Separadas por comas; se almacenan en ~/.config/rikkahub/skills/<nombre>/SKILL.md",
    "assistant.stream_output" to "Salida en streaming",
    "assistant.stream_output_help" to "Mostrar el contenido de la respuesta a medida que llega en lugar de esperar la respuesta completa",
    "assistant.memory" to "Memoria",
    "assistant.memory_help" to "Permitir que el modelo registre, actualice y use información a largo plazo entre conversaciones",
    "assistant.global_memory" to "Memoria global compartida",
    "assistant.global_memory_help" to "Compartir un almacén de memoria con otros asistentes que usen memoria global",
    "assistant.add_global_memory" to "Agregar memoria global",
    "assistant.delete_global_memory" to "Eliminar memoria global",
    "assistant.shared_memory_content" to "Hecho o preferencia compartida",
    "assistant.memory_entries" to "Entradas de memoria",
    "assistant.add_memory" to "Agregar memoria",
    "assistant.delete_memory" to "Eliminar memoria",
    "assistant.memory_content" to "Hecho o preferencia",
    "assistant.temperature" to "Temperatura",
    "assistant.inherit_provider" to "Déjalo vacío para heredar la configuración del proveedor",
    "assistant.max_output_tokens" to "Máximo de tokens de salida",
    "assistant.context_messages" to "Mensajes de contexto",
    "assistant.keep_all_when_empty" to "Déjalo vacío para conservar todos",
    "common.add" to "Agregar",
    "role.system" to "Sistema",
    "role.user" to "Usuario",
    "role.assistant" to "Asistente",
    "assistant.preset_messages" to "Mensajes predefinidos",
    "assistant.preset_messages_help" to "Agregar mensajes de ejemplo a cada nueva conversación",
    "assistant.message" to "Mensaje",
    "assistant.delete_preset_message" to "Eliminar mensaje predefinido",
    "assistant.quick_messages" to "Mensajes rápidos",
    "assistant.quick_messages_help" to "Insertar indicaciones reutilizables desde el compositor del chat",
    "assistant.title" to "Título",
    "assistant.content" to "Contenido",
    "assistant.delete_quick_message" to "Eliminar mensaje rápido",
    "assistant.regex_transforms" to "Transformaciones regex",
    "assistant.regex_transforms_help" to "Transformar la entrada del usuario, la salida del asistente o el texto mostrado",
    "assistant.rule_name" to "Nombre de regla",
    "assistant.delete_regex_rule" to "Eliminar regla regex",
    "assistant.find_regex" to "Regex de búsqueda",
    "assistant.replace_with" to "Reemplazar por",
    "assistant.visual_only" to "Solo visual",
    "assistant.prompt_injections" to "Inyecciones de prompt / libros de lore",
    "assistant.prompt_injections_help" to "Coincidir con el contexto por palabra clave o mantener una inyección siempre activa",
    "assistant.entry_name" to "Nombre de entrada",
    "assistant.delete_injection" to "Eliminar entrada de inyección",
    "assistant.injection_content" to "Contenido de la inyección",
    "assistant.keywords" to "Palabras clave (separadas por comas)",
    "assistant.keywords_help" to "Si se deja vacío, activa «siempre activo»",
    "assistant.priority" to "Prioridad",
    "assistant.priority_help" to "Cuanto mayor sea el valor, antes se coloca",
    "assistant.scan_depth" to "Mensajes a escanear",
    "assistant.scan_depth_help" to "Se usa para la coincidencia de palabras clave",
    "assistant.injection_depth" to "Profundidad de inyección",
    "assistant.injection_depth_help" to "Contar desde el final",
    "assistant.injection_role" to "Rol de inyección",
    "assistant.before_system" to "Antes del mensaje del sistema",
    "assistant.after_system" to "Después del mensaje del sistema",
    "assistant.top_of_chat" to "Parte superior del chat",
    "assistant.bottom_of_chat" to "Parte inferior del chat",
    "assistant.at_depth" to "En profundidad",
    "assistant.always_active" to "Siempre activo",
    "assistant.regex_keywords" to "Palabras clave regex",
    "assistant.case_sensitive" to "Distinguir mayúsculas y minúsculas",
    "assistant.saved" to "Configuración del asistente guardada",
    "assistant.save" to "Guardar asistente",
    "provider.title_model" to "Modelo de título",
    "provider.title_model_help" to "Déjalo vacío para usar el modelo de chat",
    "provider.title_prompt" to "Prompt de título",
    "provider.title_prompt_help" to "Admite los marcadores {locale} y {content}",
    "provider.token_usage" to "Uso de tokens",
    "provider.token_usage_help" to "Solicitar recuentos de tokens de entrada y salida de APIs de streaming compatibles",
    "provider.use_provider_default" to "Déjalo vacío para usar el valor predeterminado del proveedor",
    "provider.system_prompt" to "Mensaje del sistema",
    "provider.balance_query" to "Consulta de saldo",
    "provider.balance_query_help" to "Consultar el saldo o la cuota de la cuenta a través de la API del proveedor",
    "provider.balance_api_path" to "Ruta de API de saldo",
    "provider.balance_api_path_help" to "Introduce una ruta relativa o una URL completa",
    "provider.balance_result_path" to "Ruta JSON de resultado",
    "provider.balance_result_path_help" to "Por ejemplo: data.balance o data.items[0].amount",
    "provider.checking_balance" to "Consultando saldo...",
    "provider.current_balance" to "Saldo actual: %s",
    "provider.balance_failed" to "Error al consultar el saldo: %s",
    "provider.check_balance" to "Consultar saldo",
    "request_overrides.headers" to "Encabezados personalizados",
    "request_overrides.headers_help" to "Agregar a las solicitudes de chat y modelo",
    "request_overrides.add_header" to "Agregar encabezado personalizado",
    "request_overrides.header" to "Encabezado",
    "request_overrides.value" to "Valor",
    "request_overrides.delete_header" to "Eliminar encabezado personalizado",
    "request_overrides.body" to "Cuerpo de solicitud personalizado",
    "request_overrides.body_help" to "Combinar JSON en campos de nivel superior de la solicitud",
    "request_overrides.add_body" to "Agregar cuerpo de solicitud",
    "request_overrides.key" to "Clave",
    "request_overrides.json_value" to "Valor JSON",
    "request_overrides.invalid_json" to "Introduce JSON válido",
    "request_overrides.delete_body" to "Eliminar cuerpo de solicitud",
    "chat.restore_snapshot" to "Restaurar instantánea del historial %d: %s",
    "chat.snapshot_messages" to "%d mensajes",
    "chat.delete_snapshot" to "Eliminar instantánea del historial",
    "jumper.top" to "Ir al inicio",
    "jumper.previous" to "Mensaje anterior",
    "jumper.next" to "Mensaje siguiente",
    "jumper.bottom" to "Ir al final",
    "tool.calling" to "En ejecución",
    "tool.completed" to "Completado",
    "tool.input" to "Entrada",
    "tool.output" to "Salida",
    "tool.result" to "Resultado de la herramienta",
    "tool.answer_required" to "Se necesita tu respuesta",
    "tool.web_search" to "Buscar en la web",
    "tool.current_time" to "Obtener hora actual",
    "tool.memory" to "Gestionar memoria",
    "tool.list_files" to "Listar archivos",
    "tool.search_files" to "Buscar archivos",
    "tool.read_file" to "Leer archivo",
    "tool.write_file" to "Escribir archivo",
    "tool.edit_file" to "Editar archivo",
    "tool.run_command" to "Ejecutar comando",
    "tool.use_skill" to "Usar habilidad",
    "model_picker.refresh_balance" to "Actualizar saldo de %s",
    "model_picker.current_model" to "Modelo actual",
    "model_capability.text" to "Texto",
    "model_capability.vision" to "Visión",
    "model_capability.reasoning" to "Razonamiento",
    "model_capability.tools" to "Herramientas",
    "attachment.remove" to "Quitar archivo adjunto",
    "mcp.unnamed_service" to "Servicio MCP sin nombre",
    "language.system_default" to "Predeterminado del sistema",
    "language.chinese" to "Chino",
    "user.you" to "Tú",
    "message.user_avatar" to "Avatar de usuario",
    "common.unnamed" to "Sin nombre",
    "theme.sakura" to "Sakura",
    "theme.ocean" to "Océano",
    "theme.forest" to "Bosque",
    "theme.sunset" to "Atardecer",
    "theme.lavender" to "Lavanda",
    "theme.slate" to "Pizarra",
    "font.system" to "Predeterminado del sistema",
    "font.sans_serif" to "Sans serif",
    "font.serif" to "Con serif",
    "font.monospace" to "Monoespaciada",
    "runtime.unknown_error" to "Error desconocido",
    "runtime.save_failed" to "Error al guardar: %s",
    "runtime.title_empty" to "El modelo de título no devolvió contenido",
    "runtime.title_failed" to "Error al generar el título",
    "runtime.suggestions_empty" to "El modelo de sugerencias no devolvió contenido",
    "runtime.suggestions_failed" to "Error al generar sugerencias de respuesta",
    "runtime.mcp_configuration_invalid" to "La configuración de MCP ya no es válida. Vuelve a seleccionar los servidores en los ajustes del asistente",
    "runtime.mcp_no_tools" to "El servidor MCP %s no proporcionó herramientas utilizables",
    "runtime.mcp_sync_failed" to "Error al sincronizar herramientas MCP: %s",
    "runtime.invalid_message_template" to "Plantilla de mensaje no válida",
    "runtime.request_failed" to "Error de solicitud",
    "runtime.not_enough_messages" to "No hay suficientes mensajes para comprimir",
    "runtime.compression_empty" to "El modelo de compresión no devolvió un resumen",
    "runtime.compression_failed" to "Error al comprimir la conversación",
    "runtime.translation_empty" to "El modelo de traducción no devolvió contenido",
    "runtime.translation_failed" to "Error de traducción",
    "runtime.export_failed" to "Error de exportación: %s",
    "runtime.import_failed" to "Error de importación: %s",
    "runtime.tool_round_limit" to "Esta respuesta alcanzó el límite de %d rondas de llamadas a herramientas. Envía otro mensaje para comenzar una nueva ejecución.",
    "runtime.add_attachment_failed" to "No se pudo agregar el archivo adjunto",
    "defaults.new_provider" to "Proveedor nuevo",
    "defaults.new_assistant" to "Asistente nuevo",
    "file.import_backup" to "Importar copia de seguridad de RikkaHub",
    "file.imported_backup" to "Copia de seguridad importada desde %s",
    "file.choose_attachments" to "Agregar imágenes, audio, texto o documentos",
    "mermaid.diagram" to "Diagrama",
    "mermaid.code" to "Código",
    "mermaid.save_image" to "Guardar imagen",
    "mermaid.download" to "Descargar",
    "mermaid.fullscreen" to "Pantalla completa",
    "mermaid.exit_fullscreen" to "Salir de pantalla completa",
    "provider.connection_success" to "Conectado · %d modelos disponibles"
)
