package me.rerere.rikkahub.desktop

internal val TraditionalChineseDesktopTranslations = mapOf(
        "settings.language" to "語言", "settings.language_description" to "選擇桌面應用程式顯示語言",
        "settings.title" to "設定", "settings.subtitle" to "外觀、互動與模型服務",
        "settings.back" to "返回", "settings.color_mode" to "色彩模式",
        "settings.color_mode_description" to "跟隨系統，或固定使用淺色或深色主題",
        "settings.system" to "跟隨系統", "settings.light" to "淺色", "settings.dark" to "深色",
        "settings.theme_color" to "主題色", "settings.theme_color_description" to "為介面選擇一套強調色和配套的明暗色階",
        "settings.font" to "介面字型", "settings.font_description" to "%s；程式碼區塊保持等寬字型",
        "settings.chat_font_size" to "聊天字型大小",
        "sidebar.welcome" to "歡迎回來", "sidebar.new_chat" to "新增對話",
        "sidebar.search_chats" to "搜尋對話", "sidebar.back_to_chats" to "返回對話",
        "sidebar.favorite_messages" to "收藏訊息", "sidebar.search" to "搜尋",
        "sidebar.all_assistants" to "全部助手", "sidebar.all_tags" to "全部標籤",
        "sidebar.chats" to "對話", "chat.open_conversations" to "開啟對話列表",
        "chat.options" to "對話選項", "chat.rename" to "重新命名",
        "chat.export_markdown" to "匯出 Markdown", "chat.generate_title" to "產生標題",
        "chat.statistics" to "對話統計", "chat.generate_suggestions" to "產生回覆建議",
        "chat.compress_history" to "壓縮歷史", "chat.set_system_prompt" to "設定系統提示詞",
        "chat.edit_system_prompt" to "編輯系統提示詞", "chat.enable_lorebooks" to "啟用對話世界書",
        "chat.disable_lorebooks" to "停用對話世界書", "chat.move_to_folder" to "移至資料夾",
        "chat.uncategorized" to "未分類", "chat.new_folder" to "新增資料夾",
        "chat.close" to "關閉", "message.sources" to "來源",
        "message.source_number" to "來源 %d", "message.input_tokens" to "輸入 Token",
        "message.output_tokens" to "輸出 Token", "message.cached_tokens" to "快取 Token",
        "message.previous_version" to "上一個版本", "message.next_version" to "下一個版本",
        "message.copy" to "複製", "message.fork" to "從此處分支",
        "message.regenerate" to "重新產生", "message.translate" to "翻譯",
        "message.favorite" to "收藏", "message.unfavorite" to "取消收藏",
        "message.edit" to "編輯", "message.delete" to "刪除",
        "empty_chat.greeting" to "有什麼可以幫你的？",
        "composer.collapse" to "收合輸入框", "composer.expand" to "展開輸入框",
        "composer.add_attachment" to "新增附件", "composer.enable_web_search" to "啟用網路搜尋",
        "composer.disable_web_search" to "停用網路搜尋", "composer.quick_messages" to "快捷訊息",
        "composer.manage_assistants" to "管理助手與標籤", "composer.stop_generation" to "停止產生",
        "composer.send" to "傳送；長按只新增訊息", "settings.show_user_avatar" to "顯示使用者頭像",
        "settings.show_user_avatar_description" to "在使用者訊息旁顯示頭像",
        "settings.user_nickname" to "使用者暱稱", "settings.user_nickname_description" to "顯示在使用者訊息旁；留空時使用「你」",
        "settings.user_nickname_placeholder" to "你", "settings.show_model_icon" to "顯示模型圖示",
        "settings.show_model_icon_description" to "在助手訊息旁顯示模型圖示",
        "settings.show_model_name" to "顯示模型名稱", "settings.show_model_name_description" to "在助手訊息上方顯示模型名稱",
        "settings.assistant_bubble" to "助手氣泡", "settings.assistant_bubble_description" to "用填充氣泡顯示助手文字",
        "settings.message_timestamp" to "訊息時間", "settings.message_timestamp_description" to "在每條訊息標題中顯示建立時間",
        "settings.reasoning" to "思考內容", "settings.reasoning_description" to "顯示相容模型回傳的推理內容",
        "settings.collapse_reasoning" to "完成後收合思考內容", "settings.collapse_reasoning_description" to "僅在生成進行中展開推理內容",
        "settings.code_wrap" to "程式碼區塊自動換行", "settings.code_wrap_description" to "長程式碼行自動換行，而不是橫向捲動",
        "settings.chinese_typography" to "中文排版最佳化", "settings.chinese_typography_description" to "在中文與西文、數字或符號之間自動新增間距",
        "settings.send_on_enter" to "按 Enter 傳送", "settings.send_on_enter_description" to "關閉後，Ctrl+Enter 傳送，Enter 換行",
        "settings.auto_scroll" to "自動捲動", "settings.auto_scroll_description" to "生成時跟隨新的推理和回覆內容",
        "settings.message_navigation" to "訊息導航", "settings.message_navigation_description" to "捲動訊息後顯示跳至頂端、上一個、下一個和底部的按鈕",
        "settings.message_navigation_left" to "訊息導航置左", "settings.message_navigation_left_description" to "預設顯示在訊息區域右側",
        "settings.export_backup" to "匯出備份", "settings.export_backup_description" to "將服務商、助手、偏好設定和對話儲存為 JSON",
        "settings.export" to "匯出", "settings.import_backup" to "匯入備份",
        "settings.import_backup_description" to "使用 RikkaHub 備份替換目前桌面端資料",
        "settings.import" to "匯入", "settings.reset_data" to "重設全部資料",
        "settings.reset_data_description" to "刪除本機的服務商、助手、偏好設定和對話。此操作無法還原。",
        "settings.reset" to "重設", "settings.web_search" to "網路搜尋服務",
        "settings.web_search_description" to "設定後優先使用外部搜尋服務；未設定時使用模型服務商的原生搜尋",
        "settings.searxng_url" to "SearXNG 網址", "settings.api_key" to "API 金鑰",
        "settings.search_result_count" to "每次搜尋回傳 %d 筆結果",
        "settings.test_search" to "測試搜尋", "settings.search_test_success" to "網路搜尋連線正常",
        "settings.search_test_failed" to "搜尋測試失敗", "settings.add_assistant" to "新增助手",
        "settings.assistant_name" to "助手名稱", "settings.copy_assistant" to "複製助手",
        "settings.delete_assistant" to "刪除助手", "settings.tags" to "標籤（逗號分隔）",
        "settings.model_inherit" to "模型（留空使用服務商預設值）", "settings.select_model" to "選擇模型",
        "settings.system_prompt_inherit" to "系統提示詞（留空使用服務商預設值）", "settings.apply_preset" to "套用預設",
        "settings.add_provider" to "新增服務商", "settings.provider_name" to "服務商名稱",
        "settings.delete_provider" to "刪除服務商", "settings.base_url" to "基礎 URL",
        "settings.hide_api_key" to "隱藏 API 金鑰", "settings.show_api_key" to "顯示 API 金鑰",
        "settings.model" to "模型", "settings.select_discovered_model" to "選擇已發現的模型",
        "settings.test_and_fetch_models" to "測試並取得模型", "settings.provider_saved" to "服務商設定已儲存",
        "settings.save_provider" to "儲存服務商", "settings.back_to_chat" to "返回對話",
        "settings.reset_confirmation_title" to "重設全部資料？", "settings.reset_confirmation_description" to "這會永久刪除桌面端的服務商金鑰、助手、設定和所有對話。",
        "settings.confirm_reset" to "確認重設", "common.cancel" to "取消",
        "common.save" to "儲存", "common.submit" to "提交",
        "common.expand" to "展開", "common.collapse" to "收合",
        "message.thinking" to "思考中...", "message.translation" to "翻譯",
        "attachment.audio" to "音訊", "timeline.execution" to "執行過程",
        "timeline.expand_execution" to "展開執行過程", "timeline.collapse_execution" to "收合執行過程",
        "timeline.expand_steps" to "展開 %d 個步驟", "timeline.reasoning" to "思考過程",
        "timeline.reasoning_duration" to "思考了 %s 秒", "timeline.today" to "今天",
        "timeline.yesterday" to "昨天", "timeline.day_before_yesterday" to "前天",
        "timeline.days_ago" to "%d 天前", "sidebar.recent" to "最近",
        "sidebar.most_active" to "最常用", "sidebar.sort_recent" to "按最近時間",
        "sidebar.sort_most_active" to "按使用頻率", "sidebar.tool_call" to "工具呼叫",
        "sidebar.rename_folder" to "重新命名資料夾", "common.new" to "新增",
        "conversation.branch" to "對話分支", "conversation.pinned" to "已置頂",
        "conversation.pin" to "置頂", "conversation.unpin" to "取消置頂",
        "conversation.move_to_chat" to "移至聊天", "conversation.move_to_folder" to "移至 %s",
        "dialog.rename_conversation" to "重新命名對話", "dialog.conversation_system_prompt" to "對話系統提示詞",
        "dialog.compress_history" to "壓縮對話歷史", "dialog.compress_history_description" to "將較早訊息產生摘要，並保留最近訊息。壓縮前的完整歷史會儲存為可還原快照。",
        "dialog.target_tokens" to "目標 Token 數", "dialog.keep_recent_messages" to "保留最近訊息數（共 %d 條）",
        "dialog.additional_instructions" to "附加說明（選填）", "dialog.compress" to "壓縮",
        "dialog.translate_message" to "翻譯訊息", "dialog.target_language" to "目標語言",
        "stats.messages" to "訊息", "stats.attachments" to "附件",
        "stats.characters" to "文字與思考鏈字元", "stats.created_at" to "建立時間",
        "stats.updated_at" to "更新時間", "file.add_attachments" to "新增附件",
        "file.parent_directory" to "上層目錄", "file.selected" to "已選取",
        "file.add_count" to "新增（%d）", "file.file_name" to "檔案名稱",
        "file.export_conversation_markdown" to "將對話匯出為 Markdown",
        "file.export_backup" to "匯出 RikkaHub 備份",
        "agent.approval_request" to "Agent 請求此操作，是否允許？",
        "agent.docker_network_warning" to "將在受限 Docker 容器中執行，並暫時使用宿主網路；完成後恢復到無外網的隔離容器。",
        "agent.docker_warning" to "將在受限 Docker 容器中執行；容器僅掛載選定工作區。",
        "agent.local_shell_warning" to "本機 Shell 以目前使用者權限執行；請確認命令及其影響。",
        "agent.confirm_impact" to "請確認命令及其影響。",
        "agent.image_pull_warning" to "將從映像存放庫下載內容到本機 Docker 快取。",
        "agent.skill_warning" to "Skill 指令可能影響後續 Agent 行為。",
        "agent.write_warning" to "檔案修改限制在已選定的工作區目錄內。",
        "agent.remember_docker_shell" to "本對話內自動批准此工作區的 Docker 命令",
        "agent.remember_docker_network" to "本對話內自動批准此工作區的 Docker 連網命令",
        "agent.remember_image_pull" to "本對話內自動批准此映像下載",
        "agent.remember_operation" to "本對話內自動批准此類操作",
        "agent.allow" to "允許", "agent.deny" to "拒絕",
        "settings.navigation" to "設定分類", "settings.section.general" to "一般設定",
        "settings.section.messages" to "訊息顯示", "settings.section.interaction" to "互動",
        "settings.section.data" to "資料、備份與網路搜尋", "settings.section.assistants" to "助手",
        "settings.section.providers" to "模型與服務", "composer.placeholder" to "傳送訊息給 RikkaHub",
        "model_picker.title" to "選擇模型", "model_picker.filter" to "篩選模型",
        "model_picker.reasoning" to "推理強度", "model_picker.default" to "預設",
        "model_picker.low" to "低", "model_picker.medium" to "中", "model_picker.high" to "高",
        "model_picker.manage_providers" to "管理服務商", "model_picker.checking_balance" to "正在查詢餘額",
        "model_picker.balance" to "餘額：%s", "model_picker.balance_failed" to "餘額查詢失敗",
        "mcp.manage" to "管理 MCP 服務", "mcp.check" to "檢查可用性",
        "mcp.title" to "MCP 服務", "mcp.services_for_assistant" to "目前助手使用 %d 個服務",
        "mcp.check_all" to "檢查全部", "mcp.open_settings" to "開啟 MCP 設定",
        "mcp.no_servers" to "尚未設定 MCP 服務", "mcp.not_checked" to "尚未檢查",
        "mcp.checking" to "檢查中", "mcp.tools_synced" to "已同步 %d 個工具",
        "mcp.available_tools" to "可用 · %d 個工具", "mcp.current_assistant" to "目前助手",
        "mcp.enabled" to "啟用", "mcp.available" to "可用", "mcp.unavailable" to "不可用",
        "mcp_settings.title" to "MCP 伺服器", "mcp_settings.description" to "同步遠端工具後，為此助手啟用所需伺服器",
        "mcp_settings.add_server" to "新增 MCP 伺服器", "mcp_settings.unnamed_server" to "未命名 MCP 伺服器",
        "mcp_settings.delete_server" to "刪除 MCP 伺服器", "mcp_settings.server_name" to "伺服器名稱",
        "mcp_settings.server_name_help" to "僅允許字母和數字，用於產生穩定的工具名",
        "mcp_settings.command" to "啟動命令", "mcp_settings.arguments" to "命令參數",
        "mcp_settings.arguments_help" to "每行一個參數", "mcp_settings.environment" to "環境變數",
        "mcp_settings.environment_help" to "每行一個 KEY=VALUE", "mcp_settings.server_url" to "伺服器 URL",
        "mcp_settings.enable_server" to "啟用伺服器", "mcp_settings.enable_server_help" to "關閉後不會向模型暴露其中的工具",
        "mcp_settings.sync_failed" to "同步 MCP 工具失敗", "mcp_settings.sync_tools" to "同步工具",
        "mcp_settings.collapse_tools" to "收合工具", "mcp_settings.manage_tools" to "管理 %d 個工具（已啟用 %e 個）",
        "mcp_settings.tool" to "MCP 工具", "assistant.message_template" to "訊息範本",
        "assistant.template_variables" to "變數：{{ message }}、{{ role }}、{{ date }}、{{ time }}",
        "assistant.template_invalid" to "需要包含 {{ message }} 的有效 Pebble 範本",
        "assistant.conversation_system_prompt" to "對話系統提示詞",
        "assistant.conversation_system_prompt_help" to "允許單個對話覆蓋此助手的系統提示詞",
        "assistant.conversation_lorebooks" to "對話世界書",
        "assistant.conversation_lorebooks_help" to "允許單個對話啟用或停用此助手的提示詞注入",
        "assistant.web_search" to "網路搜尋",
        "assistant.web_search_help" to "預設在新對話中啟用相容 OpenAI 的網路搜尋",
        "assistant.local_time_tool" to "本機時間工具",
        "assistant.local_time_tool_help" to "允許模型按需讀取此裝置的本機時間和時區",
        "assistant.ask_user_tool" to "主動提問",
        "assistant.ask_user_tool_help" to "允許模型在需要澄清資訊或確認時向你提問",
        "assistant.max_tool_rounds" to "每次回覆的工具呼叫輪數上限",
        "assistant.max_tool_rounds_help" to "0 表示不限制；預設值為 8",
        "assistant.agent_workspace" to "Agent 工作區",
        "assistant.agent_workspace_help" to "允許模型在選定目錄內讀寫檔案、執行命令並載入已啟用的 Skills",
        "assistant.workspace_directory" to "工作區目錄",
        "assistant.workspace_directory_help" to "僅允許 Agent 檔案工具存取此目錄；本機 shell 每次仍會要求確認",
        "assistant.docker_container" to "Docker 容器", "assistant.local_shell" to "本機 Shell",
        "assistant.docker_image" to "Docker 映像",
        "assistant.docker_image_help" to "預設斷網、無特權、僅掛載工作區；首次拉取需核准",
        "assistant.enabled_skills" to "已啟用 Skills",
        "assistant.enabled_skills_help" to "逗號分隔；目錄位於 ~/.config/rikkahub/skills/<名稱>/SKILL.md",
        "assistant.stream_output" to "串流輸出",
        "assistant.stream_output_help" to "即時顯示回覆內容，而不是等待完整回覆",
        "assistant.memory" to "記憶",
        "assistant.memory_help" to "允許模型記錄、更新和使用跨對話的長期資訊",
        "assistant.global_memory" to "全域共享記憶",
        "assistant.global_memory_help" to "與其他啟用共享記憶的助手共用記憶庫",
        "assistant.add_global_memory" to "新增全域記憶",
        "assistant.delete_global_memory" to "刪除全域記憶",
        "assistant.shared_memory_content" to "共享事實或偏好",
        "assistant.memory_entries" to "記憶項目",
        "assistant.add_memory" to "新增記憶",
        "assistant.delete_memory" to "刪除記憶",
        "assistant.memory_content" to "事實或偏好",
        "assistant.temperature" to "溫度",
        "assistant.inherit_provider" to "留空繼承服務商設定",
        "assistant.max_output_tokens" to "最大輸出 Token",
        "assistant.context_messages" to "上下文訊息數",
        "assistant.keep_all_when_empty" to "留空保留全部"
        ,"common.add" to "新增",
        "role.system" to "系統", "role.user" to "使用者", "role.assistant" to "助手",
        "assistant.preset_messages" to "預設訊息",
        "assistant.preset_messages_help" to "在每個新對話中新增範例訊息",
        "assistant.message" to "訊息",
        "assistant.delete_preset_message" to "刪除預設訊息",
        "assistant.quick_messages" to "快捷訊息",
        "assistant.quick_messages_help" to "從聊天輸入框插入可重複使用提示詞",
        "assistant.title" to "標題", "assistant.content" to "內容",
        "assistant.delete_quick_message" to "刪除快捷訊息",
        "assistant.regex_transforms" to "正則轉換",
        "assistant.regex_transforms_help" to "轉換使用者輸入、助手輸出或顯示文字",
        "assistant.rule_name" to "規則名稱",
        "assistant.delete_regex_rule" to "刪除正則規則",
        "assistant.find_regex" to "符合的正則表示式",
        "assistant.replace_with" to "取代為",
        "assistant.visual_only" to "僅視覺顯示",
        "assistant.prompt_injections" to "提示詞注入 / 世界書",
        "assistant.prompt_injections_help" to "按關鍵字比對上下文，或設為常駐注入",
        "assistant.entry_name" to "條目名稱",
        "assistant.delete_injection" to "刪除注入條目",
        "assistant.injection_content" to "注入內容",
        "assistant.keywords" to "關鍵字（逗號分隔）",
        "assistant.keywords_help" to "留空時請開啟常駐",
        "assistant.priority" to "優先順序",
        "assistant.priority_help" to "數值越大越靠前",
        "assistant.scan_depth" to "掃描訊息數",
        "assistant.scan_depth_help" to "用於關鍵字比對",
        "assistant.injection_depth" to "注入深度",
        "assistant.injection_depth_help" to "從末尾倒數",
        "assistant.injection_role" to "注入角色",
        "assistant.before_system" to "系統前", "assistant.after_system" to "系統後",
        "assistant.top_of_chat" to "聊天頂部", "assistant.bottom_of_chat" to "聊天底部",
        "assistant.at_depth" to "指定深度", "assistant.always_active" to "常駐",
        "assistant.regex_keywords" to "正則關鍵字",
        "assistant.case_sensitive" to "區分大小寫",
        "assistant.saved" to "助手設定已儲存",
        "assistant.save" to "儲存助手"
        ,"provider.title_model" to "標題模型",
        "provider.title_model_help" to "留空時使用聊天模型",
        "provider.title_prompt" to "標題提示詞",
        "provider.title_prompt_help" to "支援 {locale} 與 {content} 佔位符",
        "provider.token_usage" to "Token 用量",
        "provider.token_usage_help" to "從相容的串流式 API 請求輸入和輸出 Token 計數",
        "provider.use_provider_default" to "留空使用服務商預設值",
        "provider.system_prompt" to "系統提示詞",
        "provider.balance_query" to "餘額查詢",
        "provider.balance_query_help" to "透過服務商 API 查詢帳戶餘額或額度",
        "provider.balance_api_path" to "餘額 API 路徑",
        "provider.balance_api_path_help" to "可填寫相對路徑或完整 URL",
        "provider.balance_result_path" to "結果 JSON 路徑",
        "provider.balance_result_path_help" to "例如 data.balance 或 data.items[0].amount",
        "provider.checking_balance" to "正在查詢餘額...",
        "provider.current_balance" to "目前餘額：%s",
        "provider.balance_failed" to "餘額查詢失敗：%s",
        "provider.check_balance" to "查詢餘額",
        "request_overrides.headers" to "自訂請求標頭",
        "request_overrides.headers_help" to "新增至聊天和模型請求中",
        "request_overrides.add_header" to "新增自訂請求標頭",
        "request_overrides.header" to "請求標頭", "request_overrides.value" to "值",
        "request_overrides.delete_header" to "刪除自訂請求標頭",
        "request_overrides.body" to "自訂請求主體",
        "request_overrides.body_help" to "將 JSON 合併至請求頂層欄位",
        "request_overrides.add_body" to "新增自訂請求主體",
        "request_overrides.key" to "鍵", "request_overrides.json_value" to "JSON 值",
        "request_overrides.invalid_json" to "請輸入有效 JSON",
        "request_overrides.delete_body" to "刪除自訂請求主體"
        ,"chat.restore_snapshot" to "還原歷史快照 %d：%s",
        "chat.snapshot_messages" to "%d 條訊息",
        "chat.delete_snapshot" to "刪除歷史快照",
        "jumper.top" to "跳至頂端", "jumper.previous" to "上一則訊息",
        "jumper.next" to "下一則訊息", "jumper.bottom" to "跳至底端",
        "tool.calling" to "正在呼叫", "tool.completed" to "呼叫完成",
        "tool.input" to "輸入", "tool.output" to "輸出", "tool.result" to "工具結果",
        "tool.answer_required" to "需要你的回答",
        "tool.web_search" to "搜尋網頁", "tool.current_time" to "取得時間",
        "tool.memory" to "管理記憶", "tool.list_files" to "列出檔案",
        "tool.search_files" to "搜尋檔案", "tool.read_file" to "讀取檔案",
        "tool.write_file" to "寫入檔案", "tool.edit_file" to "編輯檔案",
        "tool.run_command" to "執行命令", "tool.use_skill" to "使用技能"
        ,"model_picker.refresh_balance" to "重新整理 %s 餘額",
        "model_picker.current_model" to "目前模型",
        "model_capability.text" to "文字", "model_capability.vision" to "視覺",
        "model_capability.reasoning" to "推理", "model_capability.tools" to "工具",
        "attachment.remove" to "移除附件", "mcp.unnamed_service" to "未命名 MCP 服務",
        "language.chinese" to "中文", "user.you" to "你",
        "message.user_avatar" to "使用者頭像", "common.unnamed" to "未命名",
        "theme.sakura" to "櫻花", "theme.ocean" to "海洋", "theme.forest" to "森林",
        "theme.sunset" to "落日", "theme.lavender" to "薰衣草", "theme.slate" to "石墨",
        "font.system" to "系統預設", "font.sans_serif" to "無襯線",
        "font.serif" to "襯線", "font.monospace" to "等寬"
        ,"runtime.unknown_error" to "未知錯誤",
        "runtime.save_failed" to "儲存失敗：%s",
        "runtime.title_empty" to "標題模型沒有回傳內容",
        "runtime.title_failed" to "產生標題失敗",
        "runtime.suggestions_empty" to "建議模型沒有回傳內容",
        "runtime.suggestions_failed" to "產生回覆建議失敗",
        "runtime.mcp_configuration_invalid" to "MCP 設定已失效，請在助手設定中重新選擇伺服器",
        "runtime.mcp_no_tools" to "MCP 伺服器 %s 未提供可用工具",
        "runtime.mcp_sync_failed" to "MCP 工具同步失敗：%s",
        "runtime.invalid_message_template" to "無效的訊息範本",
        "runtime.request_failed" to "請求失敗",
        "runtime.not_enough_messages" to "沒有足夠的訊息可壓縮",
        "runtime.compression_empty" to "壓縮模型沒有回傳摘要",
        "runtime.compression_failed" to "壓縮對話失敗",
        "runtime.translation_empty" to "翻譯模型沒有回傳內容",
        "runtime.translation_failed" to "翻譯失敗",
        "runtime.export_failed" to "匯出失敗：%s",
        "runtime.import_failed" to "匯入失敗：%s"
        ,"runtime.tool_round_limit" to "本次回覆已達到 %d 輪工具呼叫上限。請繼續傳送訊息以開始新的處理。",
        "runtime.add_attachment_failed" to "無法新增附件"
        ,"defaults.new_provider" to "新服務商",
        "defaults.new_assistant" to "新助手",
        "file.import_backup" to "匯入 RikkaHub 備份",
        "file.imported_backup" to "已從 %s 匯入備份",
        "file.choose_attachments" to "新增圖片、音訊、文字或文件"
        ,"provider.connection_success" to "已連線 · 可用 %d 個模型"
)
