package me.rerere.rikkahub.desktop

internal val KoreanDesktopTranslations = mapOf(
        "settings.language" to "언어", "settings.language_description" to "데스크톱 앱의 표시 언어를 선택합니다",
        "settings.title" to "설정", "settings.subtitle" to "모양, 상호작용 및 모델 서비스",
        "settings.back" to "뒤로", "settings.color_mode" to "색상 모드",
        "settings.color_mode_description" to "시스템을 따르거나 밝은/어두운 테마를 고정합니다",
        "settings.system" to "시스템", "settings.light" to "밝게", "settings.dark" to "어둡게",
        "settings.theme_color" to "테마 색상", "settings.theme_color_description" to "인터페이스의 악센트 색상과 톤을 선택합니다",
        "settings.font" to "인터페이스 글꼴", "settings.font_description" to "%s; 코드 블록은 고정폭 글꼴을 유지합니다",
        "settings.chat_font_size" to "채팅 글꼴 크기",
        "sidebar.welcome" to "다시 오셨군요", "sidebar.new_chat" to "새 채팅",
        "sidebar.search_chats" to "채팅 검색", "sidebar.back_to_chats" to "채팅으로 돌아가기",
        "sidebar.favorite_messages" to "즐겨찾는 메시지", "sidebar.search" to "검색",
        "sidebar.all_assistants" to "모든 어시스턴트", "sidebar.all_tags" to "모든 태그",
        "sidebar.chats" to "채팅", "chat.open_conversations" to "대화 열기",
        "chat.options" to "대화 옵션", "chat.rename" to "이름 변경",
        "chat.export_markdown" to "Markdown 내보내기", "chat.generate_title" to "제목 생성",
        "chat.statistics" to "대화 통계", "chat.generate_suggestions" to "답변 제안 생성",
        "chat.compress_history" to "기록 압축", "chat.set_system_prompt" to "시스템 프롬프트 설정",
        "chat.edit_system_prompt" to "시스템 프롬프트 편집", "chat.enable_lorebooks" to "대화 로어북 사용",
        "chat.disable_lorebooks" to "대화 로어북 끄기", "chat.move_to_folder" to "폴더로 이동",
        "chat.uncategorized" to "미분류", "chat.new_folder" to "새 폴더",
        "chat.close" to "닫기", "message.sources" to "출처",
        "message.source_number" to "출처 %d", "message.input_tokens" to "입력 토큰",
        "message.output_tokens" to "출력 토큰", "message.cached_tokens" to "캐시된 토큰",
        "message.previous_version" to "이전 버전", "message.next_version" to "다음 버전",
        "message.copy" to "복사", "message.fork" to "여기서 분기",
        "message.regenerate" to "다시 생성", "message.translate" to "번역",
        "message.favorite" to "즐겨찾기", "message.unfavorite" to "즐겨찾기 해제",
        "message.edit" to "편집", "message.delete" to "삭제",
        "empty_chat.greeting" to "무엇을 도와드릴까요?",
        "composer.collapse" to "작성기 접기", "composer.expand" to "작성기 펼치기",
        "composer.add_attachment" to "첨부 파일 추가", "composer.enable_web_search" to "웹 검색 사용",
        "composer.disable_web_search" to "웹 검색 끄기", "composer.quick_messages" to "빠른 메시지",
        "composer.manage_assistants" to "어시스턴트와 태그 관리", "composer.stop_generation" to "생성 중지",
        "composer.send" to "보내기; 길게 눌러 답변 없이 추가",
        "settings.show_user_avatar" to "사용자 아바타 표시", "settings.show_user_avatar_description" to "사용자 메시지 옆에 아바타를 표시합니다",
        "settings.user_nickname" to "사용자 별명", "settings.user_nickname_description" to "사용자 메시지 옆에 표시. 비어 있으면 '나'",
        "settings.user_nickname_placeholder" to "나", "settings.show_model_icon" to "모델 아이콘 표시",
        "settings.show_model_icon_description" to "어시스턴트 메시지 옆에 모델 아이콘을 표시합니다",
        "settings.show_model_name" to "모델 이름 표시", "settings.show_model_name_description" to "어시스턴트 메시지 위에 모델 이름을 표시합니다",
        "settings.assistant_bubble" to "어시스턴트 말풍선", "settings.assistant_bubble_description" to "채워진 말풍선으로 어시스턴트 텍스트 표시",
        "settings.message_timestamp" to "메시지 시간", "settings.message_timestamp_description" to "각 메시지 헤더에 생성 시간을 표시합니다",
        "settings.reasoning" to "추론 내용", "settings.reasoning_description" to "호환 모델이 반환하는 추론을 표시합니다",
        "settings.collapse_reasoning" to "완료 후 추론 접기", "settings.collapse_reasoning_description" to "응답 생성 중에만 추론을 펼칩니다",
        "settings.code_wrap" to "코드 블록 줄바꿈", "settings.code_wrap_description" to "가로 스크롤 대신 긴 코드 줄을 줄바꿈합니다",
        "settings.chinese_typography" to "중국어 조판", "settings.chinese_typography_description" to "중국어와 라틴 문자, 숫자, 기호 사이에 간격을 추가합니다",
        "settings.send_on_enter" to "Enter로 전송", "settings.send_on_enter_description" to "꺼져 있으면 Ctrl+Enter 전송, Enter 줄바꿈",
        "settings.auto_scroll" to "자동 스크롤", "settings.auto_scroll_description" to "생성 중에 새로운 추론과 응답을 따라갑니다",
        "settings.message_navigation" to "메시지 탐색", "settings.message_navigation_description" to "스크롤 후 맨 위, 이전, 다음, 맨 아래 버튼을 표시합니다",
        "settings.message_navigation_left" to "메시지 탐색을 왼쪽에 표시", "settings.message_navigation_left_description" to "기본적으로 메시지 영역 오른쪽에 표시됩니다",
        "settings.export_backup" to "백업 내보내기", "settings.export_backup_description" to "제공업체, 어시스턴트, 기본 설정, 채팅을 JSON으로 저장",
        "settings.export" to "내보내기", "settings.import_backup" to "백업 가져오기",
        "settings.import_backup_description" to "RikkaHub 백업으로 현재 데스크톱 데이터를 교체합니다",
        "settings.import" to "가져오기", "settings.reset_data" to "모든 데이터 초기화",
        "settings.reset_data_description" to "로컬 제공업체, 어시스턴트, 기본 설정, 채팅을 삭제합니다. 되돌릴 수 없습니다.",
        "settings.reset" to "초기화", "settings.web_search" to "웹 검색 서비스",
        "settings.web_search_description" to "설정 시 외부 검색 서비스 사용. 미설정 시 모델 제공업체 네이티브 검색",
        "settings.searxng_url" to "SearXNG URL", "settings.api_key" to "API 키",
        "settings.search_result_count" to "검색당 결과 %d개", "settings.test_search" to "검색 테스트",
        "settings.search_test_success" to "웹 검색 연결이 정상입니다", "settings.search_test_failed" to "검색 테스트에 실패했습니다",
        "settings.add_assistant" to "어시스턴트 추가", "settings.assistant_name" to "어시스턴트 이름",
        "settings.copy_assistant" to "어시스턴트 복사", "settings.delete_assistant" to "어시스턴트 삭제",
        "settings.tags" to "태그(쉼표로 구분)", "settings.model_inherit" to "모델(비워 두면 제공업체 기본값 사용)",
                                    "settings.select_model" to "모델 선택", "settings.system_prompt_inherit" to "시스템 프롬프트(비워 두면 제공업체 기본값 사용)",
                                    "settings.apply_preset" to "프리셋 적용", "settings.add_provider" to "제공업체 추가",
                                    "settings.provider_name" to "제공업체 이름", "settings.delete_provider" to "제공업체 삭제",
                                    "settings.base_url" to "기본 URL", "settings.hide_api_key" to "API 키 숨기기",
                                    "settings.show_api_key" to "API 키 표시", "settings.model" to "모델",
                                    "settings.select_discovered_model" to "발견된 모델 선택", "settings.test_and_fetch_models" to "연결 테스트 및 모델 가져오기",
                                    "settings.provider_saved" to "제공업체 설정이 저장되었습니다", "settings.save_provider" to "제공업체 저장",
                                    "settings.back_to_chat" to "채팅으로 돌아가기", "settings.reset_confirmation_title" to "모든 데이터를 초기화할까요?",
                                    "settings.reset_confirmation_description" to "데스크톱의 제공업체 비밀, 어시스턴트, 설정 및 모든 대화를 영구적으로 삭제합니다.",
                                    "settings.confirm_reset" to "데이터 초기화", "common.cancel" to "취소",
                                    "common.save" to "저장", "common.submit" to "제출",
                                    "common.expand" to "펼치기 ", "common.collapse" to "접기 ",
                                    "message.thinking" to "생각 중...", "message.translation" to "번역",
                                    "attachment.audio" to "오디오", "timeline.execution" to "실행 과정",
                                    "timeline.expand_execution" to "실행 과정 펼치기", "timeline.collapse_execution" to "실행 과정 접기",
                                    "timeline.expand_steps" to "%d단계 펼치기", "timeline.reasoning" to "추론",
                                    "timeline.reasoning_duration" to "%s초간 추론함", "timeline.today" to "오늘",
                                    "timeline.yesterday" to "어제", "timeline.day_before_yesterday" to "그제",
                                    "timeline.days_ago" to "%d일 전", "sidebar.recent" to "최근",
                                    "sidebar.most_active" to "가장 많이 사용", "sidebar.sort_recent" to "최근 활동순",
                                    "sidebar.sort_most_active" to "사용 빈도순", "sidebar.tool_call" to "도구 호출",
                                    "sidebar.rename_folder" to "폴더 이름 변경", "common.new" to "새로 만들기",
                                    "conversation.branch" to "대화 분기", "conversation.pinned" to "고정됨",
                                    "conversation.pin" to "고정", "conversation.unpin" to "고정 해제",
                                    "conversation.move_to_chat" to "채팅으로 이동", "conversation.move_to_folder" to "%s(으)로 이동",
                                    "dialog.rename_conversation" to "대화 이름 변경", "dialog.conversation_system_prompt" to "대화 시스템 프롬프트",
                                    "dialog.compress_history" to "대화 기록 압축", "dialog.compress_history_description" to "이전 메시지를 요약하고 최근 메시지를 유지합니다. 전체 기록은 복원 가능한 스냅샷으로 저장됩니다.",
                                    "dialog.target_tokens" to "목표 토큰", "dialog.keep_recent_messages" to "최근 메시지 유지(전체 %d개)",
                                    "dialog.additional_instructions" to "추가 지침(선택 사항)", "dialog.compress" to "압축",
                                    "dialog.translate_message" to "메시지 번역", "dialog.target_language" to "대상 언어",
                                    "stats.messages" to "메시지", "stats.attachments" to "첨부",
                                    "stats.characters" to "텍스트 및 추론 문자 수", "stats.created_at" to "생성 시간",
                                    "stats.updated_at" to "업데이트 시간", "file.add_attachments" to "첨부 파일 추가",
                                    "file.parent_directory" to "상위 디렉터리", "file.selected" to "선택됨",
                                    "file.add_count" to "추가 (%d)", "file.file_name" to "파일 이름",
                                    "file.export_conversation_markdown" to "대화를 Markdown으로 내보내기",
                                    "file.export_backup" to "RikkaHub 백업 내보내기",
                                    "agent.approval_request" to "에이전트가 이 작업을 요청합니다. 허용할까요?",
                                    "agent.docker_network_warning" to "제한된 Docker 컨테이너에서 임시 호스트 네트워킹으로 실행된 후 격리된 오프라인 컨테이너로 돌아갑니다.",
                                    "agent.docker_warning" to "선택한 작업 공간만 마운트한 제한된 Docker 컨테이너에서 실행됩니다.",
                                    "agent.local_shell_warning" to "로컬 셸은 현재 사용자 권한으로 실행됩니다. 명령과 영향을 확인하세요.",
                                    "agent.confirm_impact" to "명령과 그 영향을 확인하세요.",
                                    "agent.image_pull_warning" to "이미지 레지스트리에서 로컬 Docker 캐시로 콘텐츠를 다운로드합니다.",
                                    "agent.skill_warning" to "스킬 지침은 이후 에이전트 동작에 영향을 줄 수 있습니다.",
                                    "agent.write_warning" to "파일 변경은 선택한 작업 공간 디렉터리로 제한됩니다.",
                                    "agent.remember_docker_shell" to "이 대화에서 이 작업 공간의 Docker 명령 자동 승인",
                                    "agent.remember_docker_network" to "이 대화에서 이 작업 공간의 Docker 네트워크 명령 자동 승인",
                                    "agent.remember_image_pull" to "이 대화에서 이 이미지 다운로드 자동 승인",
                                    "agent.remember_operation" to "이 대화에서 이 유형의 작업 자동 승인",
                                    "agent.allow" to "허용", "agent.deny" to "거부",
                                    "settings.navigation" to "설정 카테고리", "settings.section.general" to "일반",
                                    "settings.section.messages" to "메시지 표시", "settings.section.interaction" to "상호작용",
                                    "settings.section.data" to "데이터, 백업 및 웹 검색",
                                    "settings.section.assistants" to "어시스턴트", "settings.section.providers" to "모델 및 서비스",
                                    "composer.placeholder" to "RikkaHub에 메시지 보내기", "model_picker.title" to "모델 선택",
                                    "model_picker.filter" to "모델 필터", "model_picker.reasoning" to "추론 강도",
                                    "model_picker.default" to "기본", "model_picker.low" to "낮음", "model_picker.medium" to "보통", "model_picker.high" to "높음",
                                    "model_picker.manage_providers" to "제공업체 관리", "model_picker.checking_balance" to "잔액 확인 중",
                                    "model_picker.balance" to "잔액: %s", "model_picker.balance_failed" to "잔액을 확인할 수 없음",
                                    "mcp.manage" to "MCP 서비스 관리", "mcp.check" to "연결 확인",
                                    "mcp.title" to "MCP 서비스", "mcp.services_for_assistant" to "현재 어시스턴트에 %d개 서비스",
                                    "mcp.check_all" to "모두 확인", "mcp.open_settings" to "MCP 설정 열기",
                                    "mcp.no_servers" to "구성된 MCP 서비스가 없습니다", "mcp.not_checked" to "확인하지 않음",
                                    "mcp.checking" to "확인 중", "mcp.tools_synced" to "도구 %d개 동기화됨",
                                    "mcp.available_tools" to "사용 가능 · 도구 %d개", "mcp.current_assistant" to "이 어시스턴트",
                                    "mcp.enabled" to "사용", "mcp.available" to "사용 가능", "mcp.unavailable" to "사용 불가",
                                    "mcp_settings.title" to "MCP 서버", "mcp_settings.description" to "원격 도구를 동기화한 후 이 어시스턴트에 필요한 서버를 활성화합니다",
                                    "mcp_settings.add_server" to "MCP 서버 추가", "mcp_settings.unnamed_server" to "이름 없는 MCP 서버",
                                    "mcp_settings.delete_server" to "MCP 서버 삭제", "mcp_settings.server_name" to "서버 이름",
                                    "mcp_settings.server_name_help" to "영문자와 숫자만; 안정적인 도구 이름 생성에 사용",
                                    "mcp_settings.command" to "명령", "mcp_settings.arguments" to "명령 인수",
                                    "mcp_settings.arguments_help" to "한 줄에 하나의 인수", "mcp_settings.environment" to "환경 변수",
                                    "mcp_settings.environment_help" to "한 줄에 KEY=VALUE 쌍", "mcp_settings.server_url" to "서버 URL",
                                    "mcp_settings.enable_server" to "서버 사용", "mcp_settings.enable_server_help" to "꺼져 있으면 도구가 모델에 노출되지 않습니다",
                                    "mcp_settings.sync_failed" to "MCP 도구 동기화 실패", "mcp_settings.sync_tools" to "도구 동기화",
                                    "mcp_settings.collapse_tools" to "도구 접기", "mcp_settings.manage_tools" to "도구 %d개 관리(%e개 활성)",
                                    "mcp_settings.tool" to "MCP 도구", "assistant.message_template" to "메시지 템플릿",
                                    "assistant.template_variables" to "변수: {{ message }}, {{ role }}, {{ date }}, {{ time }}",
                                    "assistant.template_invalid" to "유효한 Pebble 템플릿에는 {{ message }}가 포함되어야 합니다",
                                    "assistant.conversation_system_prompt" to "대화 시스템 프롬프트",
                                    "assistant.conversation_system_prompt_help" to "개별 대화에서 이 어시스턴트의 시스템 프롬프트를 재정의할 수 있도록 허용",
                                    "assistant.conversation_lorebooks" to "대화 로어북",
                                    "assistant.conversation_lorebooks_help" to "개별 대화에서 이 어시스턴트의 프롬프트 주입을 켜거나 끌 수 있도록 허용",
                                    "assistant.web_search" to "웹 검색",
                                    "assistant.web_search_help" to "새 대화에서 기본적으로 OpenAI 호환 웹 검색 활성화",
                                    "assistant.local_time_tool" to "현지 시간 도구",
                                    "assistant.local_time_tool_help" to "필요시 모델이 이 장치의 현지 시간과 시간대를 읽을 수 있도록 허용",
                                    "assistant.ask_user_tool" to "사용자에게 질문",
                                    "assistant.ask_user_tool_help" to "필요시 모델이 확인이나 설명을 요청할 수 있도록 허용",
                                    "assistant.max_tool_rounds" to "답변당 최대 도구 호출 라운드",
                                    "assistant.max_tool_rounds_help" to "0은 무제한. 기본값 8",
                                    "assistant.agent_workspace" to "에이전트 작업 공간",
                                    "assistant.agent_workspace_help" to "선택한 디렉터리에서 파일 읽기/쓰기, 명령 실행, 활성 스킬 로드를 허용",
                                    "assistant.workspace_directory" to "작업 공간 디렉터리",
                                    "assistant.workspace_directory_help" to "에이전트 파일 도구만 이 디렉터리에 접근 가능. 로컬 셸은 매번 확인 필요",
                                    "assistant.docker_container" to "Docker 컨테이너", "assistant.local_shell" to "로컬 셸",
                                    "assistant.docker_image" to "Docker 이미지",
                                    "assistant.docker_image_help" to "기본적으로 오프라인, 비특권, 작업 공간만 마운트. 첫 풀은 승인 필요",
                                    "assistant.enabled_skills" to "사용 설정된 스킬",
                                    "assistant.enabled_skills_help" to "쉼표로 구분. ~/.config/rikkahub/skills/<name>/SKILL.md에 위치",
                                    "assistant.stream_output" to "스트리밍 출력",
                                    "assistant.stream_output_help" to "전체 응답을 기다리지 않고 도착하는 대로 응답 내용 표시",
                                    "assistant.memory" to "메모리",
                                    "assistant.memory_help" to "모델이 대화 간 장기 정보를 기록, 업데이트, 사용할 수 있도록 허용",
                                    "assistant.global_memory" to "전역 공유 메모리",
                                    "assistant.global_memory_help" to "전역 메모리를 사용하는 다른 어시스턴트와 메모리 저장소 공유",
                                    "assistant.add_global_memory" to "전역 메모리 추가",
                                    "assistant.delete_global_memory" to "전역 메모리 삭제",
                                    "assistant.shared_memory_content" to "공유할 사실 또는 선호",
                                    "assistant.memory_entries" to "메모리 항목",
                                    "assistant.add_memory" to "메모리 추가",
                                    "assistant.delete_memory" to "메모리 삭제",
                                    "assistant.memory_content" to "사실 또는 선호",
                                    "assistant.temperature" to "온도",
                                    "assistant.inherit_provider" to "비워 두면 제공업체 설정 상속",
                                    "assistant.max_output_tokens" to "최대 출력 토큰",
                                    "assistant.context_messages" to "컨텍스트 메시지 수",
                                    "assistant.keep_all_when_empty" to "비워 두면 모두 유지"
                                    ,"common.add" to "추가",
                                    "role.system" to "시스템", "role.user" to "사용자", "role.assistant" to "어시스턴트",
                                    "assistant.preset_messages" to "사전 설정 메시지",
                                    "assistant.preset_messages_help" to "모든 새 대화에 예제 메시지 추가",
                                    "assistant.message" to "메시지",
                                    "assistant.delete_preset_message" to "사전 설정 메시지 삭제",
                                    "assistant.quick_messages" to "빠른 메시지",
                                    "assistant.quick_messages_help" to "채팅 작성기에서 재사용 가능한 프롬프트 삽입",
                                    "assistant.title" to "제목", "assistant.content" to "내용",
                                    "assistant.delete_quick_message" to "빠른 메시지 삭제",
                                    "assistant.regex_transforms" to "정규식 변환",
                                    "assistant.regex_transforms_help" to "사용자 입력, 어시스턴트 출력 또는 표시 텍스트 변환",
                                    "assistant.rule_name" to "규칙 이름",
                                    "assistant.delete_regex_rule" to "정규식 규칙 삭제",
                                    "assistant.find_regex" to "찾을 정규식",
                                    "assistant.replace_with" to "다음으로 바꾸기",
                                    "assistant.visual_only" to "표시만",
                                    "assistant.prompt_injections" to "프롬프트 주입 / 로어북",
                                    "assistant.prompt_injections_help" to "키워드로 컨텍스트를 일치시키거나 주입을 항상 활성 상태로 유지",
                                    "assistant.entry_name" to "항목 이름",
                                    "assistant.delete_injection" to "주입 항목 삭제",
                                    "assistant.injection_content" to "주입 내용",
                                    "assistant.keywords" to "키워드(쉼표로 구분)",
                                    "assistant.keywords_help" to "비어 있으면 항상 활성화를 켜세요",
                                    "assistant.priority" to "우선순위",
                                    "assistant.priority_help" to "값이 클수록 앞에 배치",
                                    "assistant.scan_depth" to "스캔할 메시지 수",
                                    "assistant.scan_depth_help" to "키워드 매칭에 사용",
                                    "assistant.injection_depth" to "주입 깊이",
                                    "assistant.injection_depth_help" to "끝에서부터 셈",
                                    "assistant.injection_role" to "주입 역할",
                                    "assistant.before_system" to "시스템 전", "assistant.after_system" to "시스템 후",
                                    "assistant.top_of_chat" to "채팅 상단", "assistant.bottom_of_chat" to "채팅 하단",
                                    "assistant.at_depth" to "지정 깊이", "assistant.always_active" to "항상 활성화",
                                    "assistant.regex_keywords" to "정규식 키워드",
                                    "assistant.case_sensitive" to "대소문자 구분",
                                    "assistant.saved" to "어시스턴트 설정이 저장되었습니다",
                                    "assistant.save" to "어시스턴트 저장"
                                    ,"provider.title_model" to "제목 모델",
                                    "provider.title_model_help" to "비워 두면 채팅 모델 사용",
                                    "provider.title_prompt" to "제목 프롬프트",
                                    "provider.title_prompt_help" to "{locale} 및 {content} 자리 표시자 지원",
                                    "provider.token_usage" to "토큰 사용량",
                                    "provider.token_usage_help" to "호환 스트리밍 API에서 입력 및 출력 토큰 수 요청",
                                    "provider.use_provider_default" to "비워 두면 제공업체 기본값 사용",
                                    "provider.system_prompt" to "시스템 프롬프트",
                                    "provider.balance_query" to "잔액 조회",
                                    "provider.balance_query_help" to "제공업체 API를 통해 계정 잔액 또는 할당량 조회",
                                    "provider.balance_api_path" to "잔액 API 경로",
                                    "provider.balance_api_path_help" to "상대 경로 또는 전체 URL 입력",
                                    "provider.balance_result_path" to "결과 JSON 경로",
                                    "provider.balance_result_path_help" to "예: data.balance 또는 data.items[0].amount",
                                    "provider.checking_balance" to "잔액 확인 중...",
                                    "provider.current_balance" to "현재 잔액: %s",
                                    "provider.balance_failed" to "잔액 조회에 실패했습니다: %s",
                                    "provider.check_balance" to "잔액 조회",
                                    "request_overrides.headers" to "사용자 지정 헤더",
                                    "request_overrides.headers_help" to "채팅 및 모델 요청에 추가",
                                    "request_overrides.add_header" to "사용자 지정 헤더 추가",
                                    "request_overrides.header" to "헤더", "request_overrides.value" to "값",
                                    "request_overrides.delete_header" to "사용자 지정 헤더 삭제",
                                    "request_overrides.body" to "사용자 지정 요청 본문",
                                    "request_overrides.body_help" to "JSON을 요청 최상위 필드에 병합",
                                    "request_overrides.add_body" to "사용자 지정 요청 본문 추가",
                                    "request_overrides.key" to "키", "request_overrides.json_value" to "JSON 값",
                                    "request_overrides.invalid_json" to "유효한 JSON을 입력하세요",
                                    "request_overrides.delete_body" to "사용자 지정 요청 본문 삭제"
                                    ,"chat.restore_snapshot" to "기록 스냅샷 복원 %d: %s",
                                    "chat.snapshot_messages" to "메시지 %d개",
                                    "chat.delete_snapshot" to "기록 스냅샷 삭제",
                                    "jumper.top" to "맨 위로 이동", "jumper.previous" to "이전 메시지",
                                    "jumper.next" to "다음 메시지", "jumper.bottom" to "맨 아래로 이동",
                                    "tool.calling" to "호출 중", "tool.completed" to "호출 완료",
                                    "tool.input" to "입력", "tool.output" to "출력", "tool.result" to "도구 결과",
                                    "tool.answer_required" to "답변이 필요합니다",
                                    "tool.web_search" to "웹 검색", "tool.current_time" to "현재 시간 가져오기",
                                    "tool.memory" to "메모리 관리", "tool.list_files" to "파일 목록",
                                    "tool.search_files" to "파일 검색", "tool.read_file" to "파일 읽기",
                                    "tool.write_file" to "파일 쓰기", "tool.edit_file" to "파일 편집",
                                    "tool.run_command" to "명령 실행", "tool.use_skill" to "스킬 사용"
                                    ,"model_picker.refresh_balance" to "%s 잔액 새로고침",
                                    "model_picker.current_model" to "현재 모델",
                                    "model_capability.text" to "텍스트", "model_capability.vision" to "비전",
                                    "model_capability.reasoning" to "추론", "model_capability.tools" to "도구",
                                    "attachment.remove" to "첨부 파일 제거", "mcp.unnamed_service" to "이름 없는 MCP 서비스",
                                    "language.chinese" to "중국어", "user.you" to "나",
                                    "message.user_avatar" to "사용자 아바타", "common.unnamed" to "이름 없음",
                                    "theme.sakura" to "벚꽃", "theme.ocean" to "바다", "theme.forest" to "숲",
                                    "theme.sunset" to "노을", "theme.lavender" to "라벤더", "theme.slate" to "슬레이트",
                                    "font.system" to "시스템 기본값", "font.sans_serif" to "고딕",
                                    "font.serif" to "명조", "font.monospace" to "고정폭"
                                    ,"runtime.unknown_error" to "알 수 없는 오류",
                                    "runtime.save_failed" to "저장 실패: %s",
                                    "runtime.title_empty" to "제목 모델이 내용을 반환하지 않았습니다",
                                    "runtime.title_failed" to "제목 생성에 실패했습니다",
                                    "runtime.suggestions_empty" to "제안 모델이 내용을 반환하지 않았습니다",
                                    "runtime.suggestions_failed" to "답변 제안 생성에 실패했습니다",
                                    "runtime.mcp_configuration_invalid" to "MCP 구성이 더 이상 유효하지 않습니다. 어시스턴트 설정에서 서버를 다시 선택하세요",
                                    "runtime.mcp_no_tools" to "MCP 서버 %s이(가) 사용 가능한 도구를 제공하지 않았습니다",
                                    "runtime.mcp_sync_failed" to "MCP 도구 동기화 실패: %s",
                                    "runtime.invalid_message_template" to "유효하지 않은 메시지 템플릿",
                                    "runtime.request_failed" to "요청에 실패했습니다",
                                    "runtime.not_enough_messages" to "압축할 메시지가 충분하지 않습니다",
                                    "runtime.compression_empty" to "압축 모델이 요약을 반환하지 않았습니다",
                                    "runtime.compression_failed" to "대화 압축에 실패했습니다",
                                    "runtime.translation_empty" to "번역 모델이 내용을 반환하지 않았습니다",
                                    "runtime.translation_failed" to "번역에 실패했습니다",
                                    "runtime.export_failed" to "내보내기에 실패했습니다: %s",
                                    "runtime.import_failed" to "가져오기에 실패했습니다: %s"
                                    ,"runtime.tool_round_limit" to "이 답변은 %d회의 도구 호출 제한에 도달했습니다. 새 메시지를 보내 다시 시작하세요.",
                                    "runtime.add_attachment_failed" to "첨부 파일을 추가할 수 없습니다"
                                    ,"defaults.new_provider" to "새 제공업체",
                                    "defaults.new_assistant" to "새 어시스턴트",
                                    "file.import_backup" to "RikkaHub 백업 가져오기",
                                    "file.imported_backup" to "%s에서 백업을 가져왔습니다",
                                    "file.choose_attachments" to "이미지, 오디오, 텍스트 또는 문서 추가"
                                    ,"provider.connection_success" to "연결됨 · 사용 가능한 모델 %d개"
)
