package me.rerere.rikkahub.desktop

internal val DesktopCommonTranslations = mapOf(
    DesktopLanguage.CHINESE_TRADITIONAL to mapOf(
        "common.add" to "新增",
        "common.cancel" to "取消",
        "common.save" to "儲存",
        "common.submit" to "提交",
        "common.unnamed" to "未命名",
        "user.you" to "你",
        "attachment.remove" to "移除附件",
        "defaults.new_provider" to "新服務商",
        "defaults.new_assistant" to "新助手",
        "file.import_backup" to "匯入 RikkaHub 備份",
        "file.imported_backup" to "已從 %s 匯入備份",
        "file.choose_attachments" to "新增圖片、音訊、文字或文件",
        "tool.calling" to "正在呼叫",
        "tool.completed" to "呼叫完成",
        "tool.input" to "輸入",
        "tool.output" to "輸出",
        "tool.result" to "工具結果",
        "runtime.request_failed" to "請求失敗",
        "runtime.translation_failed" to "翻譯失敗",
        "runtime.export_failed" to "匯出失敗：%s",
        "runtime.import_failed" to "匯入失敗：%s",
        "runtime.add_attachment_failed" to "無法新增附件",
        "runtime.mcp_configuration_invalid" to "MCP 設定已失效，請在助手設定中重新選擇伺服器。",
        "settings.color_mode" to "色彩模式",
        "settings.system" to "跟隨系統",
        "settings.light" to "淺色",
        "settings.dark" to "深色",
        "settings.theme_color" to "主題色",
        "settings.font" to "介面字型",
        "settings.chat_font_size" to "聊天字型大小",
        "composer.send" to "傳送；長按只新增訊息",
        "composer.stop_generation" to "停止產生",
        "composer.add_attachment" to "新增附件",
        "composer.enable_web_search" to "啟用網路搜尋",
        "composer.disable_web_search" to "停用網路搜尋",
        "message.copy" to "複製",
        "message.regenerate" to "重新產生",
        "message.translate" to "翻譯",
        "message.favorite" to "收藏",
        "message.unfavorite" to "取消收藏",
        "message.edit" to "編輯",
        "message.delete" to "刪除",
        "mcp.title" to "MCP 服務",
        "mcp.services_for_assistant" to "此助手有 %d 個服務",
        "mcp.check_all" to "全部檢查",
        "mcp.open_settings" to "開啟 MCP 設定",
        "mcp.no_servers" to "尚未設定 MCP 服務",
        "mcp.not_checked" to "尚未檢查",
        "mcp.checking" to "檢查中",
        "mcp.tools_synced" to "已同步 %d 個工具",
        "mcp.available_tools" to "可用 · %d 個工具",
        "mcp.current_assistant" to "此助手",
        "mcp.enabled" to "啟用",
        "mcp.unnamed_service" to "未命名 MCP 服務",
        "sidebar.welcome" to "歡迎回來",
        "sidebar.new_chat" to "新增對話",
        "sidebar.search_chats" to "搜尋對話",
        "sidebar.favorite_messages" to "收藏訊息",
        "sidebar.all_assistants" to "所有助手",
        "sidebar.all_tags" to "所有標籤",
        "sidebar.chats" to "對話",
        "sidebar.search" to "搜尋",
        "chat.rename" to "重新命名",
        "chat.export_markdown" to "匯出 Markdown",
        "chat.statistics" to "對話統計",
        "chat.compress_history" to "壓縮歷史",
        "chat.move_to_folder" to "移至資料夾",
        "chat.uncategorized" to "未分類",
        "chat.new_folder" to "新增資料夾",
        "conversation.pin" to "置頂",
        "conversation.unpin" to "取消置頂",
        "settings.chinese_typography" to "中文排版",
        "settings.language" to "語言",
        "settings.font_description" to "%s；程式碼區塊保持等寬字型",
        "stats.characters" to "文字與推理字元",
        "stats.created_at" to "建立時間",
        "stats.updated_at" to "更新時間",
        "file.add_attachments" to "新增附件",
        "file.parent_directory" to "上層目錄",
        "file.selected" to "已選取",
        "file.file_name" to "檔案名稱",
        "chat.generate_title" to "產生標題",
        "chat.generate_suggestions" to "產生回覆建議",
        "chat.set_system_prompt" to "設定系統提示詞",
        "chat.edit_system_prompt" to "編輯系統提示詞",
        "chat.enable_lorebooks" to "啟用對話世界書",
        "chat.disable_lorebooks" to "停用對話世界書",
        "chat.close" to "關閉",
        "theme.sakura" to "櫻花",
        "theme.ocean" to "海洋",
        "theme.forest" to "森林",
        "theme.sunset" to "落日",
        "theme.lavender" to "薰衣草",
        "theme.slate" to "石墨",
        "font.system" to "系統預設",
        "font.sans_serif" to "無襯線",
        "font.serif" to "襯線",
        "font.monospace" to "等寬",
        "timeline.today" to "今天",
        "timeline.yesterday" to "昨天",
        "timeline.day_before_yesterday" to "前天",
        "timeline.days_ago" to "%d 天前",
        "sidebar.recent" to "最近",
        "sidebar.most_active" to "最常使用",
        "assistant.global_memory" to "全域共享記憶",
        "assistant.memory_entries" to "記憶項目",
        "assistant.add_memory" to "新增記憶",
        "assistant.agent_workspace" to "Agent 工作區",
        "assistant.workspace_directory" to "工作區目錄",
        "assistant.docker_container" to "Docker 容器",
        "assistant.local_shell" to "本機 Shell",
        "assistant.enabled_skills" to "已啟用 Skills",
        "assistant.temperature" to "溫度",
        "assistant.max_output_tokens" to "最大輸出 Token",
        "assistant.context_messages" to "上下文訊息數",
        "assistant.inherit_provider" to "留空以繼承服務商設定",
        "assistant.stream_output" to "串流輸出",
        "assistant.memory" to "記憶",
        "mcp_settings.title" to "MCP 伺服器",
        "mcp_settings.add_server" to "新增 MCP 伺服器",
        "mcp_settings.server_name" to "伺服器名稱",
        "mcp_settings.server_url" to "伺服器 URL",
        "mcp_settings.enable_server" to "啟用伺服器",
        "mcp_settings.sync_tools" to "同步工具",
        "mcp_settings.delete_server" to "刪除 MCP 伺服器",
        "assistant.regex_transforms" to "正規表示式轉換",
        "assistant.rule_name" to "規則名稱",
        "assistant.find_regex" to "符合的正規表示式",
        "assistant.replace_with" to "取代為",
        "assistant.prompt_injections" to "提示詞注入 / 世界書",
        "assistant.entry_name" to "條目名稱",
        "assistant.keywords" to "關鍵字（逗號分隔）",
        "assistant.priority" to "優先順序",
        "assistant.always_active" to "常駐",
        "assistant.preset_messages" to "預設訊息",
        "assistant.quick_messages" to "快捷訊息",
        "assistant.title" to "標題",
        "assistant.content" to "內容",
        "assistant.message" to "訊息",
        "assistant.delete_preset_message" to "刪除預設訊息",
        "assistant.delete_quick_message" to "刪除快捷訊息",
        "assistant.save" to "儲存助手",
        "request_overrides.headers" to "自訂請求標頭",
        "request_overrides.add_header" to "新增自訂請求標頭",
        "request_overrides.header" to "請求標頭",
        "request_overrides.value" to "值",
        "request_overrides.delete_header" to "刪除自訂請求標頭",
        "request_overrides.body" to "自訂請求主體",
        "request_overrides.add_body" to "新增自訂請求主體",
        "request_overrides.invalid_json" to "請輸入有效 JSON",
        "provider.balance_query" to "餘額查詢",
        "provider.balance_api_path" to "餘額 API 路徑",
        "provider.balance_result_path" to "結果 JSON 路徑",
        "provider.checking_balance" to "正在查詢餘額...",
        "provider.current_balance" to "目前餘額：%s",
        "provider.balance_failed" to "餘額查詢失敗：%s",
        "provider.check_balance" to "查詢餘額",
        "provider.connection_success" to "已連線 · 可用 %d 個模型",
        "agent.approval_request" to "Agent 請求此操作，是否允許？",
        "agent.allow" to "允許",
        "agent.deny" to "拒絕",
        "agent.local_shell_warning" to "本機 Shell 會以目前使用者權限執行，請確認命令及其影響。",
        "agent.write_warning" to "檔案修改僅限於選定工作區目錄。",
        "timeline.execution" to "執行過程",
        "timeline.expand_execution" to "展開執行過程",
        "timeline.collapse_execution" to "收合執行過程",
        "timeline.expand_steps" to "展開 %d 個步驟",
        "timeline.reasoning" to "推理",
        "timeline.reasoning_duration" to "推理了 %s 秒",
        "jumper.top" to "跳至頂端",
        "jumper.previous" to "上一則訊息",
        "jumper.next" to "下一則訊息",
        "jumper.bottom" to "跳至底端",
        "dialog.translate_message" to "翻譯訊息",
        "dialog.target_language" to "目標語言",
        "dialog.compress_history" to "壓縮對話歷史",
        "dialog.compress" to "壓縮",
        "dialog.target_tokens" to "目標 Token",
        "dialog.keep_recent_messages" to "保留最近訊息（共 %d 條）",
        "stats.messages" to "訊息",
        "stats.attachments" to "附件",
        "settings.send_on_enter" to "按 Enter 傳送",
        "settings.auto_scroll" to "自動捲動",
        "settings.message_navigation" to "訊息導航",
        "settings.message_navigation_left" to "訊息導航靠左",
        "settings.show_user_avatar" to "顯示使用者頭像",
        "settings.user_nickname" to "使用者暱稱",
        "settings.show_model_icon" to "顯示模型圖示",
        "settings.show_model_name" to "顯示模型名稱",
        "settings.assistant_bubble" to "助手氣泡",
        "settings.message_timestamp" to "訊息時間",
        "settings.reasoning" to "推理內容",
        "settings.collapse_reasoning" to "完成後收合推理內容",
        "settings.code_wrap" to "程式碼區塊自動換行",
        "settings.export_backup" to "匯出備份",
        "settings.export" to "匯出",
        "settings.import_backup" to "匯入備份",
        "settings.import" to "匯入",
        "settings.reset_data" to "重設所有資料",
        "settings.reset" to "重設",
        "settings.reset_confirmation_title" to "重設所有資料？",
        "settings.confirm_reset" to "重設資料",
        "settings.web_search" to "網路搜尋服務",
        "settings.searxng_url" to "SearXNG URL",
        "settings.search_result_count" to "每次搜尋 %d 項結果",
        "settings.test_search" to "測試搜尋",
        "settings.search_test_success" to "網路搜尋連線正常",
        "settings.search_test_failed" to "搜尋測試失敗",
        "settings.add_assistant" to "新增助手",
        "settings.assistant_name" to "助手名稱",
        "settings.copy_assistant" to "複製助手",
        "settings.delete_assistant" to "刪除助手",
        "settings.tags" to "標籤（逗號分隔）",
        "settings.model_inherit" to "模型（留空以使用服務商預設值）",
        "settings.select_model" to "選擇模型",
        "settings.system_prompt_inherit" to "系統提示詞（留空以使用服務商預設值）",
        "settings.add_provider" to "新增服務商",
        "settings.provider_name" to "服務商名稱",
        "settings.delete_provider" to "刪除服務商",
        "settings.base_url" to "基礎 URL",
        "settings.api_key" to "API 金鑰",
        "settings.model" to "模型",
        "settings.test_and_fetch_models" to "測試並取得模型",
        "settings.save_provider" to "儲存服務商",
        "model_picker.refresh_balance" to "重新整理 %s 餘額",
        "model_picker.current_model" to "目前模型",
        "model_capability.text" to "文字",
        "model_capability.vision" to "視覺",
        "model_capability.reasoning" to "推理",
        "model_capability.tools" to "工具"
    ),
    DesktopLanguage.JAPANESE to mapOf(
        "common.add" to "追加",
        "common.cancel" to "キャンセル",
        "common.save" to "保存",
        "common.submit" to "送信",
        "common.unnamed" to "名前なし",
        "user.you" to "あなた",
        "attachment.remove" to "添付を削除",
        "defaults.new_provider" to "新しいプロバイダー",
        "defaults.new_assistant" to "新しいアシスタント",
        "file.import_backup" to "RikkaHub バックアップをインポート",
        "file.imported_backup" to "%s からバックアップをインポートしました",
        "file.choose_attachments" to "画像、音声、テキスト、または文書を追加",
        "tool.calling" to "呼び出し中",
        "tool.completed" to "完了",
        "tool.input" to "入力",
        "tool.output" to "出力",
        "tool.result" to "ツール結果",
        "runtime.request_failed" to "リクエストに失敗しました",
        "runtime.translation_failed" to "翻訳に失敗しました",
        "runtime.export_failed" to "エクスポートに失敗しました: %s",
        "runtime.import_failed" to "インポートに失敗しました: %s",
        "runtime.add_attachment_failed" to "添付を追加できません",
        "runtime.mcp_configuration_invalid" to "MCP 設定が無効です。アシスタント設定でサーバーを選び直してください。",
        "settings.color_mode" to "カラーモード",
        "settings.system" to "システム",
        "settings.light" to "ライト",
        "settings.dark" to "ダーク",
        "settings.theme_color" to "テーマカラー",
        "settings.font" to "インターフェースのフォント",
        "settings.chat_font_size" to "チャットのフォントサイズ",
        "composer.send" to "送信。長押しで返信なしで追加",
        "composer.stop_generation" to "生成を停止",
        "composer.add_attachment" to "添付を追加",
        "composer.enable_web_search" to "ウェブ検索を有効化",
        "composer.disable_web_search" to "ウェブ検索を無効化",
        "message.copy" to "コピー",
        "message.regenerate" to "再生成",
        "message.translate" to "翻訳",
        "message.favorite" to "お気に入り",
        "message.unfavorite" to "お気に入りから削除",
        "message.edit" to "編集",
        "message.delete" to "削除",
        "mcp.title" to "MCP サービス",
        "mcp.services_for_assistant" to "このアシスタントのサービス: %d",
        "mcp.check_all" to "すべて確認",
        "mcp.open_settings" to "MCP 設定を開く",
        "mcp.no_servers" to "MCP サービスが設定されていません",
        "mcp.not_checked" to "未確認",
        "mcp.checking" to "確認中",
        "mcp.tools_synced" to "%d 個のツールを同期済み",
        "mcp.available_tools" to "利用可能 · %d 個のツール",
        "mcp.current_assistant" to "このアシスタント",
        "mcp.enabled" to "有効",
        "mcp.unnamed_service" to "名前のない MCP サービス",
        "sidebar.welcome" to "おかえりなさい",
        "sidebar.new_chat" to "新しいチャット",
        "sidebar.search_chats" to "チャットを検索",
        "sidebar.favorite_messages" to "お気に入りのメッセージ",
        "sidebar.all_assistants" to "すべてのアシスタント",
        "sidebar.all_tags" to "すべてのタグ",
        "sidebar.chats" to "チャット",
        "sidebar.search" to "検索",
        "chat.rename" to "名前を変更",
        "chat.export_markdown" to "Markdown をエクスポート",
        "chat.statistics" to "会話の統計",
        "chat.compress_history" to "履歴を圧縮",
        "chat.move_to_folder" to "フォルダーへ移動",
        "chat.uncategorized" to "未分類",
        "chat.new_folder" to "新しいフォルダー",
        "conversation.pin" to "固定",
        "conversation.unpin" to "固定を解除",
        "settings.chinese_typography" to "中国語組版",
        "settings.language" to "言語",
        "settings.font_description" to "%s。コードブロックは等幅のままです",
        "stats.characters" to "テキストと推論の文字数",
        "stats.created_at" to "作成日時",
        "stats.updated_at" to "更新日時",
        "file.add_attachments" to "添付を追加",
        "file.parent_directory" to "親ディレクトリ",
        "file.selected" to "選択済み",
        "file.file_name" to "ファイル名",
        "chat.generate_title" to "タイトルを生成",
        "chat.generate_suggestions" to "返信候補を生成",
        "chat.set_system_prompt" to "システムプロンプトを設定",
        "chat.edit_system_prompt" to "システムプロンプトを編集",
        "chat.enable_lorebooks" to "会話ロアブックを有効化",
        "chat.disable_lorebooks" to "会話ロアブックを無効化",
        "chat.close" to "閉じる",
        "theme.sakura" to "さくら",
        "theme.ocean" to "海",
        "theme.forest" to "森",
        "theme.sunset" to "夕日",
        "theme.lavender" to "ラベンダー",
        "theme.slate" to "スレート",
        "font.system" to "システム既定",
        "font.sans_serif" to "ゴシック",
        "font.serif" to "明朝",
        "font.monospace" to "等幅",
        "timeline.today" to "今日",
        "timeline.yesterday" to "昨日",
        "timeline.day_before_yesterday" to "一昨日",
        "timeline.days_ago" to "%d 日前",
        "sidebar.recent" to "最近",
        "sidebar.most_active" to "よく使う",
        "assistant.global_memory" to "グローバル共有メモリー",
        "assistant.memory_entries" to "メモリー項目",
        "assistant.add_memory" to "メモリーを追加",
        "assistant.agent_workspace" to "エージェントワークスペース",
        "assistant.workspace_directory" to "ワークスペースディレクトリ",
        "assistant.docker_container" to "Docker コンテナ",
        "assistant.local_shell" to "ローカルシェル",
        "assistant.enabled_skills" to "有効なスキル",
        "assistant.temperature" to "温度",
        "assistant.max_output_tokens" to "最大出力トークン",
        "assistant.context_messages" to "コンテキストメッセージ数",
        "assistant.inherit_provider" to "空欄でプロバイダー設定を継承",
        "assistant.stream_output" to "ストリーム出力",
        "assistant.memory" to "メモリー",
        "mcp_settings.title" to "MCP サーバー",
        "mcp_settings.add_server" to "MCP サーバーを追加",
        "mcp_settings.server_name" to "サーバー名",
        "mcp_settings.server_url" to "サーバー URL",
        "mcp_settings.enable_server" to "サーバーを有効化",
        "mcp_settings.sync_tools" to "ツールを同期",
        "mcp_settings.delete_server" to "MCP サーバーを削除",
        "assistant.regex_transforms" to "正規表現変換",
        "assistant.rule_name" to "ルール名",
        "assistant.find_regex" to "検索正規表現",
        "assistant.replace_with" to "置換後",
        "assistant.prompt_injections" to "プロンプト注入 / ロアブック",
        "assistant.entry_name" to "項目名",
        "assistant.keywords" to "キーワード（カンマ区切り）",
        "assistant.priority" to "優先度",
        "assistant.always_active" to "常に有効",
        "assistant.preset_messages" to "プリセットメッセージ",
        "assistant.quick_messages" to "クイックメッセージ",
        "assistant.title" to "タイトル",
        "assistant.content" to "内容",
        "assistant.message" to "メッセージ",
        "assistant.delete_preset_message" to "プリセットメッセージを削除",
        "assistant.delete_quick_message" to "クイックメッセージを削除",
        "assistant.save" to "アシスタントを保存",
        "request_overrides.headers" to "カスタムヘッダー",
        "request_overrides.add_header" to "カスタムヘッダーを追加",
        "request_overrides.header" to "ヘッダー",
        "request_overrides.value" to "値",
        "request_overrides.delete_header" to "カスタムヘッダーを削除",
        "request_overrides.body" to "カスタムリクエスト本文",
        "request_overrides.add_body" to "カスタムリクエスト本文を追加",
        "request_overrides.invalid_json" to "有効な JSON を入力してください",
        "provider.balance_query" to "残高照会",
        "provider.balance_api_path" to "残高 API パス",
        "provider.balance_result_path" to "結果 JSON パス",
        "provider.checking_balance" to "残高を確認中...",
        "provider.current_balance" to "現在の残高: %s",
        "provider.balance_failed" to "残高照会に失敗しました: %s",
        "provider.check_balance" to "残高を確認",
        "provider.connection_success" to "接続済み · %d モデル利用可能",
        "agent.approval_request" to "エージェントがこの操作を要求しています。許可しますか？",
        "agent.allow" to "許可",
        "agent.deny" to "拒否",
        "agent.local_shell_warning" to "ローカルシェルは現在のユーザー権限で実行されます。コマンドと影響を確認してください。",
        "agent.write_warning" to "ファイル変更は選択したワークスペースディレクトリに限定されます。",
        "timeline.execution" to "実行",
        "timeline.expand_execution" to "実行を展開",
        "timeline.collapse_execution" to "実行を折りたたむ",
        "timeline.expand_steps" to "%d ステップを展開",
        "timeline.reasoning" to "推論",
        "timeline.reasoning_duration" to "%s 秒間推論",
        "jumper.top" to "先頭へ移動",
        "jumper.previous" to "前のメッセージ",
        "jumper.next" to "次のメッセージ",
        "jumper.bottom" to "末尾へ移動",
        "dialog.translate_message" to "メッセージを翻訳",
        "dialog.target_language" to "翻訳先の言語",
        "dialog.compress_history" to "会話履歴を圧縮",
        "dialog.compress" to "圧縮",
        "dialog.target_tokens" to "目標トークン数",
        "dialog.keep_recent_messages" to "最近のメッセージを保持（全 %d 件）",
        "stats.messages" to "メッセージ",
        "stats.attachments" to "添付",
        "settings.send_on_enter" to "Enter で送信",
        "settings.auto_scroll" to "自動スクロール",
        "settings.message_navigation" to "メッセージナビゲーション",
        "settings.message_navigation_left" to "メッセージナビゲーションを左に表示",
        "settings.show_user_avatar" to "ユーザーアバターを表示",
        "settings.user_nickname" to "ユーザー名",
        "settings.show_model_icon" to "モデルアイコンを表示",
        "settings.show_model_name" to "モデル名を表示",
        "settings.assistant_bubble" to "アシスタントの吹き出し",
        "settings.message_timestamp" to "メッセージ時刻",
        "settings.reasoning" to "推論内容",
        "settings.collapse_reasoning" to "完了後に推論を折りたたむ",
        "settings.code_wrap" to "コードブロックを折り返す",
        "settings.export_backup" to "バックアップをエクスポート",
        "settings.export" to "エクスポート",
        "settings.import_backup" to "バックアップをインポート",
        "settings.import" to "インポート",
        "settings.reset_data" to "すべてのデータをリセット",
        "settings.reset" to "リセット",
        "settings.reset_confirmation_title" to "すべてのデータをリセットしますか？",
        "settings.confirm_reset" to "データをリセット",
        "settings.web_search" to "ウェブ検索サービス",
        "settings.searxng_url" to "SearXNG URL",
        "settings.search_result_count" to "検索あたり %d 件",
        "settings.test_search" to "検索をテスト",
        "settings.search_test_success" to "ウェブ検索の接続は正常です",
        "settings.search_test_failed" to "検索テストに失敗しました",
        "settings.add_assistant" to "アシスタントを追加",
        "settings.assistant_name" to "アシスタント名",
        "settings.copy_assistant" to "アシスタントをコピー",
        "settings.delete_assistant" to "アシスタントを削除",
        "settings.tags" to "タグ（カンマ区切り）",
        "settings.model_inherit" to "モデル（空欄でプロバイダーの既定値を使用）",
        "settings.select_model" to "モデルを選択",
        "settings.system_prompt_inherit" to "システムプロンプト（空欄でプロバイダーの既定値を使用）",
        "settings.add_provider" to "プロバイダーを追加",
        "settings.provider_name" to "プロバイダー名",
        "settings.delete_provider" to "プロバイダーを削除",
        "settings.base_url" to "ベース URL",
        "settings.api_key" to "API キー",
        "settings.model" to "モデル",
        "settings.test_and_fetch_models" to "接続テストとモデル取得",
        "settings.save_provider" to "プロバイダーを保存",
        "model_picker.refresh_balance" to "%s の残高を更新",
        "model_picker.current_model" to "現在のモデル",
        "model_capability.text" to "テキスト",
        "model_capability.vision" to "画像",
        "model_capability.reasoning" to "推論",
        "model_capability.tools" to "ツール"
    ),
    DesktopLanguage.KOREAN to mapOf(
        "common.add" to "추가",
        "common.cancel" to "취소",
        "common.save" to "저장",
        "common.submit" to "제출",
        "common.unnamed" to "이름 없음",
        "user.you" to "나",
        "attachment.remove" to "첨부 파일 제거",
        "defaults.new_provider" to "새 제공업체",
        "defaults.new_assistant" to "새 어시스턴트",
        "file.import_backup" to "RikkaHub 백업 가져오기",
        "file.imported_backup" to "%s에서 백업을 가져왔습니다",
        "file.choose_attachments" to "이미지, 오디오, 텍스트 또는 문서 추가",
        "tool.calling" to "호출 중",
        "tool.completed" to "호출 완료",
        "tool.input" to "입력",
        "tool.output" to "출력",
        "tool.result" to "도구 결과",
        "runtime.request_failed" to "요청에 실패했습니다",
        "runtime.translation_failed" to "번역에 실패했습니다",
        "runtime.export_failed" to "내보내기에 실패했습니다: %s",
        "runtime.import_failed" to "가져오기에 실패했습니다: %s",
        "runtime.add_attachment_failed" to "첨부 파일을 추가할 수 없습니다",
        "runtime.mcp_configuration_invalid" to "MCP 구성이 더 이상 유효하지 않습니다. 어시스턴트 설정에서 서버를 다시 선택하세요.",
        "settings.color_mode" to "색상 모드",
        "settings.system" to "시스템",
        "settings.light" to "밝게",
        "settings.dark" to "어둡게",
        "settings.theme_color" to "테마 색상",
        "settings.font" to "인터페이스 글꼴",
        "settings.chat_font_size" to "채팅 글꼴 크기",
        "composer.send" to "보내기; 길게 눌러 답변 없이 추가",
        "composer.stop_generation" to "생성 중지",
        "composer.add_attachment" to "첨부 파일 추가",
        "composer.enable_web_search" to "웹 검색 사용",
        "composer.disable_web_search" to "웹 검색 끄기",
        "message.copy" to "복사",
        "message.regenerate" to "다시 생성",
        "message.translate" to "번역",
        "message.favorite" to "즐겨찾기",
        "message.unfavorite" to "즐겨찾기 해제",
        "message.edit" to "편집",
        "message.delete" to "삭제",
        "mcp.title" to "MCP 서비스",
        "mcp.services_for_assistant" to "이 어시스턴트의 서비스 %d개",
        "mcp.check_all" to "모두 확인",
        "mcp.open_settings" to "MCP 설정 열기",
        "mcp.no_servers" to "구성된 MCP 서비스가 없습니다",
        "mcp.not_checked" to "확인하지 않음",
        "mcp.checking" to "확인 중",
        "mcp.tools_synced" to "도구 %d개 동기화됨",
        "mcp.available_tools" to "사용 가능 · 도구 %d개",
        "mcp.current_assistant" to "이 어시스턴트",
        "mcp.enabled" to "사용",
        "mcp.unnamed_service" to "이름 없는 MCP 서비스",
        "sidebar.welcome" to "다시 오셨군요",
        "sidebar.new_chat" to "새 채팅",
        "sidebar.search_chats" to "채팅 검색",
        "sidebar.favorite_messages" to "즐겨찾는 메시지",
        "sidebar.all_assistants" to "모든 어시스턴트",
        "sidebar.all_tags" to "모든 태그",
        "sidebar.chats" to "채팅",
        "sidebar.search" to "검색",
        "chat.rename" to "이름 변경",
        "chat.export_markdown" to "Markdown 내보내기",
        "chat.statistics" to "대화 통계",
        "chat.compress_history" to "기록 압축",
        "chat.move_to_folder" to "폴더로 이동",
        "chat.uncategorized" to "미분류",
        "chat.new_folder" to "새 폴더",
        "conversation.pin" to "고정",
        "conversation.unpin" to "고정 해제",
        "settings.chinese_typography" to "중국어 조판",
        "settings.language" to "언어",
        "settings.font_description" to "%s; 코드 블록은 고정폭 글꼴을 유지합니다",
        "stats.characters" to "텍스트 및 추론 문자 수",
        "stats.created_at" to "생성 시간",
        "stats.updated_at" to "업데이트 시간",
        "file.add_attachments" to "첨부 파일 추가",
        "file.parent_directory" to "상위 디렉터리",
        "file.selected" to "선택됨",
        "file.file_name" to "파일 이름",
        "chat.generate_title" to "제목 생성",
        "chat.generate_suggestions" to "답변 제안 생성",
        "chat.set_system_prompt" to "시스템 프롬프트 설정",
        "chat.edit_system_prompt" to "시스템 프롬프트 편집",
        "chat.enable_lorebooks" to "대화 로어북 사용",
        "chat.disable_lorebooks" to "대화 로어북 끄기",
        "chat.close" to "닫기",
        "theme.sakura" to "벚꽃",
        "theme.ocean" to "바다",
        "theme.forest" to "숲",
        "theme.sunset" to "노을",
        "theme.lavender" to "라벤더",
        "theme.slate" to "슬레이트",
        "font.system" to "시스템 기본값",
        "font.sans_serif" to "고딕",
        "font.serif" to "명조",
        "font.monospace" to "고정폭",
        "timeline.today" to "오늘",
        "timeline.yesterday" to "어제",
        "timeline.day_before_yesterday" to "그제",
        "timeline.days_ago" to "%d일 전",
        "sidebar.recent" to "최근",
        "sidebar.most_active" to "가장 많이 사용",
        "assistant.global_memory" to "전역 공유 메모리",
        "assistant.memory_entries" to "메모리 항목",
        "assistant.add_memory" to "메모리 추가",
        "assistant.agent_workspace" to "에이전트 작업 공간",
        "assistant.workspace_directory" to "작업 공간 디렉터리",
        "assistant.docker_container" to "Docker 컨테이너",
        "assistant.local_shell" to "로컬 셸",
        "assistant.enabled_skills" to "사용 설정된 스킬",
        "assistant.temperature" to "온도",
        "assistant.max_output_tokens" to "최대 출력 토큰",
        "assistant.context_messages" to "컨텍스트 메시지 수",
        "assistant.inherit_provider" to "비워 두면 제공업체 설정 상속",
        "assistant.stream_output" to "스트리밍 출력",
        "assistant.memory" to "메모리",
        "mcp_settings.title" to "MCP 서버",
        "mcp_settings.add_server" to "MCP 서버 추가",
        "mcp_settings.server_name" to "서버 이름",
        "mcp_settings.server_url" to "서버 URL",
        "mcp_settings.enable_server" to "서버 사용",
        "mcp_settings.sync_tools" to "도구 동기화",
        "mcp_settings.delete_server" to "MCP 서버 삭제",
        "assistant.regex_transforms" to "정규식 변환",
        "assistant.rule_name" to "규칙 이름",
        "assistant.find_regex" to "찾을 정규식",
        "assistant.replace_with" to "다음으로 바꾸기",
        "assistant.prompt_injections" to "프롬프트 주입 / 로어북",
        "assistant.entry_name" to "항목 이름",
        "assistant.keywords" to "키워드(쉼표로 구분)",
        "assistant.priority" to "우선순위",
        "assistant.always_active" to "항상 활성화",
        "assistant.preset_messages" to "사전 설정 메시지",
        "assistant.quick_messages" to "빠른 메시지",
        "assistant.title" to "제목",
        "assistant.content" to "내용",
        "assistant.message" to "메시지",
        "assistant.delete_preset_message" to "사전 설정 메시지 삭제",
        "assistant.delete_quick_message" to "빠른 메시지 삭제",
        "assistant.save" to "어시스턴트 저장",
        "request_overrides.headers" to "사용자 지정 헤더",
        "request_overrides.add_header" to "사용자 지정 헤더 추가",
        "request_overrides.header" to "헤더",
        "request_overrides.value" to "값",
        "request_overrides.delete_header" to "사용자 지정 헤더 삭제",
        "request_overrides.body" to "사용자 지정 요청 본문",
        "request_overrides.add_body" to "사용자 지정 요청 본문 추가",
        "request_overrides.invalid_json" to "유효한 JSON을 입력하세요",
        "provider.balance_query" to "잔액 조회",
        "provider.balance_api_path" to "잔액 API 경로",
        "provider.balance_result_path" to "결과 JSON 경로",
        "provider.checking_balance" to "잔액 확인 중...",
        "provider.current_balance" to "현재 잔액: %s",
        "provider.balance_failed" to "잔액 조회에 실패했습니다: %s",
        "provider.check_balance" to "잔액 조회",
        "provider.connection_success" to "연결됨 · 사용 가능한 모델 %d개",
        "agent.approval_request" to "에이전트가 이 작업을 요청합니다. 허용할까요?",
        "agent.allow" to "허용",
        "agent.deny" to "거부",
        "agent.local_shell_warning" to "로컬 셸은 현재 사용자 권한으로 실행됩니다. 명령과 영향을 확인하세요.",
        "agent.write_warning" to "파일 변경은 선택한 작업 공간 디렉터리로 제한됩니다.",
        "timeline.execution" to "실행 과정",
        "timeline.expand_execution" to "실행 과정 펼치기",
        "timeline.collapse_execution" to "실행 과정 접기",
        "timeline.expand_steps" to "%d단계 펼치기",
        "timeline.reasoning" to "추론",
        "timeline.reasoning_duration" to "%s초간 추론함",
        "jumper.top" to "맨 위로 이동",
        "jumper.previous" to "이전 메시지",
        "jumper.next" to "다음 메시지",
        "jumper.bottom" to "맨 아래로 이동",
        "dialog.translate_message" to "메시지 번역",
        "dialog.target_language" to "대상 언어",
        "dialog.compress_history" to "대화 기록 압축",
        "dialog.compress" to "압축",
        "dialog.target_tokens" to "목표 토큰",
        "dialog.keep_recent_messages" to "최근 메시지 유지(전체 %d개)",
        "stats.messages" to "메시지",
        "stats.attachments" to "첨부",
        "settings.send_on_enter" to "Enter로 전송",
        "settings.auto_scroll" to "자동 스크롤",
        "settings.message_navigation" to "메시지 탐색",
        "settings.message_navigation_left" to "메시지 탐색을 왼쪽에 표시",
        "settings.show_user_avatar" to "사용자 아바타 표시",
        "settings.user_nickname" to "사용자 별명",
        "settings.show_model_icon" to "모델 아이콘 표시",
        "settings.show_model_name" to "모델 이름 표시",
        "settings.assistant_bubble" to "어시스턴트 말풍선",
        "settings.message_timestamp" to "메시지 시간",
        "settings.reasoning" to "추론 내용",
        "settings.collapse_reasoning" to "완료 후 추론 접기",
        "settings.code_wrap" to "코드 블록 줄바꿈",
        "settings.export_backup" to "백업 내보내기",
        "settings.export" to "내보내기",
        "settings.import_backup" to "백업 가져오기",
        "settings.import" to "가져오기",
        "settings.reset_data" to "모든 데이터 초기화",
        "settings.reset" to "초기화",
        "settings.reset_confirmation_title" to "모든 데이터를 초기화할까요?",
        "settings.confirm_reset" to "데이터 초기화",
        "settings.web_search" to "웹 검색 서비스",
        "settings.searxng_url" to "SearXNG URL",
        "settings.search_result_count" to "검색당 결과 %d개",
        "settings.test_search" to "검색 테스트",
        "settings.search_test_success" to "웹 검색 연결이 정상입니다",
        "settings.search_test_failed" to "검색 테스트에 실패했습니다",
        "settings.add_assistant" to "어시스턴트 추가",
        "settings.assistant_name" to "어시스턴트 이름",
        "settings.copy_assistant" to "어시스턴트 복사",
        "settings.delete_assistant" to "어시스턴트 삭제",
        "settings.tags" to "태그(쉼표로 구분)",
        "settings.model_inherit" to "모델(비워 두면 제공업체 기본값 사용)",
        "settings.select_model" to "모델 선택",
        "settings.system_prompt_inherit" to "시스템 프롬프트(비워 두면 제공업체 기본값 사용)",
        "settings.add_provider" to "제공업체 추가",
        "settings.provider_name" to "제공업체 이름",
        "settings.delete_provider" to "제공업체 삭제",
        "settings.base_url" to "기본 URL",
        "settings.api_key" to "API 키",
        "settings.model" to "모델",
        "settings.test_and_fetch_models" to "연결 테스트 및 모델 가져오기",
        "settings.save_provider" to "제공업체 저장",
        "model_picker.refresh_balance" to "%s 잔액 새로고침",
        "model_picker.current_model" to "현재 모델",
        "model_capability.text" to "텍스트",
        "model_capability.vision" to "비전",
        "model_capability.reasoning" to "추론",
        "model_capability.tools" to "도구"
    ),
    DesktopLanguage.RUSSIAN to mapOf(
        "common.add" to "Добавить",
        "common.cancel" to "Отмена",
        "common.save" to "Сохранить",
        "common.submit" to "Отправить",
        "common.unnamed" to "Без названия",
        "user.you" to "Вы",
        "attachment.remove" to "Удалить вложение",
        "defaults.new_provider" to "Новый провайдер",
        "defaults.new_assistant" to "Новый ассистент",
        "file.import_backup" to "Импорт резервной копии RikkaHub",
        "file.imported_backup" to "Резервная копия импортирована из %s",
        "file.choose_attachments" to "Добавить изображения, аудио, текст или документы",
        "tool.calling" to "Выполняется",
        "tool.completed" to "Выполнено",
        "tool.input" to "Ввод",
        "tool.output" to "Вывод",
        "tool.result" to "Результат инструмента",
        "runtime.request_failed" to "Сбой запроса",
        "runtime.translation_failed" to "Ошибка перевода",
        "runtime.export_failed" to "Ошибка экспорта: %s",
        "runtime.import_failed" to "Ошибка импорта: %s",
        "runtime.add_attachment_failed" to "Не удалось добавить вложение",
        "runtime.mcp_configuration_invalid" to "Конфигурация MCP больше недействительна. Выберите серверы заново в настройках ассистента.",
        "settings.color_mode" to "Режим цвета",
        "settings.system" to "Системный",
        "settings.light" to "Светлый",
        "settings.dark" to "Тёмный",
        "settings.theme_color" to "Цвет темы",
        "settings.font" to "Шрифт интерфейса",
        "settings.chat_font_size" to "Размер шрифта чата",
        "composer.send" to "Отправить; удерживайте, чтобы добавить без ответа",
        "composer.stop_generation" to "Остановить генерацию",
        "composer.add_attachment" to "Добавить вложение",
        "composer.enable_web_search" to "Включить веб-поиск",
        "composer.disable_web_search" to "Выключить веб-поиск",
        "message.copy" to "Копировать",
        "message.regenerate" to "Сгенерировать снова",
        "message.translate" to "Перевести",
        "message.favorite" to "В избранное",
        "message.unfavorite" to "Убрать из избранного",
        "message.edit" to "Изменить",
        "message.delete" to "Удалить",
        "mcp.title" to "Сервисы MCP",
        "mcp.services_for_assistant" to "Сервисов для ассистента: %d",
        "mcp.check_all" to "Проверить все",
        "mcp.open_settings" to "Открыть настройки MCP",
        "mcp.no_servers" to "Сервисы MCP не настроены",
        "mcp.not_checked" to "Не проверено",
        "mcp.checking" to "Проверка",
        "mcp.tools_synced" to "Синхронизировано инструментов: %d",
        "mcp.available_tools" to "Доступно · инструментов: %d",
        "mcp.current_assistant" to "Этот ассистент",
        "mcp.enabled" to "Включено",
        "mcp.unnamed_service" to "Безымянный сервис MCP",
        "sidebar.welcome" to "С возвращением",
        "sidebar.new_chat" to "Новый чат",
        "sidebar.search_chats" to "Поиск чатов",
        "sidebar.favorite_messages" to "Избранные сообщения",
        "sidebar.all_assistants" to "Все ассистенты",
        "sidebar.all_tags" to "Все теги",
        "sidebar.chats" to "Чаты",
        "sidebar.search" to "Поиск",
        "chat.rename" to "Переименовать",
        "chat.export_markdown" to "Экспортировать Markdown",
        "chat.statistics" to "Статистика беседы",
        "chat.compress_history" to "Сжать историю",
        "chat.move_to_folder" to "Переместить в папку",
        "chat.uncategorized" to "Без категории",
        "chat.new_folder" to "Новая папка",
        "conversation.pin" to "Закрепить",
        "conversation.unpin" to "Открепить",
        "settings.chinese_typography" to "Китайская типографика",
        "settings.language" to "Язык",
        "settings.font_description" to "%s; блоки кода остаются моноширинными",
        "stats.characters" to "Символы текста и рассуждений",
        "stats.created_at" to "Создано",
        "stats.updated_at" to "Обновлено",
        "file.add_attachments" to "Добавить вложения",
        "file.parent_directory" to "Родительский каталог",
        "file.selected" to "Выбрано",
        "file.file_name" to "Имя файла",
        "chat.generate_title" to "Создать заголовок",
        "chat.generate_suggestions" to "Создать предложения ответа",
        "chat.set_system_prompt" to "Задать системный промпт",
        "chat.edit_system_prompt" to "Изменить системный промпт",
        "chat.enable_lorebooks" to "Включить лорбуки беседы",
        "chat.disable_lorebooks" to "Выключить лорбуки беседы",
        "chat.close" to "Закрыть",
        "theme.sakura" to "Сакура",
        "theme.ocean" to "Океан",
        "theme.forest" to "Лес",
        "theme.sunset" to "Закат",
        "theme.lavender" to "Лаванда",
        "theme.slate" to "Сланец",
        "font.system" to "Системный по умолчанию",
        "font.sans_serif" to "Без засечек",
        "font.serif" to "С засечками",
        "font.monospace" to "Моноширинный",
        "timeline.today" to "Сегодня",
        "timeline.yesterday" to "Вчера",
        "timeline.day_before_yesterday" to "Позавчера",
        "timeline.days_ago" to "%d дн. назад",
        "sidebar.recent" to "Недавние",
        "sidebar.most_active" to "Самые активные",
        "assistant.global_memory" to "Глобальная общая память",
        "assistant.memory_entries" to "Записи памяти",
        "assistant.add_memory" to "Добавить память",
        "assistant.agent_workspace" to "Рабочая область агента",
        "assistant.workspace_directory" to "Каталог рабочей области",
        "assistant.docker_container" to "Контейнер Docker",
        "assistant.local_shell" to "Локальная оболочка",
        "assistant.enabled_skills" to "Включённые навыки",
        "assistant.temperature" to "Температура",
        "assistant.max_output_tokens" to "Максимум выходных токенов",
        "assistant.context_messages" to "Контекстные сообщения",
        "assistant.inherit_provider" to "Оставьте пустым для наследования настроек провайдера",
        "assistant.stream_output" to "Потоковый вывод",
        "assistant.memory" to "Память",
        "mcp_settings.title" to "Серверы MCP",
        "mcp_settings.add_server" to "Добавить сервер MCP",
        "mcp_settings.server_name" to "Имя сервера",
        "mcp_settings.server_url" to "URL сервера",
        "mcp_settings.enable_server" to "Включить сервер",
        "mcp_settings.sync_tools" to "Синхронизировать инструменты",
        "mcp_settings.delete_server" to "Удалить сервер MCP",
        "assistant.regex_transforms" to "Преобразования regex",
        "assistant.rule_name" to "Имя правила",
        "assistant.find_regex" to "Поисковое regex",
        "assistant.replace_with" to "Заменить на",
        "assistant.prompt_injections" to "Инъекции промптов / лорбуки",
        "assistant.entry_name" to "Имя записи",
        "assistant.keywords" to "Ключевые слова (через запятую)",
        "assistant.priority" to "Приоритет",
        "assistant.always_active" to "Всегда активно",
        "assistant.preset_messages" to "Предустановленные сообщения",
        "assistant.quick_messages" to "Быстрые сообщения",
        "assistant.title" to "Заголовок",
        "assistant.content" to "Содержимое",
        "assistant.message" to "Сообщение",
        "assistant.delete_preset_message" to "Удалить предустановленное сообщение",
        "assistant.delete_quick_message" to "Удалить быстрое сообщение",
        "assistant.save" to "Сохранить ассистента",
        "request_overrides.headers" to "Пользовательские заголовки",
        "request_overrides.add_header" to "Добавить заголовок",
        "request_overrides.header" to "Заголовок",
        "request_overrides.value" to "Значение",
        "request_overrides.delete_header" to "Удалить заголовок",
        "request_overrides.body" to "Пользовательское тело запроса",
        "request_overrides.add_body" to "Добавить тело запроса",
        "request_overrides.invalid_json" to "Введите корректный JSON",
        "provider.balance_query" to "Запрос баланса",
        "provider.balance_api_path" to "Путь API баланса",
        "provider.balance_result_path" to "Путь JSON результата",
        "provider.checking_balance" to "Проверка баланса...",
        "provider.current_balance" to "Текущий баланс: %s",
        "provider.balance_failed" to "Не удалось проверить баланс: %s",
        "provider.check_balance" to "Проверить баланс",
        "provider.connection_success" to "Подключено · доступно моделей: %d",
        "agent.approval_request" to "Агент запрашивает эту операцию. Разрешить?",
        "agent.allow" to "Разрешить",
        "agent.deny" to "Отклонить",
        "agent.local_shell_warning" to "Локальная оболочка выполняется с правами текущего пользователя. Проверьте команду и её последствия.",
        "agent.write_warning" to "Изменения файлов ограничены выбранной рабочей областью.",
        "timeline.execution" to "Выполнение",
        "timeline.expand_execution" to "Развернуть выполнение",
        "timeline.collapse_execution" to "Свернуть выполнение",
        "timeline.expand_steps" to "Развернуть %d шагов",
        "timeline.reasoning" to "Рассуждение",
        "timeline.reasoning_duration" to "Рассуждение заняло %s с",
        "jumper.top" to "К началу",
        "jumper.previous" to "Предыдущее сообщение",
        "jumper.next" to "Следующее сообщение",
        "jumper.bottom" to "К концу",
        "dialog.translate_message" to "Перевести сообщение",
        "dialog.target_language" to "Целевой язык",
        "dialog.compress_history" to "Сжать историю беседы",
        "dialog.compress" to "Сжать",
        "dialog.target_tokens" to "Целевые токены",
        "dialog.keep_recent_messages" to "Сохранить последние сообщения (всего %d)",
        "stats.messages" to "Сообщения",
        "stats.attachments" to "Вложения",
        "settings.send_on_enter" to "Отправлять по Enter",
        "settings.auto_scroll" to "Автопрокрутка",
        "settings.message_navigation" to "Навигация по сообщениям",
        "settings.message_navigation_left" to "Навигация по сообщениям слева",
        "settings.show_user_avatar" to "Показывать аватар пользователя",
        "settings.user_nickname" to "Псевдоним пользователя",
        "settings.show_model_icon" to "Показывать значок модели",
        "settings.show_model_name" to "Показывать имя модели",
        "settings.assistant_bubble" to "Пузырь ассистента",
        "settings.message_timestamp" to "Время сообщения",
        "settings.reasoning" to "Содержание рассуждений",
        "settings.collapse_reasoning" to "Сворачивать рассуждения после завершения",
        "settings.code_wrap" to "Переносить строки кода",
        "settings.export_backup" to "Экспорт резервной копии",
        "settings.export" to "Экспорт",
        "settings.import_backup" to "Импорт резервной копии",
        "settings.import" to "Импорт",
        "settings.reset_data" to "Сбросить все данные",
        "settings.reset" to "Сброс",
        "settings.reset_confirmation_title" to "Сбросить все данные?",
        "settings.confirm_reset" to "Сбросить данные",
        "settings.web_search" to "Сервис веб-поиска",
        "settings.searxng_url" to "URL SearXNG",
        "settings.search_result_count" to "%d результатов на поиск",
        "settings.test_search" to "Проверить поиск",
        "settings.search_test_success" to "Подключение веб-поиска работает",
        "settings.search_test_failed" to "Ошибка проверки поиска",
        "settings.add_assistant" to "Добавить ассистента",
        "settings.assistant_name" to "Имя ассистента",
        "settings.copy_assistant" to "Копировать ассистента",
        "settings.delete_assistant" to "Удалить ассистента",
        "settings.tags" to "Теги (через запятую)",
        "settings.model_inherit" to "Модель (оставьте пустым для значения провайдера)",
        "settings.select_model" to "Выбрать модель",
        "settings.system_prompt_inherit" to "Системный промпт (оставьте пустым для значения провайдера)",
        "settings.add_provider" to "Добавить провайдера",
        "settings.provider_name" to "Имя провайдера",
        "settings.delete_provider" to "Удалить провайдера",
        "settings.base_url" to "Базовый URL",
        "settings.api_key" to "Ключ API",
        "settings.model" to "Модель",
        "settings.test_and_fetch_models" to "Проверить и получить модели",
        "settings.save_provider" to "Сохранить провайдера",
        "model_picker.refresh_balance" to "Обновить баланс %s",
        "model_picker.current_model" to "Текущая модель",
        "model_capability.text" to "Текст",
        "model_capability.vision" to "Зрение",
        "model_capability.reasoning" to "Рассуждение",
        "model_capability.tools" to "Инструменты"
    ),
    DesktopLanguage.SPANISH to mapOf(
        "common.add" to "Agregar",
        "common.cancel" to "Cancelar",
        "common.save" to "Guardar",
        "common.submit" to "Enviar",
        "common.unnamed" to "Sin nombre",
        "user.you" to "Tú",
        "attachment.remove" to "Quitar archivo adjunto",
        "defaults.new_provider" to "Proveedor nuevo",
        "defaults.new_assistant" to "Asistente nuevo",
        "file.import_backup" to "Importar copia de seguridad de RikkaHub",
        "file.imported_backup" to "Copia de seguridad importada desde %s",
        "file.choose_attachments" to "Agregar imágenes, audio, texto o documentos",
        "tool.calling" to "En ejecución",
        "tool.completed" to "Completado",
        "tool.input" to "Entrada",
        "tool.output" to "Salida",
        "tool.result" to "Resultado de la herramienta",
        "runtime.request_failed" to "Error de solicitud",
        "runtime.translation_failed" to "Error de traducción",
        "runtime.export_failed" to "Error de exportación: %s",
        "runtime.import_failed" to "Error de importación: %s",
        "runtime.add_attachment_failed" to "No se pudo agregar el archivo adjunto",
        "runtime.mcp_configuration_invalid" to "La configuración de MCP ya no es válida. Vuelva a seleccionar los servidores en los ajustes del asistente.",
        "settings.color_mode" to "Modo de color",
        "settings.system" to "Sistema",
        "settings.light" to "Claro",
        "settings.dark" to "Oscuro",
        "settings.theme_color" to "Color del tema",
        "settings.font" to "Fuente de la interfaz",
        "settings.chat_font_size" to "Tamaño de fuente del chat",
        "composer.send" to "Enviar; mantén pulsado para agregar sin respuesta",
        "composer.stop_generation" to "Detener generación",
        "composer.add_attachment" to "Agregar archivo adjunto",
        "composer.enable_web_search" to "Activar búsqueda web",
        "composer.disable_web_search" to "Desactivar búsqueda web",
        "message.copy" to "Copiar",
        "message.regenerate" to "Regenerar",
        "message.translate" to "Traducir",
        "message.favorite" to "Favorito",
        "message.unfavorite" to "Quitar de favoritos",
        "message.edit" to "Editar",
        "message.delete" to "Eliminar",
        "mcp.title" to "Servicios MCP",
        "mcp.services_for_assistant" to "%d servicios para este asistente",
        "mcp.check_all" to "Comprobar todo",
        "mcp.open_settings" to "Abrir ajustes de MCP",
        "mcp.no_servers" to "No hay servicios MCP configurados",
        "mcp.not_checked" to "Sin comprobar",
        "mcp.checking" to "Comprobando",
        "mcp.tools_synced" to "%d herramientas sincronizadas",
        "mcp.available_tools" to "Disponible · %d herramientas",
        "mcp.current_assistant" to "Este asistente",
        "mcp.enabled" to "Activado",
        "mcp.unnamed_service" to "Servicio MCP sin nombre",
        "sidebar.welcome" to "Bienvenido de nuevo",
        "sidebar.new_chat" to "Chat nuevo",
        "sidebar.search_chats" to "Buscar chats",
        "sidebar.favorite_messages" to "Mensajes favoritos",
        "sidebar.all_assistants" to "Todos los asistentes",
        "sidebar.all_tags" to "Todas las etiquetas",
        "sidebar.chats" to "Chats",
        "sidebar.search" to "Buscar",
        "chat.rename" to "Cambiar nombre",
        "chat.export_markdown" to "Exportar Markdown",
        "chat.statistics" to "Estadísticas de la conversación",
        "chat.compress_history" to "Comprimir historial",
        "chat.move_to_folder" to "Mover a carpeta",
        "chat.uncategorized" to "Sin categoría",
        "chat.new_folder" to "Carpeta nueva",
        "conversation.pin" to "Fijar",
        "conversation.unpin" to "Desfijar",
        "settings.chinese_typography" to "Tipografía china",
        "settings.language" to "Idioma",
        "settings.font_description" to "%s; los bloques de código permanecen monoespaciados",
        "stats.characters" to "Caracteres de texto y razonamiento",
        "stats.created_at" to "Creado",
        "stats.updated_at" to "Actualizado",
        "file.add_attachments" to "Agregar archivos adjuntos",
        "file.parent_directory" to "Directorio superior",
        "file.selected" to "Seleccionado",
        "file.file_name" to "Nombre de archivo",
        "chat.generate_title" to "Generar título",
        "chat.generate_suggestions" to "Generar sugerencias de respuesta",
        "chat.set_system_prompt" to "Establecer mensaje del sistema",
        "chat.edit_system_prompt" to "Editar mensaje del sistema",
        "chat.enable_lorebooks" to "Activar libros de lore de la conversación",
        "chat.disable_lorebooks" to "Desactivar libros de lore de la conversación",
        "chat.close" to "Cerrar",
        "theme.sakura" to "Sakura",
        "theme.ocean" to "Océano",
        "theme.forest" to "Bosque",
        "theme.sunset" to "Atardecer",
        "theme.lavender" to "Lavanda",
        "theme.slate" to "Pizarra",
        "font.system" to "Predeterminado del sistema",
        "font.sans_serif" to "Sans serif",
        "font.serif" to "Con serif",
        "font.monospace" to "Monoespaciada",
        "timeline.today" to "Hoy",
        "timeline.yesterday" to "Ayer",
        "timeline.day_before_yesterday" to "Anteayer",
        "timeline.days_ago" to "Hace %d días",
        "sidebar.recent" to "Recientes",
        "sidebar.most_active" to "Más activos",
        "assistant.global_memory" to "Memoria global compartida",
        "assistant.memory_entries" to "Entradas de memoria",
        "assistant.add_memory" to "Agregar memoria",
        "assistant.agent_workspace" to "Espacio de trabajo del agente",
        "assistant.workspace_directory" to "Directorio del espacio de trabajo",
        "assistant.docker_container" to "Contenedor Docker",
        "assistant.local_shell" to "Shell local",
        "assistant.enabled_skills" to "Habilidades activadas",
        "assistant.temperature" to "Temperatura",
        "assistant.max_output_tokens" to "Máximo de tokens de salida",
        "assistant.context_messages" to "Mensajes de contexto",
        "assistant.inherit_provider" to "Déjalo vacío para heredar la configuración del proveedor",
        "assistant.stream_output" to "Salida en streaming",
        "assistant.memory" to "Memoria",
        "mcp_settings.title" to "Servidores MCP",
        "mcp_settings.add_server" to "Agregar servidor MCP",
        "mcp_settings.server_name" to "Nombre del servidor",
        "mcp_settings.server_url" to "URL del servidor",
        "mcp_settings.enable_server" to "Activar servidor",
        "mcp_settings.sync_tools" to "Sincronizar herramientas",
        "mcp_settings.delete_server" to "Eliminar servidor MCP",
        "assistant.regex_transforms" to "Transformaciones regex",
        "assistant.rule_name" to "Nombre de regla",
        "assistant.find_regex" to "Regex de búsqueda",
        "assistant.replace_with" to "Reemplazar por",
        "assistant.prompt_injections" to "Inyecciones de prompt / libros de lore",
        "assistant.entry_name" to "Nombre de entrada",
        "assistant.keywords" to "Palabras clave (separadas por comas)",
        "assistant.priority" to "Prioridad",
        "assistant.always_active" to "Siempre activo",
        "assistant.preset_messages" to "Mensajes predefinidos",
        "assistant.quick_messages" to "Mensajes rápidos",
        "assistant.title" to "Título",
        "assistant.content" to "Contenido",
        "assistant.message" to "Mensaje",
        "assistant.delete_preset_message" to "Eliminar mensaje predefinido",
        "assistant.delete_quick_message" to "Eliminar mensaje rápido",
        "assistant.save" to "Guardar asistente",
        "request_overrides.headers" to "Encabezados personalizados",
        "request_overrides.add_header" to "Agregar encabezado personalizado",
        "request_overrides.header" to "Encabezado",
        "request_overrides.value" to "Valor",
        "request_overrides.delete_header" to "Eliminar encabezado personalizado",
        "request_overrides.body" to "Cuerpo de solicitud personalizado",
        "request_overrides.add_body" to "Agregar cuerpo de solicitud",
        "request_overrides.invalid_json" to "Introduce JSON válido",
        "provider.balance_query" to "Consulta de saldo",
        "provider.balance_api_path" to "Ruta de API de saldo",
        "provider.balance_result_path" to "Ruta JSON de resultado",
        "provider.checking_balance" to "Consultando saldo...",
        "provider.current_balance" to "Saldo actual: %s",
        "provider.balance_failed" to "Error al consultar el saldo: %s",
        "provider.check_balance" to "Consultar saldo",
        "provider.connection_success" to "Conectado · %d modelos disponibles",
        "agent.approval_request" to "El agente solicita esta operación. ¿Permitir?",
        "agent.allow" to "Permitir",
        "agent.deny" to "Denegar",
        "agent.local_shell_warning" to "La shell local se ejecuta con los permisos del usuario actual. Confirma el comando y su impacto.",
        "agent.write_warning" to "Los cambios de archivos se limitan al directorio del espacio de trabajo seleccionado.",
        "timeline.execution" to "Ejecución",
        "timeline.expand_execution" to "Expandir ejecución",
        "timeline.collapse_execution" to "Contraer ejecución",
        "timeline.expand_steps" to "Expandir %d pasos",
        "timeline.reasoning" to "Razonamiento",
        "timeline.reasoning_duration" to "Razonó durante %s segundos",
        "jumper.top" to "Ir al inicio",
        "jumper.previous" to "Mensaje anterior",
        "jumper.next" to "Mensaje siguiente",
        "jumper.bottom" to "Ir al final",
        "dialog.translate_message" to "Traducir mensaje",
        "dialog.target_language" to "Idioma de destino",
        "dialog.compress_history" to "Comprimir historial de la conversación",
        "dialog.compress" to "Comprimir",
        "dialog.target_tokens" to "Tokens objetivo",
        "dialog.keep_recent_messages" to "Conservar mensajes recientes (de %d en total)",
        "stats.messages" to "Mensajes",
        "stats.attachments" to "Archivos adjuntos",
        "settings.send_on_enter" to "Enviar con Enter",
        "settings.auto_scroll" to "Desplazamiento automático",
        "settings.message_navigation" to "Navegación de mensajes",
        "settings.message_navigation_left" to "Navegación de mensajes a la izquierda",
        "settings.show_user_avatar" to "Mostrar avatar de usuario",
        "settings.user_nickname" to "Apodo de usuario",
        "settings.show_model_icon" to "Mostrar icono del modelo",
        "settings.show_model_name" to "Mostrar nombre del modelo",
        "settings.assistant_bubble" to "Burbuja del asistente",
        "settings.message_timestamp" to "Hora del mensaje",
        "settings.reasoning" to "Contenido de razonamiento",
        "settings.collapse_reasoning" to "Contraer razonamiento al terminar",
        "settings.code_wrap" to "Ajustar bloques de código",
        "settings.export_backup" to "Exportar copia de seguridad",
        "settings.export" to "Exportar",
        "settings.import_backup" to "Importar copia de seguridad",
        "settings.import" to "Importar",
        "settings.reset_data" to "Restablecer todos los datos",
        "settings.reset" to "Restablecer",
        "settings.reset_confirmation_title" to "¿Restablecer todos los datos?",
        "settings.confirm_reset" to "Restablecer datos",
        "settings.web_search" to "Servicio de búsqueda web",
        "settings.searxng_url" to "URL de SearXNG",
        "settings.search_result_count" to "%d resultados por búsqueda",
        "settings.test_search" to "Probar búsqueda",
        "settings.search_test_success" to "La conexión de búsqueda web funciona",
        "settings.search_test_failed" to "Error en la prueba de búsqueda",
        "settings.add_assistant" to "Agregar asistente",
        "settings.assistant_name" to "Nombre del asistente",
        "settings.copy_assistant" to "Copiar asistente",
        "settings.delete_assistant" to "Eliminar asistente",
        "settings.tags" to "Etiquetas (separadas por comas)",
        "settings.model_inherit" to "Modelo (déjalo vacío para usar el predeterminado del proveedor)",
        "settings.select_model" to "Elegir modelo",
        "settings.system_prompt_inherit" to "Mensaje del sistema (déjalo vacío para usar el predeterminado del proveedor)",
        "settings.add_provider" to "Agregar proveedor",
        "settings.provider_name" to "Nombre del proveedor",
        "settings.delete_provider" to "Eliminar proveedor",
        "settings.base_url" to "URL base",
        "settings.api_key" to "Clave de API",
        "settings.model" to "Modelo",
        "settings.test_and_fetch_models" to "Probar y obtener modelos",
        "settings.save_provider" to "Guardar proveedor",
        "model_picker.refresh_balance" to "Actualizar saldo de %s",
        "model_picker.current_model" to "Modelo actual",
        "model_capability.text" to "Texto",
        "model_capability.vision" to "Visión",
        "model_capability.reasoning" to "Razonamiento",
        "model_capability.tools" to "Herramientas"
    ),
    DesktopLanguage.FRENCH to mapOf(
        "common.add" to "Ajouter",
        "common.cancel" to "Annuler",
        "common.save" to "Enregistrer",
        "common.submit" to "Envoyer",
        "common.unnamed" to "Sans nom",
        "user.you" to "Vous",
        "attachment.remove" to "Retirer la pièce jointe",
        "defaults.new_provider" to "Nouveau fournisseur",
        "defaults.new_assistant" to "Nouvel assistant",
        "file.import_backup" to "Importer une sauvegarde RikkaHub",
        "file.imported_backup" to "Sauvegarde importée depuis %s",
        "file.choose_attachments" to "Ajouter des images, de l'audio, du texte ou des documents",
        "tool.calling" to "En cours",
        "tool.completed" to "Terminé",
        "tool.input" to "Entrée",
        "tool.output" to "Sortie",
        "tool.result" to "Résultat de l'outil",
        "runtime.request_failed" to "Échec de la requête",
        "runtime.translation_failed" to "Échec de la traduction",
        "runtime.export_failed" to "Échec de l'exportation : %s",
        "runtime.import_failed" to "Échec de l'importation : %s",
        "runtime.add_attachment_failed" to "Impossible d'ajouter la pièce jointe",
        "runtime.mcp_configuration_invalid" to "La configuration MCP n'est plus valide. Sélectionnez à nouveau les serveurs dans les paramètres de l'assistant.",
        "settings.color_mode" to "Mode de couleur",
        "settings.system" to "Système",
        "settings.light" to "Clair",
        "settings.dark" to "Sombre",
        "settings.theme_color" to "Couleur du thème",
        "settings.font" to "Police de l'interface",
        "settings.chat_font_size" to "Taille de police du chat",
        "composer.send" to "Envoyer ; maintenez pour ajouter sans réponse",
        "composer.stop_generation" to "Arrêter la génération",
        "composer.add_attachment" to "Ajouter une pièce jointe",
        "composer.enable_web_search" to "Activer la recherche web",
        "composer.disable_web_search" to "Désactiver la recherche web",
        "message.copy" to "Copier",
        "message.regenerate" to "Régénérer",
        "message.translate" to "Traduire",
        "message.favorite" to "Ajouter aux favoris",
        "message.unfavorite" to "Retirer des favoris",
        "message.edit" to "Modifier",
        "message.delete" to "Supprimer",
        "mcp.title" to "Services MCP",
        "mcp.services_for_assistant" to "%d services pour cet assistant",
        "mcp.check_all" to "Tout vérifier",
        "mcp.open_settings" to "Ouvrir les paramètres MCP",
        "mcp.no_servers" to "Aucun service MCP configuré",
        "mcp.not_checked" to "Non vérifié",
        "mcp.checking" to "Vérification",
        "mcp.tools_synced" to "%d outils synchronisés",
        "mcp.available_tools" to "Disponible · %d outils",
        "mcp.current_assistant" to "Cet assistant",
        "mcp.enabled" to "Activé",
        "mcp.unnamed_service" to "Service MCP sans nom",
        "sidebar.welcome" to "Bon retour",
        "sidebar.new_chat" to "Nouveau chat",
        "sidebar.search_chats" to "Rechercher des chats",
        "sidebar.favorite_messages" to "Messages favoris",
        "sidebar.all_assistants" to "Tous les assistants",
        "sidebar.all_tags" to "Toutes les étiquettes",
        "sidebar.chats" to "Chats",
        "sidebar.search" to "Rechercher",
        "chat.rename" to "Renommer",
        "chat.export_markdown" to "Exporter en Markdown",
        "chat.statistics" to "Statistiques de la conversation",
        "chat.compress_history" to "Compresser l'historique",
        "chat.move_to_folder" to "Déplacer vers le dossier",
        "chat.uncategorized" to "Sans catégorie",
        "chat.new_folder" to "Nouveau dossier",
        "conversation.pin" to "Épingler",
        "conversation.unpin" to "Désépingler",
        "settings.chinese_typography" to "Typographie chinoise",
        "settings.language" to "Langue",
        "settings.font_description" to "%s ; les blocs de code restent à chasse fixe",
        "stats.characters" to "Caractères de texte et de raisonnement",
        "stats.created_at" to "Créé",
        "stats.updated_at" to "Mis à jour",
        "file.add_attachments" to "Ajouter des pièces jointes",
        "file.parent_directory" to "Répertoire parent",
        "file.selected" to "Sélectionné",
        "file.file_name" to "Nom de fichier",
        "chat.generate_title" to "Générer le titre",
        "chat.generate_suggestions" to "Générer des suggestions de réponse",
        "chat.set_system_prompt" to "Définir l'invite système",
        "chat.edit_system_prompt" to "Modifier l'invite système",
        "chat.enable_lorebooks" to "Activer les lorebooks de la conversation",
        "chat.disable_lorebooks" to "Désactiver les lorebooks de la conversation",
        "chat.close" to "Fermer",
        "theme.sakura" to "Sakura",
        "theme.ocean" to "Océan",
        "theme.forest" to "Forêt",
        "theme.sunset" to "Coucher de soleil",
        "theme.lavender" to "Lavande",
        "theme.slate" to "Ardoise",
        "font.system" to "Valeur système",
        "font.sans_serif" to "Sans empattement",
        "font.serif" to "Avec empattement",
        "font.monospace" to "Monospace",
        "timeline.today" to "Aujourd'hui",
        "timeline.yesterday" to "Hier",
        "timeline.day_before_yesterday" to "Avant-hier",
        "timeline.days_ago" to "Il y a %d jours",
        "sidebar.recent" to "Récents",
        "sidebar.most_active" to "Les plus actifs",
        "assistant.global_memory" to "Mémoire partagée globale",
        "assistant.memory_entries" to "Entrées de mémoire",
        "assistant.add_memory" to "Ajouter une mémoire",
        "assistant.agent_workspace" to "Espace de travail de l'agent",
        "assistant.workspace_directory" to "Répertoire de l'espace de travail",
        "assistant.docker_container" to "Conteneur Docker",
        "assistant.local_shell" to "Shell local",
        "assistant.enabled_skills" to "Compétences activées",
        "assistant.temperature" to "Température",
        "assistant.max_output_tokens" to "Maximum de jetons de sortie",
        "assistant.context_messages" to "Messages de contexte",
        "assistant.inherit_provider" to "Laissez vide pour hériter des réglages du fournisseur",
        "assistant.stream_output" to "Sortie en flux",
        "assistant.memory" to "Mémoire",
        "mcp_settings.title" to "Serveurs MCP",
        "mcp_settings.add_server" to "Ajouter un serveur MCP",
        "mcp_settings.server_name" to "Nom du serveur",
        "mcp_settings.server_url" to "URL du serveur",
        "mcp_settings.enable_server" to "Activer le serveur",
        "mcp_settings.sync_tools" to "Synchroniser les outils",
        "mcp_settings.delete_server" to "Supprimer le serveur MCP",
        "assistant.regex_transforms" to "Transformations regex",
        "assistant.rule_name" to "Nom de règle",
        "assistant.find_regex" to "Regex de recherche",
        "assistant.replace_with" to "Remplacer par",
        "assistant.prompt_injections" to "Injections de prompt / lorebooks",
        "assistant.entry_name" to "Nom de l'entrée",
        "assistant.keywords" to "Mots-clés (séparés par des virgules)",
        "assistant.priority" to "Priorité",
        "assistant.always_active" to "Toujours actif",
        "assistant.preset_messages" to "Messages prédéfinis",
        "assistant.quick_messages" to "Messages rapides",
        "assistant.title" to "Titre",
        "assistant.content" to "Contenu",
        "assistant.message" to "Message",
        "assistant.delete_preset_message" to "Supprimer le message prédéfini",
        "assistant.delete_quick_message" to "Supprimer le message rapide",
        "assistant.save" to "Enregistrer l'assistant",
        "request_overrides.headers" to "En-têtes personnalisés",
        "request_overrides.add_header" to "Ajouter un en-tête personnalisé",
        "request_overrides.header" to "En-tête",
        "request_overrides.value" to "Valeur",
        "request_overrides.delete_header" to "Supprimer l'en-tête personnalisé",
        "request_overrides.body" to "Corps de requête personnalisé",
        "request_overrides.add_body" to "Ajouter un corps de requête",
        "request_overrides.invalid_json" to "Saisissez un JSON valide",
        "provider.balance_query" to "Consultation du solde",
        "provider.balance_api_path" to "Chemin d'API du solde",
        "provider.balance_result_path" to "Chemin JSON du résultat",
        "provider.checking_balance" to "Vérification du solde...",
        "provider.current_balance" to "Solde actuel : %s",
        "provider.balance_failed" to "Échec de la vérification du solde : %s",
        "provider.check_balance" to "Vérifier le solde",
        "provider.connection_success" to "Connecté · %d modèles disponibles",
        "agent.approval_request" to "L'agent demande cette opération. L'autoriser ?",
        "agent.allow" to "Autoriser",
        "agent.deny" to "Refuser",
        "agent.local_shell_warning" to "Le shell local s'exécute avec les autorisations de votre utilisateur actuel. Confirmez la commande et son impact.",
        "agent.write_warning" to "Les modifications de fichiers sont limitées au répertoire de l'espace de travail sélectionné.",
        "timeline.execution" to "Exécution",
        "timeline.expand_execution" to "Développer l'exécution",
        "timeline.collapse_execution" to "Réduire l'exécution",
        "timeline.expand_steps" to "Développer %d étapes",
        "timeline.reasoning" to "Raisonnement",
        "timeline.reasoning_duration" to "A raisonné pendant %s secondes",
        "jumper.top" to "Aller en haut",
        "jumper.previous" to "Message précédent",
        "jumper.next" to "Message suivant",
        "jumper.bottom" to "Aller en bas",
        "dialog.translate_message" to "Traduire le message",
        "dialog.target_language" to "Langue cible",
        "dialog.compress_history" to "Compresser l'historique de la conversation",
        "dialog.compress" to "Compresser",
        "dialog.target_tokens" to "Jetons cibles",
        "dialog.keep_recent_messages" to "Conserver les messages récents (sur %d au total)",
        "stats.messages" to "Messages",
        "stats.attachments" to "Pièces jointes",
        "settings.send_on_enter" to "Envoyer avec Entrée",
        "settings.auto_scroll" to "Défilement automatique",
        "settings.message_navigation" to "Navigation des messages",
        "settings.message_navigation_left" to "Navigation des messages à gauche",
        "settings.show_user_avatar" to "Afficher l'avatar utilisateur",
        "settings.user_nickname" to "Surnom de l'utilisateur",
        "settings.show_model_icon" to "Afficher l'icône du modèle",
        "settings.show_model_name" to "Afficher le nom du modèle",
        "settings.assistant_bubble" to "Bulle de l'assistant",
        "settings.message_timestamp" to "Heure du message",
        "settings.reasoning" to "Contenu du raisonnement",
        "settings.collapse_reasoning" to "Réduire le raisonnement après la fin",
        "settings.code_wrap" to "Retour à la ligne dans les blocs de code",
        "settings.export_backup" to "Exporter la sauvegarde",
        "settings.export" to "Exporter",
        "settings.import_backup" to "Importer une sauvegarde",
        "settings.import" to "Importer",
        "settings.reset_data" to "Réinitialiser toutes les données",
        "settings.reset" to "Réinitialiser",
        "settings.reset_confirmation_title" to "Réinitialiser toutes les données ?",
        "settings.confirm_reset" to "Réinitialiser les données",
        "settings.web_search" to "Service de recherche web",
        "settings.searxng_url" to "URL SearXNG",
        "settings.search_result_count" to "%d résultats par recherche",
        "settings.test_search" to "Tester la recherche",
        "settings.search_test_success" to "La connexion de recherche web fonctionne",
        "settings.search_test_failed" to "Échec du test de recherche",
        "settings.add_assistant" to "Ajouter un assistant",
        "settings.assistant_name" to "Nom de l'assistant",
        "settings.copy_assistant" to "Copier l'assistant",
        "settings.delete_assistant" to "Supprimer l'assistant",
        "settings.tags" to "Étiquettes (séparées par des virgules)",
        "settings.model_inherit" to "Modèle (laissez vide pour utiliser celui du fournisseur)",
        "settings.select_model" to "Choisir un modèle",
        "settings.system_prompt_inherit" to "Invite système (laissez vide pour utiliser celle du fournisseur)",
        "settings.add_provider" to "Ajouter un fournisseur",
        "settings.provider_name" to "Nom du fournisseur",
        "settings.delete_provider" to "Supprimer le fournisseur",
        "settings.base_url" to "URL de base",
        "settings.api_key" to "Clé API",
        "settings.model" to "Modèle",
        "settings.test_and_fetch_models" to "Tester et récupérer les modèles",
        "settings.save_provider" to "Enregistrer le fournisseur",
        "model_picker.refresh_balance" to "Actualiser le solde de %s",
        "model_picker.current_model" to "Modèle actuel",
        "model_capability.text" to "Texte",
        "model_capability.vision" to "Vision",
        "model_capability.reasoning" to "Raisonnement",
        "model_capability.tools" to "Outils"
    ),
    DesktopLanguage.GERMAN to mapOf(
        "common.add" to "Hinzufügen",
        "common.cancel" to "Abbrechen",
        "common.save" to "Speichern",
        "common.submit" to "Senden",
        "common.unnamed" to "Unbenannt",
        "user.you" to "Du",
        "attachment.remove" to "Anhang entfernen",
        "defaults.new_provider" to "Neuer Anbieter",
        "defaults.new_assistant" to "Neuer Assistent",
        "file.import_backup" to "RikkaHub-Sicherung importieren",
        "file.imported_backup" to "Sicherung aus %s importiert",
        "file.choose_attachments" to "Bilder, Audio, Text oder Dokumente hinzufügen",
        "tool.calling" to "Wird ausgeführt",
        "tool.completed" to "Abgeschlossen",
        "tool.input" to "Eingabe",
        "tool.output" to "Ausgabe",
        "tool.result" to "Werkzeugergebnis",
        "runtime.request_failed" to "Anfrage fehlgeschlagen",
        "runtime.translation_failed" to "Übersetzung fehlgeschlagen",
        "runtime.export_failed" to "Export fehlgeschlagen: %s",
        "runtime.import_failed" to "Import fehlgeschlagen: %s",
        "runtime.add_attachment_failed" to "Anhang konnte nicht hinzugefügt werden",
        "runtime.mcp_configuration_invalid" to "Die MCP-Konfiguration ist nicht mehr gültig. Wählen Sie die Server in den Assistenteneinstellungen erneut aus.",
        "settings.color_mode" to "Farbmodus",
        "settings.system" to "System",
        "settings.light" to "Hell",
        "settings.dark" to "Dunkel",
        "settings.theme_color" to "Themenfarbe",
        "settings.font" to "Oberflächenschrift",
        "settings.chat_font_size" to "Chat-Schriftgröße",
        "composer.send" to "Senden; gedrückt halten, um ohne Antwort hinzuzufügen",
        "composer.stop_generation" to "Generierung stoppen",
        "composer.add_attachment" to "Anhang hinzufügen",
        "composer.enable_web_search" to "Websuche aktivieren",
        "composer.disable_web_search" to "Websuche deaktivieren",
        "message.copy" to "Kopieren",
        "message.regenerate" to "Neu generieren",
        "message.translate" to "Übersetzen",
        "message.favorite" to "Favorisieren",
        "message.unfavorite" to "Aus Favoriten entfernen",
        "message.edit" to "Bearbeiten",
        "message.delete" to "Löschen",
        "mcp.title" to "MCP-Dienste",
        "mcp.services_for_assistant" to "%d Dienste für diesen Assistenten",
        "mcp.check_all" to "Alle prüfen",
        "mcp.open_settings" to "MCP-Einstellungen öffnen",
        "mcp.no_servers" to "Keine MCP-Dienste konfiguriert",
        "mcp.not_checked" to "Nicht geprüft",
        "mcp.checking" to "Wird geprüft",
        "mcp.tools_synced" to "%d Werkzeuge synchronisiert",
        "mcp.available_tools" to "Verfügbar · %d Werkzeuge",
        "mcp.current_assistant" to "Dieser Assistent",
        "mcp.enabled" to "Aktiviert",
        "mcp.unnamed_service" to "Unbenannter MCP-Dienst",
        "sidebar.welcome" to "Willkommen zurück",
        "sidebar.new_chat" to "Neuer Chat",
        "sidebar.search_chats" to "Chats suchen",
        "sidebar.favorite_messages" to "Favorisierte Nachrichten",
        "sidebar.all_assistants" to "Alle Assistenten",
        "sidebar.all_tags" to "Alle Tags",
        "sidebar.chats" to "Chats",
        "sidebar.search" to "Suchen",
        "chat.rename" to "Umbenennen",
        "chat.export_markdown" to "Markdown exportieren",
        "chat.statistics" to "Gesprächsstatistik",
        "chat.compress_history" to "Verlauf komprimieren",
        "chat.move_to_folder" to "In Ordner verschieben",
        "chat.uncategorized" to "Nicht kategorisiert",
        "chat.new_folder" to "Neuer Ordner",
        "conversation.pin" to "Anheften",
        "conversation.unpin" to "Lösen",
        "settings.chinese_typography" to "Chinesische Typografie",
        "settings.language" to "Sprache",
        "settings.font_description" to "%s; Codeblöcke bleiben monospaced",
        "stats.characters" to "Text- und Denkzeichen",
        "stats.created_at" to "Erstellt",
        "stats.updated_at" to "Aktualisiert",
        "file.add_attachments" to "Anhänge hinzufügen",
        "file.parent_directory" to "Übergeordnetes Verzeichnis",
        "file.selected" to "Ausgewählt",
        "file.file_name" to "Dateiname",
        "chat.generate_title" to "Titel generieren",
        "chat.generate_suggestions" to "Antwortvorschläge generieren",
        "chat.set_system_prompt" to "Systemprompt festlegen",
        "chat.edit_system_prompt" to "Systemprompt bearbeiten",
        "chat.enable_lorebooks" to "Lorebooks für dieses Gespräch aktivieren",
        "chat.disable_lorebooks" to "Lorebooks für dieses Gespräch deaktivieren",
        "chat.close" to "Schließen",
        "theme.sakura" to "Sakura",
        "theme.ocean" to "Ozean",
        "theme.forest" to "Wald",
        "theme.sunset" to "Sonnenuntergang",
        "theme.lavender" to "Lavendel",
        "theme.slate" to "Schiefer",
        "font.system" to "Systemstandard",
        "font.sans_serif" to "Serifenlos",
        "font.serif" to "Serif",
        "font.monospace" to "Monospace",
        "timeline.today" to "Heute",
        "timeline.yesterday" to "Gestern",
        "timeline.day_before_yesterday" to "Vorgestern",
        "timeline.days_ago" to "Vor %d Tagen",
        "sidebar.recent" to "Kürzlich",
        "sidebar.most_active" to "Am häufigsten verwendet",
        "assistant.global_memory" to "Globaler gemeinsamer Speicher",
        "assistant.memory_entries" to "Speichereinträge",
        "assistant.add_memory" to "Speicher hinzufügen",
        "assistant.agent_workspace" to "Agent-Arbeitsbereich",
        "assistant.workspace_directory" to "Arbeitsbereichsverzeichnis",
        "assistant.docker_container" to "Docker-Container",
        "assistant.local_shell" to "Lokale Shell",
        "assistant.enabled_skills" to "Aktivierte Skills",
        "assistant.temperature" to "Temperatur",
        "assistant.max_output_tokens" to "Maximale Ausgabe-Token",
        "assistant.context_messages" to "Kontextnachrichten",
        "assistant.inherit_provider" to "Leer lassen, um die Anbietereinstellung zu übernehmen",
        "assistant.stream_output" to "Streaming-Ausgabe",
        "assistant.memory" to "Speicher",
        "mcp_settings.title" to "MCP-Server",
        "mcp_settings.add_server" to "MCP-Server hinzufügen",
        "mcp_settings.server_name" to "Servername",
        "mcp_settings.server_url" to "Server-URL",
        "mcp_settings.enable_server" to "Server aktivieren",
        "mcp_settings.sync_tools" to "Werkzeuge synchronisieren",
        "mcp_settings.delete_server" to "MCP-Server löschen",
        "assistant.regex_transforms" to "Regex-Transformationen",
        "assistant.rule_name" to "Regelname",
        "assistant.find_regex" to "Such-Regex",
        "assistant.replace_with" to "Ersetzen durch",
        "assistant.prompt_injections" to "Prompt-Injektionen / Lorebooks",
        "assistant.entry_name" to "Eintragsname",
        "assistant.keywords" to "Schlüsselwörter (durch Kommas getrennt)",
        "assistant.priority" to "Priorität",
        "assistant.always_active" to "Immer aktiv",
        "assistant.preset_messages" to "Voreingestellte Nachrichten",
        "assistant.quick_messages" to "Schnellnachrichten",
        "assistant.title" to "Titel",
        "assistant.content" to "Inhalt",
        "assistant.message" to "Nachricht",
        "assistant.delete_preset_message" to "Voreingestellte Nachricht löschen",
        "assistant.delete_quick_message" to "Schnellnachricht löschen",
        "assistant.save" to "Assistenten speichern",
        "request_overrides.headers" to "Benutzerdefinierte Header",
        "request_overrides.add_header" to "Benutzerdefinierten Header hinzufügen",
        "request_overrides.header" to "Header",
        "request_overrides.value" to "Wert",
        "request_overrides.delete_header" to "Benutzerdefinierten Header löschen",
        "request_overrides.body" to "Benutzerdefinierter Anfragetext",
        "request_overrides.add_body" to "Anfragetext hinzufügen",
        "request_overrides.invalid_json" to "Gültiges JSON eingeben",
        "provider.balance_query" to "Guthabenabfrage",
        "provider.balance_api_path" to "Guthaben-API-Pfad",
        "provider.balance_result_path" to "Ergebnis-JSON-Pfad",
        "provider.checking_balance" to "Guthaben wird geprüft...",
        "provider.current_balance" to "Aktuelles Guthaben: %s",
        "provider.balance_failed" to "Guthabenabfrage fehlgeschlagen: %s",
        "provider.check_balance" to "Guthaben prüfen",
        "provider.connection_success" to "Verbunden · %d Modelle verfügbar",
        "agent.approval_request" to "Der Agent fordert diesen Vorgang an. Zulassen?",
        "agent.allow" to "Zulassen",
        "agent.deny" to "Ablehnen",
        "agent.local_shell_warning" to "Die lokale Shell läuft mit den Rechten Ihres aktuellen Benutzers. Bestätigen Sie den Befehl und seine Auswirkungen.",
        "agent.write_warning" to "Dateiänderungen sind auf das ausgewählte Arbeitsverzeichnis beschränkt.",
        "timeline.execution" to "Ausführung",
        "timeline.expand_execution" to "Ausführung aufklappen",
        "timeline.collapse_execution" to "Ausführung einklappen",
        "timeline.expand_steps" to "%d Schritte aufklappen",
        "timeline.reasoning" to "Denken",
        "timeline.reasoning_duration" to "%s Sekunden nachgedacht",
        "jumper.top" to "Zum Anfang",
        "jumper.previous" to "Vorherige Nachricht",
        "jumper.next" to "Nächste Nachricht",
        "jumper.bottom" to "Zum Ende",
        "dialog.translate_message" to "Nachricht übersetzen",
        "dialog.target_language" to "Zielsprache",
        "dialog.compress_history" to "Gesprächsverlauf komprimieren",
        "dialog.compress" to "Komprimieren",
        "dialog.target_tokens" to "Ziel-Token",
        "dialog.keep_recent_messages" to "Letzte Nachrichten behalten (von insgesamt %d)",
        "stats.messages" to "Nachrichten",
        "stats.attachments" to "Anhänge",
        "settings.send_on_enter" to "Mit Enter senden",
        "settings.auto_scroll" to "Automatisch scrollen",
        "settings.message_navigation" to "Nachrichtennavigation",
        "settings.message_navigation_left" to "Nachrichtennavigation links",
        "settings.show_user_avatar" to "Benutzeravatar anzeigen",
        "settings.user_nickname" to "Benutzername",
        "settings.show_model_icon" to "Modellsymbol anzeigen",
        "settings.show_model_name" to "Modellnamen anzeigen",
        "settings.assistant_bubble" to "Assistentensprechblase",
        "settings.message_timestamp" to "Nachrichtenzeit",
        "settings.reasoning" to "Denkinhalt",
        "settings.collapse_reasoning" to "Denkinhalt nach Abschluss einklappen",
        "settings.code_wrap" to "Codeblöcke umbrechen",
        "settings.export_backup" to "Sicherung exportieren",
        "settings.export" to "Exportieren",
        "settings.import_backup" to "Sicherung importieren",
        "settings.import" to "Importieren",
        "settings.reset_data" to "Alle Daten zurücksetzen",
        "settings.reset" to "Zurücksetzen",
        "settings.reset_confirmation_title" to "Alle Daten zurücksetzen?",
        "settings.confirm_reset" to "Daten zurücksetzen",
        "settings.web_search" to "Websuchdienst",
        "settings.searxng_url" to "SearXNG-URL",
        "settings.search_result_count" to "%d Ergebnisse pro Suche",
        "settings.test_search" to "Suche testen",
        "settings.search_test_success" to "Websuchverbindung funktioniert",
        "settings.search_test_failed" to "Suchtest fehlgeschlagen",
        "settings.add_assistant" to "Assistenten hinzufügen",
        "settings.assistant_name" to "Assistentenname",
        "settings.copy_assistant" to "Assistenten kopieren",
        "settings.delete_assistant" to "Assistenten löschen",
        "settings.tags" to "Tags (durch Kommas getrennt)",
        "settings.model_inherit" to "Modell (leer lassen für den Anbieterstandard)",
        "settings.select_model" to "Modell auswählen",
        "settings.system_prompt_inherit" to "Systemprompt (leer lassen für den Anbieterstandard)",
        "settings.add_provider" to "Anbieter hinzufügen",
        "settings.provider_name" to "Anbietername",
        "settings.delete_provider" to "Anbieter löschen",
        "settings.base_url" to "Basis-URL",
        "settings.api_key" to "API-Schlüssel",
        "settings.model" to "Modell",
        "settings.test_and_fetch_models" to "Testen und Modelle abrufen",
        "settings.save_provider" to "Anbieter speichern",
        "model_picker.refresh_balance" to "Guthaben von %s aktualisieren",
        "model_picker.current_model" to "Aktuelles Modell",
        "model_capability.text" to "Text",
        "model_capability.vision" to "Bild",
        "model_capability.reasoning" to "Denken",
        "model_capability.tools" to "Werkzeuge"
    ),
    DesktopLanguage.PORTUGUESE_BRAZIL to mapOf(
        "common.add" to "Adicionar",
        "common.cancel" to "Cancelar",
        "common.save" to "Salvar",
        "common.submit" to "Enviar",
        "common.unnamed" to "Sem nome",
        "user.you" to "Você",
        "attachment.remove" to "Remover anexo",
        "defaults.new_provider" to "Novo provedor",
        "defaults.new_assistant" to "Novo assistente",
        "file.import_backup" to "Importar backup do RikkaHub",
        "file.imported_backup" to "Backup importado de %s",
        "file.choose_attachments" to "Adicionar imagens, áudio, texto ou documentos",
        "tool.calling" to "Em execução",
        "tool.completed" to "Concluído",
        "tool.input" to "Entrada",
        "tool.output" to "Saída",
        "tool.result" to "Resultado da ferramenta",
        "runtime.request_failed" to "Falha na solicitação",
        "runtime.translation_failed" to "Falha na tradução",
        "runtime.export_failed" to "Falha na exportação: %s",
        "runtime.import_failed" to "Falha na importação: %s",
        "runtime.add_attachment_failed" to "Não foi possível adicionar o anexo",
        "runtime.mcp_configuration_invalid" to "A configuração MCP não é mais válida. Selecione os servidores novamente nas configurações do assistente.",
        "settings.color_mode" to "Modo de cor",
        "settings.system" to "Sistema",
        "settings.light" to "Claro",
        "settings.dark" to "Escuro",
        "settings.theme_color" to "Cor do tema",
        "settings.font" to "Fonte da interface",
        "settings.chat_font_size" to "Tamanho da fonte do chat",
        "composer.send" to "Enviar; mantenha pressionado para adicionar sem resposta",
        "composer.stop_generation" to "Parar geração",
        "composer.add_attachment" to "Adicionar anexo",
        "composer.enable_web_search" to "Ativar pesquisa na web",
        "composer.disable_web_search" to "Desativar pesquisa na web",
        "message.copy" to "Copiar",
        "message.regenerate" to "Gerar novamente",
        "message.translate" to "Traduzir",
        "message.favorite" to "Favoritar",
        "message.unfavorite" to "Remover dos favoritos",
        "message.edit" to "Editar",
        "message.delete" to "Excluir",
        "mcp.title" to "Serviços MCP",
        "mcp.services_for_assistant" to "%d serviços para este assistente",
        "mcp.check_all" to "Verificar todos",
        "mcp.open_settings" to "Abrir configurações MCP",
        "mcp.no_servers" to "Nenhum serviço MCP configurado",
        "mcp.not_checked" to "Não verificado",
        "mcp.checking" to "Verificando",
        "mcp.tools_synced" to "%d ferramentas sincronizadas",
        "mcp.available_tools" to "Disponível · %d ferramentas",
        "mcp.current_assistant" to "Este assistente",
        "mcp.enabled" to "Ativado",
        "mcp.unnamed_service" to "Serviço MCP sem nome",
        "sidebar.welcome" to "Bem-vindo de volta",
        "sidebar.new_chat" to "Novo chat",
        "sidebar.search_chats" to "Pesquisar chats",
        "sidebar.favorite_messages" to "Mensagens favoritas",
        "sidebar.all_assistants" to "Todos os assistentes",
        "sidebar.all_tags" to "Todas as tags",
        "sidebar.chats" to "Chats",
        "sidebar.search" to "Pesquisar",
        "chat.rename" to "Renomear",
        "chat.export_markdown" to "Exportar Markdown",
        "chat.statistics" to "Estatísticas da conversa",
        "chat.compress_history" to "Compactar histórico",
        "chat.move_to_folder" to "Mover para pasta",
        "chat.uncategorized" to "Sem categoria",
        "chat.new_folder" to "Nova pasta",
        "conversation.pin" to "Fixar",
        "conversation.unpin" to "Desafixar",
        "settings.chinese_typography" to "Tipografia chinesa",
        "settings.language" to "Idioma",
        "settings.font_description" to "%s; blocos de código permanecem monoespaçados",
        "stats.characters" to "Caracteres de texto e raciocínio",
        "stats.created_at" to "Criado",
        "stats.updated_at" to "Atualizado",
        "file.add_attachments" to "Adicionar anexos",
        "file.parent_directory" to "Diretório pai",
        "file.selected" to "Selecionado",
        "file.file_name" to "Nome do arquivo",
        "chat.generate_title" to "Gerar título",
        "chat.generate_suggestions" to "Gerar sugestões de resposta",
        "chat.set_system_prompt" to "Definir prompt do sistema",
        "chat.edit_system_prompt" to "Editar prompt do sistema",
        "chat.enable_lorebooks" to "Ativar livros de lore da conversa",
        "chat.disable_lorebooks" to "Desativar livros de lore da conversa",
        "chat.close" to "Fechar",
        "theme.sakura" to "Sakura",
        "theme.ocean" to "Oceano",
        "theme.forest" to "Floresta",
        "theme.sunset" to "Pôr do sol",
        "theme.lavender" to "Lavanda",
        "theme.slate" to "Ardósia",
        "font.system" to "Padrão do sistema",
        "font.sans_serif" to "Sem serifa",
        "font.serif" to "Com serifa",
        "font.monospace" to "Monoespaçada",
        "timeline.today" to "Hoje",
        "timeline.yesterday" to "Ontem",
        "timeline.day_before_yesterday" to "Anteontem",
        "timeline.days_ago" to "%d dias atrás",
        "sidebar.recent" to "Recentes",
        "sidebar.most_active" to "Mais usados",
        "assistant.global_memory" to "Memória global compartilhada",
        "assistant.memory_entries" to "Entradas de memória",
        "assistant.add_memory" to "Adicionar memória",
        "assistant.agent_workspace" to "Espaço de trabalho do agente",
        "assistant.workspace_directory" to "Diretório do espaço de trabalho",
        "assistant.docker_container" to "Contêiner Docker",
        "assistant.local_shell" to "Shell local",
        "assistant.enabled_skills" to "Habilidades ativadas",
        "assistant.temperature" to "Temperatura",
        "assistant.max_output_tokens" to "Máximo de tokens de saída",
        "assistant.context_messages" to "Mensagens de contexto",
        "assistant.inherit_provider" to "Deixe em branco para herdar a configuração do provedor",
        "assistant.stream_output" to "Saída em streaming",
        "assistant.memory" to "Memória",
        "mcp_settings.title" to "Servidores MCP",
        "mcp_settings.add_server" to "Adicionar servidor MCP",
        "mcp_settings.server_name" to "Nome do servidor",
        "mcp_settings.server_url" to "URL do servidor",
        "mcp_settings.enable_server" to "Ativar servidor",
        "mcp_settings.sync_tools" to "Sincronizar ferramentas",
        "mcp_settings.delete_server" to "Excluir servidor MCP",
        "assistant.regex_transforms" to "Transformações regex",
        "assistant.rule_name" to "Nome da regra",
        "assistant.find_regex" to "Regex de busca",
        "assistant.replace_with" to "Substituir por",
        "assistant.prompt_injections" to "Injeções de prompt / livros de lore",
        "assistant.entry_name" to "Nome da entrada",
        "assistant.keywords" to "Palavras-chave (separadas por vírgulas)",
        "assistant.priority" to "Prioridade",
        "assistant.always_active" to "Sempre ativo",
        "assistant.preset_messages" to "Mensagens predefinidas",
        "assistant.quick_messages" to "Mensagens rápidas",
        "assistant.title" to "Título",
        "assistant.content" to "Conteúdo",
        "assistant.message" to "Mensagem",
        "assistant.delete_preset_message" to "Excluir mensagem predefinida",
        "assistant.delete_quick_message" to "Excluir mensagem rápida",
        "assistant.save" to "Salvar assistente",
        "request_overrides.headers" to "Cabeçalhos personalizados",
        "request_overrides.add_header" to "Adicionar cabeçalho personalizado",
        "request_overrides.header" to "Cabeçalho",
        "request_overrides.value" to "Valor",
        "request_overrides.delete_header" to "Excluir cabeçalho personalizado",
        "request_overrides.body" to "Corpo de solicitação personalizado",
        "request_overrides.add_body" to "Adicionar corpo de solicitação",
        "request_overrides.invalid_json" to "Insira JSON válido",
        "provider.balance_query" to "Consulta de saldo",
        "provider.balance_api_path" to "Caminho da API de saldo",
        "provider.balance_result_path" to "Caminho JSON do resultado",
        "provider.checking_balance" to "Consultando saldo...",
        "provider.current_balance" to "Saldo atual: %s",
        "provider.balance_failed" to "Falha na consulta de saldo: %s",
        "provider.check_balance" to "Consultar saldo",
        "provider.connection_success" to "Conectado · %d modelos disponíveis",
        "agent.approval_request" to "O agente solicita esta operação. Permitir?",
        "agent.allow" to "Permitir",
        "agent.deny" to "Negar",
        "agent.local_shell_warning" to "O shell local é executado com as permissões do seu usuário atual. Confirme o comando e o impacto.",
        "agent.write_warning" to "As alterações de arquivos são limitadas ao diretório do espaço de trabalho selecionado.",
        "timeline.execution" to "Execução",
        "timeline.expand_execution" to "Expandir execução",
        "timeline.collapse_execution" to "Recolher execução",
        "timeline.expand_steps" to "Expandir %d etapas",
        "timeline.reasoning" to "Raciocínio",
        "timeline.reasoning_duration" to "Raciocinou por %s segundos",
        "jumper.top" to "Ir para o início",
        "jumper.previous" to "Mensagem anterior",
        "jumper.next" to "Próxima mensagem",
        "jumper.bottom" to "Ir para o fim",
        "dialog.translate_message" to "Traduzir mensagem",
        "dialog.target_language" to "Idioma de destino",
        "dialog.compress_history" to "Compactar histórico da conversa",
        "dialog.compress" to "Compactar",
        "dialog.target_tokens" to "Tokens de destino",
        "dialog.keep_recent_messages" to "Manter mensagens recentes (de %d no total)",
        "stats.messages" to "Mensagens",
        "stats.attachments" to "Anexos",
        "settings.send_on_enter" to "Enviar com Enter",
        "settings.auto_scroll" to "Rolagem automática",
        "settings.message_navigation" to "Navegação de mensagens",
        "settings.message_navigation_left" to "Navegação de mensagens à esquerda",
        "settings.show_user_avatar" to "Mostrar avatar do usuário",
        "settings.user_nickname" to "Apelido do usuário",
        "settings.show_model_icon" to "Mostrar ícone do modelo",
        "settings.show_model_name" to "Mostrar nome do modelo",
        "settings.assistant_bubble" to "Balão do assistente",
        "settings.message_timestamp" to "Horário da mensagem",
        "settings.reasoning" to "Conteúdo do raciocínio",
        "settings.collapse_reasoning" to "Recolher raciocínio após a conclusão",
        "settings.code_wrap" to "Quebrar linhas em blocos de código",
        "settings.export_backup" to "Exportar backup",
        "settings.export" to "Exportar",
        "settings.import_backup" to "Importar backup",
        "settings.import" to "Importar",
        "settings.reset_data" to "Redefinir todos os dados",
        "settings.reset" to "Redefinir",
        "settings.reset_confirmation_title" to "Redefinir todos os dados?",
        "settings.confirm_reset" to "Redefinir dados",
        "settings.web_search" to "Serviço de pesquisa na web",
        "settings.searxng_url" to "URL do SearXNG",
        "settings.search_result_count" to "%d resultados por pesquisa",
        "settings.test_search" to "Testar pesquisa",
        "settings.search_test_success" to "A conexão de pesquisa na web está funcionando",
        "settings.search_test_failed" to "Falha no teste de pesquisa",
        "settings.add_assistant" to "Adicionar assistente",
        "settings.assistant_name" to "Nome do assistente",
        "settings.copy_assistant" to "Copiar assistente",
        "settings.delete_assistant" to "Excluir assistente",
        "settings.tags" to "Tags (separadas por vírgulas)",
        "settings.model_inherit" to "Modelo (deixe em branco para usar o padrão do provedor)",
        "settings.select_model" to "Escolher modelo",
        "settings.system_prompt_inherit" to "Prompt do sistema (deixe em branco para usar o padrão do provedor)",
        "settings.add_provider" to "Adicionar provedor",
        "settings.provider_name" to "Nome do provedor",
        "settings.delete_provider" to "Excluir provedor",
        "settings.base_url" to "URL base",
        "settings.api_key" to "Chave da API",
        "settings.model" to "Modelo",
        "settings.test_and_fetch_models" to "Testar e buscar modelos",
        "settings.save_provider" to "Salvar provedor",
        "model_picker.refresh_balance" to "Atualizar saldo de %s",
        "model_picker.current_model" to "Modelo atual",
        "model_capability.text" to "Texto",
        "model_capability.vision" to "Visão",
        "model_capability.reasoning" to "Raciocínio",
        "model_capability.tools" to "Ferramentas"
    )
)
